### ISSUE TITLE
Preset search for "Eingang" does find entrance preset

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1012]
Description:
---

The German (de_DE) translation is Eingang, but the search does not find it.

Device info:
---
<table>
<tr><td>App version</td><td>14.0.0.2</td></tr>
<tr><td>App version code</td><td>1301</td></tr>
<tr><td>Android build version</td><td>0d27</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPOS29.114-134-2</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>ocean</td></tr>
<tr><td>Device model</td><td>moto g(7) power</td></tr>
<tr><td>Device product name</td><td>ocean_reteu</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>HolgerJeromin</td></tr>
</table>

**Comment by simonpoole** [comment]
Thanks for the report. The problem was that because entrance is a fairly popular key it got a low default weight which led to it dropping out of the top 10 results, which would normally then be adjusted by re-scaling the weight because it is an exact or partial match for "Eingang" however that wasn't using the translated name.

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/422aebed2b521a0f1647104a6f3da346b18628f4
