### ISSUE TITLE
Could not save task-changes for osmose (and most) tasks

### ISSUE THREAD

**Issue by zyphlar** [MarcusWolschon/osmeditor4android#1022]
## Vespucci Version

13.1.9

## Download source

Google Play

## Device (Manufacturer and Model)

Samsung Galaxy S8

## Android Version 

9

## Behaviour/Symptoms

About 90% of task changes (osmose, maproulette, notes, etc) fail to upload, either by the data upload feature or by clicking the upload button on the task directly. I have a maproulette key entered in the format 1234|1234abc-1234abc...

## Expected Behaviour

Task changes should upload properly.

If there is an issue, the appropriate resolution or exact upstream error should be communicated.

Changes which fail to upload should either be cached for future upload retries or should be reverted in my version to their previous state so I can manually try again.

## How to recreate

1. Be me
2. Install vespucci
3. Copy-paste your OSM and Maproulette credentials
4. Edit a lot of stuff
5. Notice that everything works except saving tasks/bugs.

## Crash dump submitted (no or yes + date)

No

## Any other potentially relevant information

Attached screenshot

![](https://i.imgur.com/E4gg7hR.jpg)

**Comment by simonpoole** [comment]
This is likely due to issues with one of the servers, most likely the OSMOSE server. 

Task objects are only marked as uploaded when it has actually successfully happened, so there should never be any data loss simply because an upload failed (have you actually checked if the tasks in question have been updated?).

Further note: I don't know which OSM credentials you copy & pasted, but it doesn't sound if it was something that you should be doing. If you are using the standard OSM servers you should be using OAuth, which will automatically ask you to authorize once, on your 1st upload. You should NOT be storing your display name and password on device.

**Comment by zyphlar** [comment]
It's been long enough that I've forgotten how my osm credentials were
entered, but they work fine.

I tested a maproulette task-close just now and it worked so it's possible
that this is osmose-specific. Most of the things I'm interested in updating
are osmose so we can treat this as if it were.

This is an example of an issue which I reported as closed in vespucci but
still appears open on osmose. It had a twin right next to it which I was
able to successfully close in the osmose website directly.

http://osmose.openstreetmap.fr/en/error/34260211194

**Comment by simonpoole** [comment]
The best way to debug this is to send a manual crash dump via the "Debug" menu item immediately after the issue has occurred, as in 13.1 the log excerpt included is rather short, it would probably make sense to upgrade to 14.0 beta.

**Comment by zyphlar** [comment]
Thanks for the advice regarding the beta version. I've downloaded it and
experimented and everything seems to be working much better now!

**Comment by simonpoole** [comment]
Well 14.0.3 soon 14.0.5 release is available, so you shouldn't actually be using the beta (because you won't get updates I believe). Closing the issue.
