### ISSUE TITLE
Pinch zoom runs away

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1047]
Description:
---

When doin pinch zoom-in, the zoom often runs off and I get 2m x  2m extreme close-up. Then I need to slowly zoom out to get the desired zoom level.

Device info:
---
<table>
<tr><td>App version</td><td>14.0.3.0</td></tr>
<tr><td>App version code</td><td>1305</td></tr>
<tr><td>Android build version</td><td>G930FXXS6ESI6</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>R16NW.G930FXXS6ESI6</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>herolte</td></tr>
<tr><td>Device model</td><td>SM-G930F</td></tr>
<tr><td>Device product name</td><td>heroltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8890</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>t-mu</td></tr>
</table>

**Comment by simonpoole** [comment]
I think I've been able to recreate when this happens (as nobody has actually indicated what they were doing different from normal, I could naturally be wrong). It seems to be speed related, that is un-pinching very fast will cause large scale values to be generated by Android. It is conceivable that this  could also happen accidentally.

https://github.com/MarcusWolschon/osmeditor4android/commit/6f25d0abd0d5081f35b7e5a225172efd59a0e63c limits the scale factor to between 0.8 and 1.2, and I've been unable to recreate extreme zooms since.
