### ISSUE TITLE
natural=bare_rock area displayed differently based on whatever it is a polygon or a multipolygon

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1054]
Description:
---

I would the same rendering in this two cars to make rendering less confusing.

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>14.0.9.0</td></tr>
<tr><td>App version code</td><td>1311</td></tr>
<tr><td>Android build version</td><td>V10.0.16.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.16.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
cars out of bare rock would confuse me too :-)

Seriously, there are two different issues here, the default colours for natural weren't the same for normal way rendering vs. multi-polygon (there isn't actually a specific rendering for bare_rock currently). That is fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/b5702f709811f06651b5bdfff88b06b10bd6488d

The 2nd issue is that there is currently no facility for implicit area rendering, so for objects that can be both linear and area objects there is currently no real way to get exactly the same rendering for both area types. 

2nd issue continued in https://github.com/MarcusWolschon/osmeditor4android/issues/1056
