### ISSUE TITLE
Order of numerical values is messed up

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#1071]
## Vespucci Version
14.0.12

## Download source
F-Droid

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
7.1.2

## Behaviour/Symptoms
When working with tag fields that contain numerical values, some exhibit strange behaviour in the dropdown menu that makes it difficult to quickly select values.

Example:

I create a new `amenity=bench`, then want to select the appropriate number of seats. The order of available keys is:

```
4
6
9
15
10
2
3
5
7
8
```

Other example:

I create a new restaurant and want to add its level. The order of values is:

```
5
0
20
19
... (etc.)
7
6
4
3
2
1
-1
-2
```

I assume that (some? all?) previously used keys move to the top, what in a way totally makes sense, but still makes it hard to properly select a desired value.

## Expected Behaviour

I don't have the ultimate solution. Some ideas:

- Separate used and unused values with a horizontal line or other visual means (bold font, different background color, ...)
- Order used keys numerically (instead of ordering them by last usage as it is currently done?)
- Keep used values in the list of unused values (these values will therefore appear twice in the list).

The aforementioned bench example would become something like:

```
4
6
9
10
15
---
2
3
4
5
6
7
8
9
```

## How to recreate

One may need to create tags before this behaviour appears.

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
> I assume that (some? all?) previously used keys move to the top, what in a way totally makes sense, but still makes it hard to properly select a desired value.

The system stores the last 10 most used values.

> ## Expected Behaviour
> 
> I don't have the ultimate solution. Some ideas:
> 
>     * Separate used and unused values with a horizontal line or other visual means (bold font, different background color, ...)
>
Different font might be possible with an acceptable effort, all the rest will not work, as it is not possible to have a non-selectable value in the an autocompletetext widget. 

I've been thinking of replacing the current widget with a number selector, however that wouldn't really solve the problem either.
 
>     * Order used keys numerically (instead of ordering them by last usage as it is currently done?)
Potentially this could be a preset attribute.

>     * Keep used values in the list of unused values (these values will therefore appear twice in the list).

That could be done specifically for numerical values.

**Comment by jajajaneeneenee** [comment]
A preset attribute like values_sort="fixed" would really be nice (I already expected that with values_sort="false", but this only prevents the alphabetical sorting) ... with the result that a list of values is not sorted alphabetically AND does not show the last 10 most used values at top ... It makes me crazy, that the order of list elements is always different (caused by the 10 most used values at top) – specially with large lists (e.g. surface).

And a Vespucci preference option to completely DISABLE the 10 most used values at top would also be nice ... I think, I would activate this. For me it's easier to always have a list in the same order ... easier for the brain to find an element.

Off topic: the changing order in the Vespucci main menu and the toolbar also makes me a little crazy .... e.g. I am very often searching for "copy" or "delete" ... it feels like a sportive challenge to find it in the menu (like values in a list) ... I often hit at the wrong place, because it has moved again to somewhere else. Is this behaviour not quite contrary to a good GUI and usability concept?

**Comment by simonpoole** [comment]
The MRU tag functionality was introduced because users wanted it, I'm not completely convinced that turning it off at the preset field level would work and not just simply confuse things more.

> Off topic: the changing order in the Vespucci main menu and the toolbar also makes me a little crazy .... e.g. I am very often searching for "copy" or "delete" ... it feels like a sportive challenge to find it in the menu (like values in a list) ... I often hit at the wrong place, because it has moved again to somewhere else. Is this behaviour not quite contrary to a good GUI and usability concept?

The order doesn't change. There are some items that are shown or hidden depending on context, in principle it would  be better if they where just enabled/disabled, but that would make the lists even longer. The "too many possible actions" tends to be a problem over all GIS programs and there is no really good way to solve it (there might be some change here in the future, see also https://github.com/MarcusWolschon/osmeditor4android/issues/841

**Comment by jajajaneeneenee** [comment]
I can understand that a solution on the preset field level is not the best solution – I was thinking at my very personal custom presets and that I could use it there at least, if no other solution takes place ...

But I would appreciate a Vespucci preference option to turn off the MRU tag functionality completely a lot! It's perhaps the easiest solution and cannot be wrong, even if other solutions would follow. I also read #841: +1 !

I can understand that other users wanted this functionality (I think it could have been #557 of May 2017 ...), and surely it's nice in some (or many) conditions, but I am not sure if all consequences have been seen at that time. For me, the cons outweigh the pros I think (at least in the current implementation of the functionality) ...

E.g. I just created a custom preset for an item which used the "direction" key with these display_values:

`"Forward,Backward,N (0°),NNE (22.5°),NE (45°),ENE (67.5°),E (90°),ESE (112.5°),SE (135°),SSE (157.5°),S (180°),SSW (202.5°),SW (225°),WSW (247.5°),W (270°),WNW (292.5°),NW (315°),NNW (337.5°)"`

(= the cardinal directions in clockwise order – see [wiki](https://wiki.openstreetmap.org/wiki/Key:direction#Angles_and_cardinal_directions)).

And after some edits, the list can look like that – no fun at all to find the right value quickly:
![Direction](https://user-images.githubusercontent.com/48966999/90842278-2cb9e500-e35f-11ea-8af4-99147f1d9830.jpg)

I hope, it's clear what I mean ...

**And for the order in the Vespucci main menu:** 
OK, I understand. I really thought the commands would change position like the MRU tag functionality. I will keep an eye on that. Perhaps such commands like "copy/paste/copy tags/delete" should ALWAYS be on top? (If s.th. is selected). And separators (like thin lines?) to group some commands would perhaps improve the visual clarity – if this is possible without producing too much additional space. Then you could also reduce the line spacing a little which is quite high on my device (if this is possible to reduce the length of the list).
