### ISSUE TITLE
Modal dialogues can be closed

### ISSUE THREAD

**Issue by johantiden** [MarcusWolschon/osmeditor4android#1089]
## Vespucci Version
14.0.9

## Download source
F-droid

## Device (Manufacturer and Model)
Google Pixel 3 Plus

## Android Version 
10
4.9.185-g9f181f6db9d7-ab6027027
#0 Fri Nov 22 18:17:08 UTC 2019

## Behaviour/Symptoms
Modal dialogues e.g. "Downloading data from server" can be closed, allowing further actions while the task completes in the background.

## Expected Behaviour
The user should be locked in while waiting for the task to finish.

## How to recreate
1. Tap Transfer... > Download current view. The modal dialog pops up while downloading.
2. Tap outside of the dialog. The dialog is closed.

## Crash dump submitted (no or yes + date)
No

**Comment by johantiden** [comment]
This opens up many possibilities to get the app to behave erraticly. The user can "queue" up multiple tasks.

For instance, you can download the current view, the zoom around and download another view. Doing this will add a large delay on the

**Comment by simonpoole** [comment]
I can see your point with respect to manually downloading multiple areas were they might not complete in the same order as started, however my response to that would be: then don't do it. Because it is really only an issue if you start another download before the initial one has either failed (you will get a message), or completed. 

Note the download process is -always- completely asynchronous, what you are cancelling is simply the spinner display. 

All the automatic download options specifically don't zoom to the downloaded areas to avoid the problem you are describing

**Comment by johantiden** [comment]
I can reproduce this using the Osmose warnings dialogue on an item that has not been downloaded. It will download an area and _then_ zoom.
