### ISSUE TITLE
Support ESRI MapServer (was Unable to add a custom layer with {bbox})

### ISSUE THREAD

**Issue by zstadler** [MarcusWolschon/osmeditor4android#1092]
## Vespucci Version
14.0.9

## Download source
google play store

## Device (Manufacturer and Model)
Oneplus 7 (GM1900)

## Android Version 
10

## Behaviour/Symptoms
Unable to add a custom layer which uses `{bbox}`,`{width}`, and `{height}` to access a MapServer with the `export` API.

## Expected Behaviour
The URL below, _as an example only_, would show as a background.

## How to recreate
- Preferences -> "Custom layers" -> "+"
- Name: `MapServer export`
- URL: 
   ```
   https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/export?bbox={bbox}&bboxSR=3857&imageSR=3857&size={width},{height}&f=image
   ```
- "Save and set" -> "Done" -> Back

The newly defined layer does not show.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
The following URL, where `{bbox}` was replaced by a fixed bbox (3857 projection), is seen as a background with the same tile in every zoom and location.
```
https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/export?bbox=3868325.1274561994,3733795.957674291,3869548.1199087612,3735018.950126853&bboxSR=3857&imageSR=3857&size={width},{height}&f=image
```

**Comment by simonpoole** [comment]
It is as simple as that we currently don't support MapServer, see http://vespucci.io/tutorials/custom_imagery/#adding-a-custom-imagery-source While supporting proprietary protocols and solutions is not a top priority (just consider the irony of spending free time on supporting a multi-billion US company), if you can provide documentation I'm willing to have a look at it.

**Comment by zstadler** [comment]
This issue requests that the replacement of placeholders in URLs will be performed as documented.

The above example URL is as a valid WMS server entry, as defined in the documentation: it contains __{width}__, __{height}__ and __{bbox}__ placeholders. It also does not contain a __{proj}__ placeholder.

https://github.com/MarcusWolschon/osmeditor4android/blob/1fe1927d5603b55ee591dc5cedb21e14199038eb/documentation/docs/tutorials/custom_imagery.md#L52

The documentation says Vespucci will perform the following replacements in a URL:

https://github.com/MarcusWolschon/osmeditor4android/blob/1fe1927d5603b55ee591dc5cedb21e14199038eb/documentation/docs/tutorials/custom_imagery.md#L43-L47

If these replacements had taken place, the example URL would have worked. This is demonstrated by using another URL where the __{bbox}__ placeholder was manually replaced by some arbitrary bounding box in EPSG:3857 coordinates.

It seems like a bug rather than an enhancement. Some code, or fault in the code, introduces an undocumented behavior which prevents the a appropriate replacement of the __{bbox}__ placeholder for some URLs that do qualify as a valid WMS server entry.

**Comment by simonpoole** [comment]
It really isn't a bug. The "valid WMS entry" is referring to which placeholders need to be used in an URL that is otherwise a valid WMS entry, that means in particular that it has a **proj** and **version** attribute (the version is only required for WMS 1.3 and later servers that use projection dependent bounding box coordinate ordering). 

The difference between the WMS entries in ELI and entry via the custom imagery form, is that ELI contains a list of supported projections that are used to fill in the proj, and in the custom imagery form it needs to be present in the URL (which it will be because a valid WMS URL must contain it). In the 2nd case Vespucci extracts the projection value from the URL, without the projection value there is no way the app can know if 

a) the projection is one of the two supported ones

b) which transformation to apply to the coordinates and raster image

That the example with a hardwired bbox does something is because per default the URLs are treated as normal tileserver URLs, which will lead to exactly the result you describe, the same image in all tile positions.

For rudimentary MapServer support we would need to do essentially the same as for WMS servers, that is have a way of determining that it is a MapServer URL, and extracting the available projection in a robust way, assuming that otherwise the behaviour is the same as for a WMS server.

**Comment by simonpoole** [comment]
Relevant ESRI documentation https://developers.arcgis.com/rest/services-reference/export-map.htm

**Comment by grischard** [comment]
You can use:

- the wmts at https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/wmts
- the wms at https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/wms
- the tms at https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tms

**Comment by simonpoole** [comment]
@grischard the question is more if all MapServer instances have equivalent tms/wms services available and if they are "automatic", have the same content as the native service.

**Comment by grischard** [comment]
Most do. Some also have `/tiles` instead of or as a synonym of `/tms`.

**Comment by simonpoole** [comment]
Documentation clarified in https://github.com/MarcusWolschon/osmeditor4android/commit/2614ac1f91cd7deafddd1d6889c62c7cba2fba01

**Comment by zstadler** [comment]
Given the documentation update I still not understand what's wrong with the URL listed in the issue:

```https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/export?bbox={bbox}&bboxSR=3857&imageSR=3857&size={width},{height}&f=image```

It has ___{width}__, __{height}___, and ___{bbox}___ placeholders, and it does not have a __{proj}__ placeholder, just as the documentation describes

**Comment by simonpoole** [comment]
It isn't a valid WMS layer URL, it's an ESRI mapserver URL.

**Comment by zstadler** [comment]
I would expect the Vespucci documentation to define what are its criteria for a valid WMS layer.

**Comment by simonpoole** [comment]
> I would expect the Vespucci documentation to define what are its criteria for a valid WMS layer.

See https://portal.ogc.org/files/?artifact_id=14416 in particular page 34 ff.
