### ISSUE TITLE
Adding autopreset for driveway doesn't work

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1095]
Vespucci 14.0.15
Android 9
Samsung Galaxy A7 (2018)

I try to create a custom preset for a driveway but it doesn't work. Steps:

1. Create a way
2. Add the tags `highway=service` and `service=driveway`
3. Tick the boxes of both tags
4. Select "Create custom preset" (or similar, I have the German version) and save
5. Try to apply the preset to another way

Outcome: 
The way only gets `highway=service` applied

Expected outcome:
The way receives both tags

**Comment by simonpoole** [comment]
Thanks for the report. 

The issue was that when possible we try to inherit the properties of the field from the original preset, which in this case (the "service" tag in the "Service" preset) has the "optional" attribute set. So the information was being added to the preset as excepted, applying the preset simply didn't automatically add it because it was optional.

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/46f84e0dc0de4b80394f3a954da008d4976b3783
