### ISSUE TITLE
Issues with gestures on Android 10

### ISSUE THREAD

**Issue by Atrate** [MarcusWolschon/osmeditor4android#1098]
With Android 10's new immersive gestures mode (which remove the navbar completely) using Vespucci presents a few issues.

This is for example the fact that swiping from the bottom of the screen does not trigger an Android gesture like it should, but instead opens one of the icon's drop-down (pull-up) menu and immediately selects an option, which is annoying to say the least and can lead to unwanted consequences.

**Comment by simonpoole** [comment]
And what do you propose to do about it?

**Comment by Atrate** [comment]
Haven't really thought about it much but maybe allow placing the bar at the top?

**Comment by simonpoole** [comment]
You can already:

- place the bar at the top
- turn off full screen mode for broken devices

the question is what else do you suggest?

**Comment by Atrate** [comment]
Oh yes, forgot about placing the bar at the top.

It still requires two swipes to use a gesture, but at least it works now.

I'll leave this issue open for a while if anyone has suggestions

**Comment by simonpoole** [comment]
Back from vacation and have been able to read up on this and actually try on a Android 10 phone. The two swipes from the bottom are actually what according to google is supposed to happen for apps in full screen mode, so that isn't a defect.

Best workaround is now described in http://vespucci.io/tutorials/faq/#navigation-gestures-on-android-9-and-later

As the gesture feature itself conflicts fundamentally with the way Vespucci's UI is set up and the Android software components used, a "real" fix would require a complete rework of the map and action UIs, which, best guess, is likely half a man year of work.

I'm leaving this open as an enhancement request.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/c3e3d5512cfb9c0e5ba2e8bb91b5051c225dcf3f checks if gesture mode is turned on (in a completely undocumented way) and if that is so, doesn't enable full screen mode. This seems to go fairly far towards solving the issue on the devices I've tested. Accessing the back button is rather iffy tough.

**Comment by simonpoole** [comment]
Testing on a Android 10 tablet would indicate that the fix works well enough.
