### ISSUE TITLE
GPX import fails

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#1099]
## Vespucci Version
14.0.15

## Download source
F-Droid

## Device (Manufacturer and Model)
Nokia 6.1 (TA-1089)

## Android Version 
v9

## Behaviour/Symptoms
No track drawn

## Expected Behaviour
GPX track is drawn

## How to recreate
Location menu - GPX track management - Import GPX track - select a track (mine are invariably created by OsmAnd)

## Crash dump submitted (no or yes + date)
Yes, 2020-02-17

## Any other potentially relevant information
I was able to open the attached file in Vespucci yesterday. Today it won't open.

**Comment by simonpoole** [comment]
Did you have the issue again?

**Comment by contrapunctus-1** [comment]
Can still reproduce with v14.1.4.0 from F-Droid.

**Comment by simonpoole** [comment]
Could you attach a current GPX file that shows the issue (and I believe I asked on IRC from where you were trying to load the file).

**Comment by simonpoole** [comment]
Any more input on this?

**Comment by contrapunctus-1** [comment]
When I tried to open a GPX file with Simple File Manager v6.7.3 from F-Droid, Vespucci is not offered as an application.

I'll try to attach it.

**Comment by simonpoole** [comment]
I suspect the issue here is fuzziness around "GPX import". 

Could you confirm that going to the GPS/GNSS menu, "GPX track management" and then selecting "Import GPX track" works or not?

I suspect what you are actually doing is opening a GPX file in a file manager etc and then expecting it to open in Vespucci. This is highly file manager dependent, and while https://github.com/MarcusWolschon/osmeditor4android/commit/4c5a57a8e5f64915731e219f6f1d621c4492443d added support for some more variants for 15.0 there is no guarantee that all are covered now.

**Comment by simonpoole** [comment]
Both versions work for me (opening via filemanger depends strongly on the file manager in question, there were some improvements in 15.0 to cover a few more cases), see

![Screenshot_1599137744](https://user-images.githubusercontent.com/1011860/92118140-5ad70480-edf6-11ea-9412-5ab01033cc53.png)

**Comment by contrapunctus-1** [comment]
When the file was in Android/data/net.osmand.plus/files/tracks/
* ❌ opening with SFM
* ❌ opening with Import GPX Track

When the file was in Vespucci's own folder
* ✅ opening with SFM
* ✅ opening with Import GPX Track

When the file was in the internal storage root -
* ✅ opening with SFM
* ❌ opening with Import GPX Track

**Comment by simonpoole** [comment]
> 
>     * ❌ opening with SFM
> 
>     * ❌ opening with Import GPX Track
> 

OK, so it boils down to not getting an error message in that case (as the behaviour is to be expected).

**Comment by contrapunctus-1** [comment]
I faced inconsistencies in some cases too - the same test not working at one time and working later. I'll post if I run into it again. 🤔

**Comment by simonpoole** [comment]
The inconsistencies are due to the Androids way of handling file access in modern Android versions, in general it is not possible to access files created by other apps except if they have been created in the "Download" folder. 

To make things extra complicated the behaviour also depends on which version of Android the apps in question were built against In particular if they can have access to a stable external directory (in the Vespucci case the "Vespucci" directory) depends on this, and will be going completely away with Android 11, except for the Download directory. So really the question is why you don't see an error message (which imho is the real question here).

**Comment by simonpoole** [comment]
Closing for now
