### ISSUE TITLE
issue with data upload for private OSM (Rails of Port) server

### ISSUE THREAD

**Issue by hthouse** [MarcusWolschon/osmeditor4android#1138]
## Behaviour/Symptoms
I am able to download current view from private OSM (The Rails Ports) however, not able to upload data to the OSM server. I get the following error 
"Could not upload
The API responded with error, please save your data and report the issue:
Cannot parse valid changeset  from xml string. Must specify string with one or more characters"_
I have tried the private server with JOSM and it works well with basic auth (username and password only) and with OAuth. For the OAuth in JOSM I have to configure JOSM manually with the consumer key and secret.

## Expected Behaviour
Upload data to the server

## How to recreate
standup OSM (rails of ports) on AWS or virtual sandbox as per the:
https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md
and bulk upload sample osm file. install Vespucci and JOSM and configure them with new server url.

**Comment by simonpoole** [comment]
OAuth will definitely not work as there is currently no way to configure client keys on a per API base (this might however be coming in a future release). I have a local rails port instance here and will test (for obvious reasons the basic auth code is not exercised a lot).

**Comment by simonpoole** [comment]
I suspect I remeber what the issue is, are you running the rails-port with the rails internal server by any chance?

Because iirc that doesn't support chunked http uploads, and that is what the TCP library that Vespucci uses always does. I suspect if you run the the rails-port with a "proper" web server the problem will go away.

**Comment by simonpoole** [comment]
Fixed title as the issue in not authentication related

**Comment by simonpoole** [comment]
I've spent some time on this now and have tested with Thin, Puma and Webrick ruby servers (as they all would be OK for a dev setup),. and even though the chunked request issue turns up on all issue trackers, literally years ago (as in half a decade and more), they seem to be totally inconclusive if the issue was ever fixed.

Note I can run Vespucci vs the OSMF dev server with OAuth turned of and using basic auth with no problem, so I maintain that the error is actually on the rails side of things (which the error message would imply too). Maybe @tomhughes or @gravitystorm want to weigh in (as my rails know how is not very much different from 0).

![Screenshot_1583880885](https://user-images.githubusercontent.com/1011860/76366807-550ed380-632b-11ea-9a6c-372e0d689aa3.png)

**Comment by simonpoole** [comment]
@hthouse waiting  on feedback from you, as there is not really anything I can do about this.

**Comment by hthouse** [comment]
Thank you, @simonpoole , I appreciate the help. Vespucci is a great mobile OSM editor that we want to use for our project and have been trying to get it to work (upload edits) in the dev. environment, that has been the challenge. However, we are trying to install the OSM-website (the rails port) on Phusion Passenger production environment  to see if Vespucci behaves same way as with the public OSM.

**Comment by hthouse** [comment]
It works when openstreetmap website is installed on the Phusion Passenger.  I only able to get the  Basic Auth to work.

**Comment by mmd-osm** [comment]
> Note I can run Vespucci vs the OSMF dev server with OAuth turned of and using basic auth with no problem, so I maintain that the error is actually on the rails side of things (which the error message would imply too

Not sure if this relevant here: even on the OSMF dev server the changeset upload is handled by CGImap. So you were not really testing an Apache web server against a Rails backend here.

Reference: https://github.com/openstreetmap/chef/blob/master/cookbooks/dev/templates/default/apache.rails.erb#L52

**Comment by simonpoole** [comment]
> 
> 
> It works when openstreetmap website is installed on the Phusion Passenger. I was only able to get the Basic Auth to work.

When you are running your own server and want to use OAuth you need to

- generate an OAuth client key on your server (you can do that from any user account currently)
- add an entry to src/main/res/values/apis.xml

**Comment by simonpoole** [comment]
> 
> 
> > Note I can run Vespucci vs the OSMF dev server with OAuth turned of and using basic auth with no problem, so I maintain that the error is actually on the rails side of things (which the error message would imply too
> 
> Not sure if this relevant here: even on the OSMF dev server the changeset upload is handled by CGImap. So you were not really testing an Apache web server against a Rails backend here.
> 
I was a bit sloppy there, but essentially it was just a question of if basic auth worked in principle, which it does.

As pointed out the actual issue is that none of the rails light weight / dev https servers support chunked requests (even though it has been part of the standard for ages).
