### ISSUE TITLE
Removing name not possible in multiselect

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1158]
Description:
---

I had two nodes with:

historic=wayside_shrine
name=Heiligenhäuschen

Selecting both and edit.
Select full name string. 
Delete. 
Leaving the editor kept the names.
Selecting only one node worked as expected.

Device info:
---
<table>
<tr><td>App version</td><td>14.1.3.0</td></tr>
<tr><td>App version code</td><td>1406</td></tr>
<tr><td>Android build version</td><td>21fefe</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPOS29.114-134-10</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>ocean</td></tr>
<tr><td>Device model</td><td>moto g(7) power</td></tr>
<tr><td>Device product name</td><td>ocean_reteu</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>HolgerJeromin</td></tr>
</table>

**Comment by HolgerJeromin** [comment]
It works when i remove the full row (including name)

**Comment by simonpoole** [comment]
I wouldn't classify this as an issue. just as an oddity that is due to the subject matter. 

When you are editing tags in multi-select mode "nothing" in the value field indicates "don't change this", typing in a text means: add this tag with this value to all selected elements. 

Deleting the whole row or the key field is the correct way to delete a tag completely as you've noticed.

**Comment by HolgerJeromin** [comment]
Ok, I understand. Hard to change to something more intuitiv.
