### ISSUE TITLE
Defibrillator labeled as building

### ISSUE THREAD

**Issue by pyrog** [MarcusWolschon/osmeditor4android#1231]
## Vespucci Version
15.0.3

## Download source
google play store

## Device (Manufacturer and Model)
Samsung Galaxy s6 **SM-G30F**

## Android Version 
8.0.0

## Behaviour/Symptoms
1. Long press on a POI (an AED. The node is part of a building)
2. Vespucci list display
- Townhall (building)
- Building

## Expected Behaviour
Should display
- Townhall (defibrillator)
- Building

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
https://www.openstreetmap.org/node/7875614680

**Comment by simonpoole** [comment]
This is simply a misunderstanding. The object(s) listed in parentheses are the parent objects (if any), not the type of the object. This is simply a help to be able to differentiate between multiple overlapping objects that might be members of different ways or relations.

In the specific case things simply conspire to make things look silly, in particular because a name is set on the defibrillator, which as a general rule will be displayed as the objects description with preference over anything else. 

A possible way to make this more would be  to support https://github.com/MarcusWolschon/osmeditor4android/issues/1232
