### ISSUE TITLE
Tweak preset matching to reduce spurious matching on non-object tags

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1241]
Description:
---

I use leisure (not landuse) for recreation gtound (better key, avoids clash with US usage for any place where a leisure activity takes place, e.g. inbounds of ski areas). Adding a surface tag of grass to one such object, results in sport=cycling to also appear. This happens reproducibly on this object, I havent tried to repeat elsewhere. Any ideas? J

Device info:
---
<table>
<tr><td>App version</td><td>15.0.3.0</td></tr>
<tr><td>App version code</td><td>1504</td></tr>
<tr><td>Android build version</td><td>T510XXU3BTFN</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.T510XXU3BTFN</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>gta3xlwifi</td></tr>
<tr><td>Device model</td><td>SM-T510</td></tr>
<tr><td>Device product name</td><td>gta3xlwifieea</td></tr>
<tr><td>Device hardware name</td><td>exynos7904</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>SK53</td></tr>
</table>

**Comment by simonpoole** [comment]
The behaviour is a bit of an edge case in the preset matching, normally this wouldn't match at all, as there in no preset (currently) for leisure=recreation_ground. However there are a number of sport presets that allow setting leisure to anything, which gets them included in the list of potentially matchable objects, which then caused (because nothing else -actually- matched) the surface tag to be used for scoring.

https://github.com/simonpoole/beautified-JOSM-preset/commit/9c04763184a784c5a5b30f8692dc4f9d4cc02ae5 fixes the specific issue, however not the underlying cause.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/20afb32f6e46e4649a7186a8874fe24c7592d951
