### ISSUE TITLE
Latest apk(s) not found

### ISSUE THREAD

**Issue by ChiefMikeK** [MarcusWolschon/osmeditor4android#1252]
- F-Droid = 15.0.2.0 see #1163
- Google play = September 6
- Github = zip only after 15.0.4.0
- apkpure =  15.0.3.0

**Please update links on the website  _Vespucci.io_**
ie. add a note after the link, m@ybe?

**Comment by simonpoole** [comment]
The release process is typically 

I tag a release and generate the unsigned APKs - @MarcusWolschon signs the APK and uploads the signed files to the play store and the repo. 

I tagged 15.05 mid this week and the signed APKs will be available as soon as Marcus has time. With other words you can't find the APKs because they are not available yet. APKs signed with my dev key are available from https://drive.google.com/drive/folders/0B9pKLmh8s1h8TnJCS0FjMnQybWc see the README for instructions.

As you can see from  https://github.com/MarcusWolschon/osmeditor4android/issues/1163 distribution on F-Droid is not under our control, you can naturally lobby them to fix their broken auto-update procedure, but I wouldn't hold my breath. I have no information on how and what apkpure is distributing, I suspect they are now and then copying the google play distribution, but again nothing we have anything to do with.
