### ISSUE TITLE
Add exit button

### ISSUE THREAD

**Issue by MakiWolf** [MarcusWolschon/osmeditor4android#1301]
It would be great, when the app has an exit button.

![Screenshot_20201207-182248_Vespucci.jpg](https://user-images.githubusercontent.com/73300633/101383593-9f70b100-38b9-11eb-930f-e3231450101d.jpg)

**Comment by simonpoole** [comment]
Why would you need that? Pressing the back button already provides the functionality.

**Comment by MakiWolf** [comment]
Because there is a button overlay, when you click on the ![grafik](https://user-images.githubusercontent.com/73300633/101390088-959f7b80-38c2-11eb-92eb-4bf66545859f.png) button and the back button only exits the context menu, when the app is in fullscreen mode. I know that I can also press the home button to go back, but I think it would be great when there is also an exit button in the context menu to close the app.

![grafik](https://user-images.githubusercontent.com/73300633/101389508-d3e86b00-38c1-11eb-872c-ab0a4e081a2a.png)

**Comment by simonpoole** [comment]
When in full screen mode (you can always turn it off) there are essentially three modi (dependent on you device and Android version, not dependent on Vespucci):

- full screen mode with navigation bar, available since Android 4.4: swipe up from the bottom edge to get the navigation bar and the back button,
- navigation with bottom gestures (implies at least nearly full screen mode), iirc available since Android 9: back button is either a swipe up on the left or the right side of the bottom edge depending on how you set things up,
- navigation with "full" gestures (implies full screen mode), available from Android 10 on, back is a swipe from the bottom of the left or right edge.

There are some phones that have broken full screen navigation, however this tends to affect navigation in dialogs, not exiting the app, if your phone has such issues I can add it to the list of phones for which full screen mode gets turned off.

Pressing the home button doesn't necessarily exit the app in any of the above scenarios, it will however typically pause it and the OS might at some point destroy the app, but there is no requirement for that to happen.

The overlay you are seeing is shown by the OS when you select a menu, and is mainly shown so that you can dismiss a menu, it is not the user activated navigation bar.

**Comment by MakiWolf** [comment]
Swipe up from the bottom edge to get the navigation bar and the back button. That have fixed that for me. Thanks a lot.
