### ISSUE TITLE
Geen openstreetmap data

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1304]
Description:
---

Ik ben net geüpdate naar v15.1 maar ik zie geen plattegrond .... In deze versie.

Device info:
---
<table>
<tr><td>App version</td><td>15.1.0.0</td></tr>
<tr><td>App version code</td><td>1603</td></tr>
<tr><td>Android build version</td><td>00WW_4_15I</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>00WW_4_15I</td></tr>
<tr><td>Device brand</td><td>Nokia</td></tr>
<tr><td>Device manufacturer</td><td>HMD Global</td></tr>
<tr><td>Device name</td><td>PL2_sprout</td></tr>
<tr><td>Device model</td><td>Nokia 6.1</td></tr>
<tr><td>Device product name</td><td>Plate2_00WW</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Jvitegem"/>Jvitegem</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Which version did you have installed before? And a screenshot might be helpful, I assume you are referring to not having any background imagery with "no map"?

**Comment by JoopiJansen** [comment]
I upgraded from v14.1 because 15.0.2 crashed on my device
I am referring to having no background imagery at all.
I don't know what you mean with "really no OSM data".

**Comment by simonpoole** [comment]
Well the title say "No OpenStreetMap data" and the content of the issue says something else, just trying to determine what is actually happening. 

15.0 had substantial changes to layer management http://vespucci.io/help/en/15.0.0%20Release%20notes/#improved-layer-support in particular layers can be completely removed and the order changed. You should check if you actually have a background layer added in the layer control and that it is visible, we do try to auto-migrate the existing settings from previous versions, but that can go wrong.

Note the crash issue with 15.0 was simply a matter of removing existing data because in some cases that had become corrupted, pointed out in the 15.0 release notes, the vespucci twitter account, the OSM diaries and multiple issues here.

**Comment by simonpoole** [comment]
@JoopiJansen ping

**Comment by JoopiJansen** [comment]
After reentering my openstreetmap authorisation and "Clear and download current area" command
It works again..

I could not remove existing data in 15.0 because it crashed before I could do anything.

**Comment by simonpoole** [comment]
OK, closing as resolved.
