### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [MarcusWolschon/osmeditor4android#1322]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by simonpoole** [comment]
The problem is that doing anything with f-droid is fraught with difficulty, for example we wouldn't actually be able to test if added the screenshots work, except when once in a blue moon a random version is published on f-droid. So I would need a lot more convincing to add stuff just on the hope that it might one day get used.

**Comment by simonpoole** [comment]
To illustrate why this is likely going to go nowhere, I just notices that for some reason F-Droid is distributing the 1st beta of 15.1 from November last year as the current release and without noting that it is a beta.

**Comment by simonpoole** [comment]
Further general note: PRs are naturally welcome.

**Comment by simonpoole** [comment]
Actually any PRs to do with F-Droid are not welcome, see also https://github.com/MarcusWolschon/osmeditor4android/issues/1459

**Comment by Korb** [comment]
Still no screenshots [at F-Droid](https://f-droid.org/packages/de.blau.android/):

![Screenshot_2023_1104_170223_org fdroid fdroid](https://github.com/MarcusWolschon/osmeditor4android/assets/3509797/1a8110f9-1e3e-4ee4-80b0-c2211126714d)
