### ISSUE TITLE
Vespucci crashes after copy and paste any way and choosing INFO from the menu

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1327]
## Vespucci Version
15.1.4

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
If copying any WAY (not a single node), then paste it (insert) and choosing "Info" for this way, Vespucci crashes. It happens with closed and open ways. I suppose it only happens before uploading (?). I didn't test this ...

It does not happen with single nodes.

It does not happen if Vespucci is in locked mode (lock closed) and you do a long press on the pasted way, which also shows the info window.

## Expected Behaviour
It should not crash …

## How to recreate
obvious

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
no

**Comment by simonpoole** [comment]
Thanks for the report. The crash was due to the initial state not being quite the same for a way created via normal means vs C&P. Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/b324b2436fdcafd6ddfbad58b3e73f38dcbf4236

See also https://github.com/MarcusWolschon/osmeditor4android/issues/1328
