### ISSUE TITLE
Data stored in SD Card

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1341]
Description:
---

I noticed that my Vespucci 15.1.6.0 stores data here: SD Card/Android/data/de.blau.android.

This is undesirable, as I change SD Card often. Is this normal? Can I force it to use the internal storage? I can't find the relevant option in the settings. It's the only app I can't stop from doing this. 

In case it's relevant, Vespucci was sideloaded (extracted from an Android 4 tablet). Storage permission is enabled.

Device info:
---
<table>
<tr><td>App version</td><td>15.1.6.0</td></tr>
<tr><td>App version code</td><td>1609</td></tr>
<tr><td>Android build version</td><td>A515FXXU4CUA1</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.A515FXXU4CUA1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a51</td></tr>
<tr><td>Device model</td><td>SM-A515F</td></tr>
<tr><td>Device product name</td><td>a51nsxx</td></tr>
<tr><td>Device hardware name</td><td>exynos9611</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Tonushka"/>Tonushka</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Yes there is no setting for this.

Vespucci tries to create the tile cache on an actual SD card because it can become quite large. However there is a simple solution for your issue: remove the sd card, start up Vespucci. The app will then create the cache on the internal storage and continue to use it even when the SD card is present again (or at least it should).

See also http://vespucci.io/tutorials/faq/#vespucci-warning-that-it-cannot-write-to-an-external-sd-card

WRT to side loading: you can simply retrieve the current APK from https://github.com/MarcusWolschon/osmeditor4android/releases and install that.
