### ISSUE TITLE
Changelog on master is missing versions 15.1.7, 15.1.6, 15.1.5, 15.1.4, 15.1.3 and a typo in 15.1.0

### ISSUE THREAD

**Issue by agent-redd** [MarcusWolschon/osmeditor4android#1350]
## Missing changelog for several 15.1 versions

The current Changelog file misses the changelog for several 1.5.1 versions. 
But these are availble in the 15.1-MAINT branch. There was even one typo fixed in 15.1.0 which isn't fixed in master changelog. 

See the compare: https://github.com/MarcusWolschon/osmeditor4android/compare/master...15.1-MAINT

Is it okay to port the missing changelog from 15.1 to master?

Reason: Current version in F-Droid is 15.1.7 and the changelog isn't shown when clicking on the Changelog link: https://github.com/MarcusWolschon/osmeditor4android/blob/HEAD/CHANGELOG.txt

Edit: Update link to comparision

**Comment by simonpoole** [comment]
> 
> ## Missing changelog for several 15.1 versions
> 
> The current Changelog file misses the changelog for several 1.5.1 versions.
> But these are availble in the 15.1-MAINT branch. There was even one typo fixed in 15.1.0 which isn't fixed in master changelog.
> 
> See the compare: [master...15.1-MAINT](https://github.com/MarcusWolschon/osmeditor4android/compare/master...15.1-MAINT)
> 
> Is it okay to port the missing changelog from 15.1 to master?
> 
> Reason: Current version in F-Droid is 15.1.7 and the changelog isn't shown when clicking on the Changelog link: https://github.com/MarcusWolschon/osmeditor4android/blob/HEAD/CHANGELOG.txt
> 
> Edit: Update link to comparision

The thing is that while in some cases the commits are cherry picked from the master branch, that is not guaranteed and the master branch overall -does not- contain the same changes post branching of the -MAINT branch for the previous release. 

So for example in the case of 15.2.0 BETA 1 we have actually gone from 15.1.2 to the current state (you will notice that lots of the changes listed in the 15.1 change log post 15.1.2 are actually listed in the entry for 15.2.0 BETA 1).

But that isn't the problem really, the problem is the link in F-Droid. There are multiple ways I could imagine to fix it, but somebody that actually knows the F-Droid build system would have to comment (right now as auto update is broken, the link could simply be changed to the correct branch). @Bubu any suggestions?

**Comment by Bubu** [comment]
@simonpoole The link is there and can be changed at will: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/de.blau.android.yml#L7

(It'll take effect with the next app publishing cycle, so expect some delay in updating that.)

**Comment by agent-redd** [comment]
So maybe we should change that link in F-Droid Repo to 
https://github.com/MarcusWolschon/osmeditor4android/releases
Or is there any more suiteble link?

**Comment by agent-redd** [comment]
ok, the Pull Request on F-Droid was merged, I guess my Issue is therefore solved soon, i close this issue. Thanks everybody.
