### ISSUE TITLE
Can't add note to OSM as upload button hidden by keyboard;  both 'done' and collapse keyboard buttons invisible in portrait mode

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1426]
Description:
---

In portrait view the soft keyboard covers the upload button, in landscape view there is a done button to shove the keyboard out of the way, in portrait mode there isn't - at least it isn't visible.
While writing this feedback the collapse keyboard 'v' shape total left bottom is visible, but in 'non-simple-mode' that v isn't visible
Android 10, Motorola Moto g 5g .

Device info:
---
<table>
<tr><td>App version</td><td>15.2.3.0</td></tr>
<tr><td>App version code</td><td>1705</td></tr>
<tr><td>Android build version</td><td>9d905</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QZKS30.Q4-40-81-3-2</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>kiev</td></tr>
<tr><td>Device model</td><td>moto g 5G</td></tr>
<tr><td>Device product name</td><td>kiev_retaile</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/H4N5-antw"/>H4N5-antw</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Have you tried disabling full screen mode? Outside of that, a couple of screen shots illustrating the issue would be helpful.

**Comment by H4N5-antw** [comment]
Dear Simon, 

Thank you for the response. 

Had already replied to your message on OSM, herewith duplicate text to keep this thread complete : the suggestion to take a screenshot cured the issue, as the keyboard folded out of view, showing the Upload and other buttons. 

Nice touch : when one then clicks somewhere in the message to add text, the keyboard appears with the 'fold away' v-shape in the bottom left corner. 

Attached for photos of the smartphone, with caption as filename. 

![osm vespucci github 1 upload obscured lacking collapse keyboard](https://user-images.githubusercontent.com/88083615/127298378-ea45ac17-043b-4c95-84dc-37a054f6b090.jpg)

![osm vespucci github 2 landscape shows Done button](https://user-images.githubusercontent.com/88083615/127298380-26f8d07e-2511-41c2-b240-95c062985d5b.jpg)

![osm vespucci github 3 after three finger to take screenshot](https://user-images.githubusercontent.com/88083615/127298381-f55183f9-10c0-4b90-b617-769ecd74700d.jpg)

![osm vespucci github 4 continue to edit text shows collaps keyboard v-shape](https://user-images.githubusercontent.com/88083615/127298389-daeb297e-3a38-447e-929a-9caa3764c845.jpg)

Upshot is that workaround works, but might suggest moving the add note window to the upper half of the screen - while keyboard occupies lower half - would obviate need for this workaround?


= = = 

As mentioned in OSM message four days ago : are any photos taken uploaded to the internet, please? There is a disclaimer on the vespucci http://vespucci.io/ on Mapillary , might be that photos are sent there ; is would that be to the Vespucci account, or to mine? Taking photo didn't succeed : could it be because my OSM-login no longer works at Mapillary, and the passwords are different? 

Met vriendelijke groet (Dutch for 'with friendly greeting),

**Comment by simonpoole** [comment]
This is clearly an issue with your Android device or the keyboard app. Did you try turning full screen mode off as I suggested?

If that helps I'll add your device to the list of broken Android implementations, and full screen mode will be disabled, see  https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/assets/devices.json

**Comment by simonpoole** [comment]
> As mentioned in OSM message four days ago : are any photos taken uploaded to the internet, please? There is a disclaimer on the vespucci http://vespucci.io/ on Mapillary , might be that photos are sent there ; is would that be to the Vespucci account, or to mine? Taking photo didn't succeed : could it be because my OSM-login no longer works at Mapillary, and the passwords are different?

As I already answered in my reply to you:
>Currently Vespucci stores images in the Vespucci/Pictures directory, this will change to a new location due to Android 11 restrictions in the next (non-maintenance release).

With other words your photos are not uploaded. If the photo app you are using produces an error, you need to take a screen shot of that and open a new issue with details (photo app etc) and the screen shot of the error.

**Comment by H4N5-antw** [comment]
> This is clearly an issue with your Android device or the keyboard app. Did you try turning full screen mode off as I suggested?

Dear Simon, thank you for the question, had earlier turned full screen mode off in the Android Settings app, for all apps, as there is no need for that little extra bit of screen space in any of the apps. 

But you have a point, the top ruler is behind the info along the top. 

Vespucci would refer to the Full Screen setting in Android Settings, like all other apps? 

There is an option down in the Vespucci settings where full screen is set to 'auto' - not sure what to expect from that, would prefer 'use Android system settings'. 

Changing the Vespucci full screen setting from 'auto' to 'never' reveals the top ruler. 

If you were to ask my opinion : I'd prefer Vespucci following the Android setting, rather than expect the user to hunt down what seems a duplicate full screen setting but isn't, as it apparently overrides the Android one. 

Final thought : given that scores of other apps follow the Android Full Screen setting : is it really the phone which has a broken Android implementation, or would the 'auto' setting need to be refined? 

Met als immer vriendelijke groet,

**Comment by simonpoole** [comment]
There are "no" Android level full screen setting, just setting how the navigation bar should look like, which isn't the problem here. 

Full screen mode is not used by many apps that use a keyboard, so it is not a surprise when there are issues now and then (typically depending on the keyboard in use), matter of fact I don't believe I've seen any one outside of Vespucci. 

See also http://vespucci.io/tutorials/faq/#fullscreen-mode-doesnt-work-properly and http://vespucci.io/help/en/Advanced%20preferences/#user-interface-settings . Don't change anything at a system level, simply disable fullscreen mode in Vespucci and then test again.

**Comment by simonpoole** [comment]
Closing as stale.
