### ISSUE TITLE
Logging of sensitive information

### ISSUE THREAD

**Issue by bananabr** [MarcusWolschon/osmeditor4android#1457]
## Vespucci Version
15.2.8

## Download source
github

## Device (Manufacturer and Model)
n/a

## Android Version 
n/a

## Behaviour/Symptoms

Prior to Android 4.0, any application with READ_LOGS permission could obtain all the other applications' log output. After Android 4.1, the specification of READ_LOGS permission has been changed. Even applications with READ_LOGS permission cannot obtain log output from other applications.

However, by connecting an Android device to a PC, or when running a rooted device, log output from other applications can be obtained.

Therefore, it is important that applications do not send sensitive information to log output.

Once the issue is fixed, please create a security advisory to a CVE is assigned to it by GitHub.

## Expected Behaviour
No user sensitive information should be logged to the system log

## How to recreate
The following LGTM query results demonstrate user credentials being written to the system log: https://lgtm.com/query/6208604878570798994/

**Comment by simonpoole** [comment]
Anybody that has physical access to the device already has the granted access to the users account and doesn't need any information from the log to access it unless the authorization is withdrawn, which however in turns renders the information in the logs useless.

**Comment by bananabr** [comment]
Not in the case of a rooted device. But if you think the risk is negligible feel free to close the issue.

**Comment by bananabr** [comment]
There is also the case when another application is given the READ_LOGS permissions through ADB
```adb shell pm grant <pkg> android.permission.READ_LOGS```

**Comment by simonpoole** [comment]
In practice this requires physical access to the device too. 

You have a point in that there are scenarios in which a bad actor could kidnap a users device, extract credentials and give the device back unnoticed and then use them for nefarious purposes, but in this case the value of that is minimal because it simply would allow you to upload data to OSM in somebodies elses name, which is likely not going to go unnoticed (the only bit of personal data that is stored by OSM is the e-mail address, that however is not accessible via the API, so nothing to be gained there either). So the impact is minimal, but I'll change the offending code in any case as the information is literally only used for debugging.

**Comment by bananabr** [comment]
Sounds good to me @simonpoole.

Thank you.

**Comment by simonpoole** [comment]
Removed in https://github.com/MarcusWolschon/osmeditor4android/commit/73911f0bf29adc1a22634cf0e433e9592f8a1475
