### ISSUE TITLE
After installing Vespucci, make adding an existing OSM account friendlier

### ISSUE THREAD

**Issue by SomeoneElseOSM** [MarcusWolschon/osmeditor4android#1506]
When installing Vespucci for the first time on a new device, the first question that I asked myself was "how do I authenticate myself to OSM".

Unfortunately neither the on-device help nor even http://vespucci.io/help/en/Advanced%20preferences/#user-account much help with this.  It is in http://vespucci.io/tutorials/faq/#how-can-i-upload-newchanged-data-to-the-osm-server , but someone installing Vespucci likely doesn't know that that page exists.

It'd be great to have a way of authorising OAuth _before_ any changes have been made rather than waiting until a user has made some changes (which might get lost if there is a problem).

It'd be great if the on-device help for "User Account" http://vespucci.io/help/en/Advanced%20preferences/#user-account told the user how to authenticate themselves to OSM rather than just "you don't need to do that here".

The actual place is
Spanner menu (whatever that is called)
Authorise OAuth (which probably should be called something that more people will understand, perhaps "login to OpenStreetMap")

**Comment by simonpoole** [comment]
The introduction https://vespucci.io/help/en/Introduction/ has a section on "Saving Your Changes" that covers all of the above.

The "Spanner" menu is the "Tools" menu, that's the label used when it is displayed in the overflow menu (that's the Android name for the three dot menu). In general, this is an Android thing, the app has little to no control over what is exactly displayed with a button or overflowed to the overflow menu (this will change due to screen size, resolution etc).
