### ISSUE TITLE
Direction marking for traffic_signals has disappeared from the dialog

### ISSUE THREAD

**Issue by CRCulver** [MarcusWolschon/osmeditor4android#1533]
After upgrading to Vespucci 16.1.2.0, the direction=forward/backward toggle has disappeared from the dialog when adding a highway=traffic_signals. The tag editor no longer even autocompletes the tag name traffic_signals:direction. Why was support for this tag (extremely widely used, with over 317,269 nodes on OSM as I write this) removed?

**Comment by simonpoole** [comment]
Note that this is a preset issue and should have been reported in the preset repo (https://github.com/simonpoole/beautified-JOSM-preset).

The tag was accidentally removed during some changes to synchronize with the JOSM presets, no evil intent, nothing to argue about. The issue was fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/82f4a242cc6df4dc0406ece022f22100291ca5a2 You can switch to using the version of the preset distributed online until the next maintenance release if you want to, see http://vespucci.io/help/en/Presets/#managing-presets or the corresponding on-device help.
