### ISSUE TITLE
Blank map

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1543]
Description:
---

I can't see anything except the yellow bug symbols. I have downloaded the current view.

Device info:
---
<table>
<tr><td>App version</td><td>16.1.3.0</td></tr>
<tr><td>App version code</td><td>1905</td></tr>
<tr><td>Android build version</td><td>gms-12ee4a80</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>8901.3.A.0134.20211116</td></tr>
<tr><td>Device brand</td><td>Fairphone</td></tr>
<tr><td>Device manufacturer</td><td>Fairphone</td></tr>
<tr><td>Device name</td><td>FP3</td></tr>
<tr><td>Device model</td><td>FP3</td></tr>
<tr><td>Device product name</td><td>FP3</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/mcg1878"/>mcg1878</A></td></tr>
</table>

**Comment by simonpoole** [comment]
'Blank screen' checklist:

- preset or tag filter turned on, check the main 'overflow' menu (three dots)
- data layer disabled or hidden by other layer, check the layer dialog ('hamburger' menu in the upper right corner)
- API sandbox selected instead of normal API, check the configuration of the data layer in the layer dialog.

Did you have a different version installed before 16.1.3?

**Comment by simonpoole** [comment]
Stale. I added a FAQ http://vespucci.io/tutorials/faq/#ive-downloaded-data-but-the-screen-remains-blank as this tends to be a accidental misconfiguration.
