### ISSUE TITLE
"Go to current location" turns on location marker

### ISSUE THREAD

**Issue by joelamos** [MarcusWolschon/osmeditor4android#1588]
## Vespucci Version

17.0.5

## Download source

Google Play Store

## Device (Manufacturer and Model)
Google Pixel 6

## Android Version 

12

## Behaviour/Symptoms

When I press "Go to current location" with "Show location" toggled off, the map jumps to my location, displays the location marker, and does not toggle on the corresponding "Show location" checkbox.

## Expected Behaviour

The map jumps to my current location without displaying the location marker, as "Show location" is toggled off.

## How to recreate

Press "Go to current location" with "Show location" toggled off.

## Crash dump submitted (no or yes + date)

no

**Comment by jajajaneeneenee** [comment]
I experience a different behaviour since a long time: if I press "Go to current location" and "Show location" and "Follow Location" is **OFF** then NOTHING happens. I **always** have to switch on "Show location" first and then press "Go to current location" ... Then it always works and it jumps to the current location (if the phone has the correct location).

I already do this automatically .. and hoped that some day "Go to current location" will work better – I mean as expected – without having to switch on "Show location" first. Perhaps you can check this, too – if it can be improved. Perhaps it depends on the Android version or even the device??? I don't hope so and that you can fix it easily ...

My system: Android Version 9.1.0; Huawei Honor 7x; Vespucci 17.0.5 (Google Play Store)

**Comment by joelamos** [comment]
> if I press "Go to current location" and "Show location" and "Follow Location" is **OFF** then NOTHING happens
This is the bug I was intending to report (see original title) but then started to have trouble reproducing it and thought there had been a fix attempt, and so I pivoted.

I think I've figured out how it all works. The bug you're seeing is present only when the app has not yet made a location request to the Android API in the current session (You can tell when such a request is made because a location icon appears briefly in the notification tray.) Once the app has established location access, the behavior shifts to what I described above. Let me know if you can reproduce this. Hard closing the app resets the behavior.

**Comment by jajajaneeneenee** [comment]
Hello! Yes , I can reproduce it (although I have no location icon appearing somewhere). It works for some time without having to switch on "Show location" again. But normally (for me), I don't use the command in short time intervals, so the most common situation for me is that I have to switch on "Show location" first again – if the time interval for the last is too long, and the device (or the app) has lost the location again. (Indeed the device should have the GPS location permanently, because I normally do a track recording with another app – Locus Map Pro – in the background when I am outside for mapping ...)

And because you can never be sure if it still works (if "Show location" is OFF), the only 100% reliable method for me was to **always** switch on "Show location" first (and often waiting some seconds until the location is determined and the location arrow jumps away) ...

I also already thought that the problem could be, that the command "Go to current location" doesn't initiate a location request to the Android API at all (or it takes too long until it gets a response or until the location is determined? – something like that. I'm sure Simon Poole will know more ...).

By the way: I'm also surprised that it often takes so long for Vespucci to determine the location (often it's fast, but sometimes it also takes 10 or 20 seconds or does not work at all for some time), because - as mentioned above – I have a track recording running in the background and the GPS position is always active. And I don't see any dropouts later on in the recorded track either. 

Anyway – an improvement would be welcome ... perhaps also with a message, that it can take some time until the location is determined, if it is not immediately available for any reason?

**Comment by simonpoole** [comment]
The behaviour was a combination of two minor issues:

- goto current location turning on the marker without actually setting the preference that it should be turned on, however due to the aspect mentioned below, it is preferable to actually not do that,
- the goto current location doesn't turn on continous location updates (because battery) and tries to get the last reported location from the TrackerService (if present) or as fallback from the system location manager, however the former only works if the service received a location once. The fix ensures that the fall back to the location manger will always be used if no location can be obtained.

**Comment by joelamos** [comment]
Appreciate the work on this!
