### ISSUE TITLE
Add a way to override the UI language

### ISSUE THREAD

**Issue by Sorunome** [MarcusWolschon/osmeditor4android#1590]
Currently the UI language is auto-detected from the language set within android. While this is a great default, it would be awesome if there was a setting to override that to some other language.

**Comment by simonpoole** [comment]
You've been able to switch off translation since 16.1 http://vespucci.io/help/en/16.1.0%20Release%20notes/#preference-to-disable-user-interface-translation (via an ugly hack).

And it seems as if google will from Android 13 on actually support per app language selection after 15 years of refusing to suppprt it. So in 1-2 years you may see official suppprt.
