### ISSUE TITLE
Crashes on Amazon tablet 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1610]
Description:
---

Feedback requested by an app notification. This device is an Amazon HD10 which gives amazing bang-for-the buck; however it has a quirky version of Android. Vespucci routinely crashes. Crashes are frequent when switching aerial imagery sources. When this happens V. loses track of the displayed location, and loses update "history". It would be nice if this didn't happen. Recent V. updates have shown great improvements in this area, but the problem hasn't been completely resolved.

Best Rgds, -H-

Device info:
---
<table>
<tr><td>App version</td><td>17.0.5.0</td></tr>
<tr><td>App version code</td><td>2008</td></tr>
<tr><td>Android build version</td><td>0022247240580</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PS7322</td></tr>
<tr><td>Device brand</td><td>Amazon</td></tr>
<tr><td>Device manufacturer</td><td>Amazon</td></tr>
<tr><td>Device name</td><td>maverick</td></tr>
<tr><td>Device model</td><td>KFMAWI</td></tr>
<tr><td>Device product name</td><td>maverick</td></tr>
<tr><td>Device hardware name</td><td>mt8183</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/HMWamboldt"/>HMWamboldt</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Hi, you don't seem to have to submitted a crash dump (this should be from the crash after using the imagery chooser), by its nature this is likely nearly impossible to debug without one. 

We actually test pre-release on an old Amazon tablet and I just tried the imagery chooser on it and couldn't find any specific issues on the device. 

Are you installing the app from the Amazon app store?

**Comment by H--W** [comment]
Apologies. Vespucci was installed through the Google Play Store. I didn't know it was available on Amazon. Since this report was device initiated I assumed some sort of dump would be included. I didn't see any widgets for including the dump, or, perhaps I have to enable dumps? I'm not familiar with Android debugging (yet :). I've been meaning to read about crash dump debugging on Android Developer but haven't gotten around to it. My history has been mostly embedded C. These crashes happen somewhat regularly on the HD10. I switch aerial imagery, it crashes and restarts. Not always 'tho, and the last few versions have had less frequent crashes. I'd be happy to attach a dump, if you could provide a pointer to the relevant documentation. Also, dumps can be ridiculously large, can I assume you're only interested in the stack and logs? Not text, data, bss, or whatever? Assuming the latest version is available on Amazon I'm also happy to switch. Best Rgds, -H-

**Comment by simonpoole** [comment]
We use https://github.com/ACRA/acra for generating crash reports, while there is an option to suppress generating them, it is be default on, because you will be asked if you want to submit the report on a case by case base in any case, see


![Screenshot_1648717959](https://user-images.githubusercontent.com/1011860/161020980-f3033cf3-760f-462d-b1dd-e7f987503c8a.png)

That you don't see the form asking you to submit something indicates that it isn't a simple application crash, which makes things complicated.

The probably easiest way to see what is going on is to view the system log while the crash is happening. You will need to install adb https://developer.android.com/studio/command-line/adb , connect your device via USB and then use the https://developer.android.com/studio/command-line/logcat command to view the log. Alternatively you can install android studio and use its log viewing (which uses the same mechanism).

**Comment by simonpoole** [comment]
Any progress?

**Comment by H--W** [comment]
Sorry, I've been busy with other projects. Is it OK to just leave this open for a while? I'll try to find time to dig out more diagnostic information but on my end this is on slow burn. It isn't a blocker but if others are having this problem I can up the priority. Best Rgds, -H--- HMWamboldtOn 2022-04-11, 11:00 AM Simon Poole ***@***.***> wrote:

   
  Any progress?

**Comment by simonpoole** [comment]
>  Sorry, I've been busy with other projects. Is it OK to just leave this open for a while?

No problem.

**Comment by simonpoole** [comment]
Very stale.
