### ISSUE TITLE
Notify me if I haven't uploaded in a day.

### ISSUE THREAD

**Issue by amandasaurus** [MarcusWolschon/osmeditor4android#1611]
Upon opening vespucci, I saw that I had not-uploaded changes. I had done some editing about a week ago (also “on the go”), and had not uploaded yet. I [uploaded](https://www.openstreetmap.org/changeset/119230763) & mapped.

I suggest that Vespucci notify me if I have non-uploaded changes. For example, it could do it the next day. This prevents people from forgetting to upload, and prevents teaching users from making lots of changesets (by uploading often to avoid that)

**Comment by simonpoole** [comment]
What you want is something that reminds you without starting the app, aka not the app itself, this might be possible on device but needs investigation.

**Comment by jajajaneeneenee** [comment]
I can also confirm that I know this “problem” ... But I use Vespucci almost every day ... so it's normally not such a big problem. I my case, the green ”counter“ number on the download/upload icon is already a good reminder.

A thought: 
Perhaps it would already be an improvement (without the need of a solution when the app is not running ...) if it could fire a reminder if it IS still running in an "idle" state (no new mappings or other interactions of the user  took place since I would say 1 or 2 hours) AND there are not-uploaded changes ... This would perhaps cover the typical situation that you simply forgot to upload some changes ... (Ideally, of course, with a configurable setting, after which time of “no action” or if such a reminder should take place at all.) I am not sure, but perhaps on most devices the app will go on running for some time after the last interaction until it is "killed" by the system to give some memory free or whatever ... and this simpler solution could work for most cases (if this is correct).

My typical situation is that I came home, a few mappings recently made before, and I'm so hungry that I have to prepare something to eat immediately, and have to play with the cat and so on ... And forgot Vespucci and the uploads completely until I open it again until the next day or 2 days later ... A reminder after 1 hour would have helped, perhaps ...

And of course it should “fire” this reminder (or a pop-up reminder in this case) if the app was closed and opened again and there are not-uploaded changes (which are older than 1 hour for example) ... It could be a text like “Do not forget to upload your edits (last edit: 2022-04-17 16:20:24)!“
 
At the moment, I only see the green number on the download/upload icon, which is already a good reminder for me if I open the app again, but an explicit reminder would even be better ...
