### ISSUE TITLE
AntiFeatures on F-Droid a FYI

### ISSUE THREAD

**Issue by licaon-kter** [MarcusWolschon/osmeditor4android#1642]
Ref: https://gitlab.com/fdroid/fdroiddata/-/commit/4ff783186b5cd282f8f4ee25886e969be9fedfbc#49fd777b5e286fa060feabc311254c1af436568e

Ref: https://gitlab.com/fdroid/fdroiddata/-/commit/b432dcd63032e48ce41d937f48cbe63f9beb06bb

Ref: https://gitlab.com/fdroid/fdroiddata/-/issues/2685

These AFs are not there to punish the devs, but to inform the user.

It's understandable to use some server for some functions, it's more a matter of using the services of known bad actors that might use/send the user info elsewhere in a way that the app user never consented to in the first place. 

Both AFs can be removed by a "simple" opt-in dialogue on start _(and a Setting if they change their mind later)_ that explains the what/where/why and allows to user to choose to be able to use those features or not _(this applies to both "use server to get mapdata" and "send crash report")_

**Comment by simonpoole** [comment]
There is no and never has been any automatic connection to the services in question (small exception wrt Bing see below), matter of fact with exception of Bing they have always been completely disabled for third party builds to start with. 

Bing imagery use has a small technical quirk in that to be able to switch to the source you have to fetch a small amount of metadata from their API beforehand, as this is very slow it happens async without user interaction, but that is disabled now in 3rd party builds with the removal of the Bing API key. 

Wrt crash dumps there is an overall preference that turns them on or completely off, default is on. Nonetheless prior to every submission the user has always been asked if they want send the specific dump.

I'm not sure what you are referring too with "use server to get mapdata".

**Comment by licaon-kter** [comment]
This is what I see on launch, I don't change any setting, I press "Wait" for those 3-4 ANRs that keep popping out, and these are even before the "Welcome" dialogue appears.

![vespucci](https://user-images.githubusercontent.com/2282799/170661194-1380b440-0a56-4860-86a6-1f29f2c7deff.jpg)

> but that is disabled now in 3rd party builds with the removal of the Bing API key.

"now" means already released or future version?

> Nonetheless prior to every submission the user has always been asked if they want to send the specific dump 

This is not mentioned here: https://github.com/MarcusWolschon/osmeditor4android/blob/master/documentation/docs/help/en/Advanced%20preferences.md#report-app-crashes hence I added the AF

**Comment by simonpoole** [comment]
On a new install or upgrade the imagery configuration is reread (from the APK assets, which can take a bit of time and even though it is not running on the UI thread tends to tickle ANRs on some devices) and then the on device database updated. The standard configuration uses the configuration from https://github.com/osmlab/editor-layer-index.

Most of the layers have the icons as encoded binary in the configuration, however https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/sources/world/OpenStreetMap-Mapnik.geojson which is the default background layer, for whatever reason uses an icon that is in the ELI repo which is what you are seeing. IMHO this needs to be fixed upstream, but not a real problem to get that done.

Bing is simply used for its global orthoimagery mosaic and it is just one of many such layers, it is only special because of the metadata that needs to be retrieved before use.

The Bing key is removed in 17.1 which is likely to be tagged this weekend or early next week.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/b374c83097fd8cae95e1c400f856bd04bb9b7fd9 fixes the issue with the OSM icon being fetched from the ELI repo on github. It only does so for the Vespucci base imagery configuration, not for ELI itself, see https://github.com/osmlab/editor-layer-index/issues/1521

**Comment by licaon-kter** [comment]
Are we lost in translation? 

`Starting with this version this is no longer the case as allowing access to a wide range of sources is considered an anti-feature by the operators of F-Droid / It should be noted that the other claims by F-Droid in this context are incorrect, neither Mapillary support or Github access has ever been available in 3rd-party builds of Vespucci.`

This is just FUD. There's a picture above from the firewall that proves the app literally connected to these servers. :confused: 

Having Bing as a data source is one thing, and F-Droid has no issue with this.

What it has issues with, and tries to convey this before one can install the app, via an AF, is that the user gets no choice to select this data source and the app connects on first start to these proprietary services none the less.

That being said 17.1.1.0 is live on F-Droid and still (tries to) connects to `www.bing.com:443` on first start.

![vesp](https://user-images.githubusercontent.com/2282799/173853208-c88c6687-f1cb-4c12-b264-8586e7d8bbe9.jpeg)

_Anyone can install https://f-droid.org/en/packages/eu.faircode.netguard to verify._

So [the readme](https://github.com/MarcusWolschon/osmeditor4android/blob/c00613758541b94a4d1cfad1de9e305abd733b89/documentation/docs/help/en/17.1.0%20Release%20notes.md#bing-imagery-no-longer-available-for-3rd-party-builds) is false on three accounts. :man_shrugging:

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11291

**Comment by EvanCarroll** [comment]
As a side note, Vespucci is supported if you're an f-droid user.

* https://f-droid.org/en/packages/de.blau.android/

**Comment by opk12** [comment]
@simonpoole Just a heads up / post-mortem that the wording on the website was fixed shortly after, as a consequence of this issue ([ticket at F-droid](https://gitlab.com/fdroid/fdroid-website/-/issues/646)).
* The AntiFeature docs article was clarified ([commit](https://gitlab.com/fdroid/fdroid-website/-/commit/4280dc6ba7b8fbb019190e054b90588030790805), [before](https://web.archive.org/web/20220405012413/f-droid.org/en/docs/Anti-Features/#NonFreeNet), [after](https://web.archive.org/web/20220706111333/https://f-droid.org/en/docs/Anti-Features/#NonFreeNet)) to match what was already publicly said elsewhere (but not really accessible to the casual user), that the issue is user choice, in the form of: irreplaceable dependency, default behavior.
* The F-droid page of any NonFreeNet app now says `promotes or depends entirely on a non-free service` not just `promotes` as before. As said in the linked ticket, this is not about bad-mouthing, and as a personal experience as a heavy F-droid user, F-droid is one of the few serious software distributors out there. [before](https://web.archive.org/web/20220324131136/https://f-droid.org/en/packages/net.osmand.plus/), [after](https://web.archive.org/web/20220914121154/https://f-droid.org/en/packages/net.osmand.plus/)
