### ISSUE TITLE
Tags being over-written without selection of a preset

### ISSUE THREAD

**Issue by davidpnewton** [MarcusWolschon/osmeditor4android#1644]
It appears that the alternative tagging update is producing undesirable behaviour: tags are being removed without user interaction. Specifically it is now impossible to have man_made=utility_pole and power=pole on the same without Vespucci automatically removing one or other tag. This happens with or without selection of a preset occurring. Manually inputting the tagging man_made=utility_pole results in removal of power=pole and vice-versa.

Vespucci should not be altering tagging without either manual input of that tagging or selection of a preset. The utility pole and power tagging are not mutually exclusive and therefore can and have co-existed on the same node previously.

## Vespucci Version
17.1.0.1 beta

## Download source
Google Play

**Comment by simonpoole** [comment]
It would seem to be unlikely that this is due to the change in how alternative tagging is displayed, as the underlying mechanism has been present for a number of releases now, you just needed to manually display them. I'll have a look at what might causing this (could be a preset change).

**Comment by davidpnewton** [comment]
What, if anything do you need from me?

**Comment by simonpoole** [comment]
OK, I can reproduce this. The reason for the behaviour is that when auto applying the preset we use a generic mechanism which is also used when applying alternatives. In the later case we need to remove such tags as otherwise the concept doesn't make any sense.

I'm working on a fix that will only activate the code when actually applying the alternative and not always.
