### ISSUE TITLE
DataStyling – the new offset value also seems to shift the labels

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1663]
I've been playing around with your example sidewalk styling for `highway=residential` ways ... with the new offset attribute of Vespucci v17.1 (very nice!!!).

I noticed that the street name is centered to the casing outline with the offset value – the offset value also seems to shift the label. To demonstrate what I mean, here I changed the widthFactor in the code

`<feature type="residential_sidewalk_right_casing" updateWidth="true" widthFactor="0.7" color="FFFF0000" style="STROKE" cap="BUTT" join="MITER" offset="0.50"/>`

from 0.7 to 10:

`<feature type="residential_sidewalk_right_casing" updateWidth="true" widthFactor="10" color="FFFF0000" style="STROKE" cap="BUTT" join="MITER" offset="0.50"/>`

And 

And the result of a `highway=residential` line with `sidewalk=both` and one with `sidewalk=right` (and `name=residential`) looks like this:

![Screenshot](https://user-images.githubusercontent.com/48966999/174190903-29d9a79a-9528-4653-b741-5e02b93cf143.png)

I'm not sure if it's intentional and it's no big deal, just wanted to report it. (I would prefer to have the name centered on the highway line.)

**Comment by simonpoole** [comment]
This is clearly a defect, thanks for the report. The problem is that the array containing the way coordinates is modified this isn't a problem for the drawing of the actual way as the path object is created before the offset happens, but for highway labels that happens after. There isn't likely a good solution for this, except to copy the array contents before offsetting which naturally has a bit of a performance impact.
