### ISSUE TITLE
Add title to disambiguation menu

### ISSUE THREAD

**Issue by lennartppp** [MarcusWolschon/osmeditor4android#1716]
I have come across a road which appears to have a name if you click on it, but where the "Name" tag is blank in the attribute editor (see attached screen shot). I selected the road in Vespucci by "Go too coordinates" 59.54874,17.00276.

This is probably caused by an adjacent object which has a name "spilling over". Another telltale sign that something is strange,  is that I can't invoke the tag editor at this point,   I have to move away from the named object. 

The work- round for this is to click on the text "Minor road", this brings up the tag editor. 

Please document this in a suitable way, so beginners can find it.

![Screenshot_20220806-104321_Vespucci](https://user-images.githubusercontent.com/35870304/183241973-7999a309-d008-4b34-93cc-63bc9bf332ef.jpg)
![Screenshot_20220806-103832_Vespucci](https://user-images.githubusercontent.com/35870304/183241988-cf068078-82b5-4011-b914-1a56d571293d.jpg)

**Comment by simonpoole** [comment]
Starting with version 14 (back in 2019) the best matching preset is automatically applied, see http://vespucci.io/help/en/14.0.0%20Release%20notes/#automatically-apply-preset-when-property-editor-is-invoked So having the empty Name field displayed in the property editor is intentional.

I don't quite understand your issue with selecting the road though, the disambiguation menu is exactly there for handling the case were multiple elements are very close to each other. In this case the farmyard and the road are sharing nodes for the relevant stretch so the geometry is actually the same (that that is not considered best practice is a different topic) and the editor has know way of automatically knowing which element you wanted to select.

**Comment by lennartppp** [comment]
The issue is that newbie/occasional/inexperienced users of Vespucci, like
myself, may mistake the disambiguation menu for a read- only window
displaying properties of exactly one object, in my case,  a road. Once I
had gotten the road into the property editor,  the properties appeared to
be different, which made me doubt that I had selected the "right" road.

Maybe a caption like 'please select one of the following/above' could
clarify things for users such as I?
