### ISSUE TITLE
Tile layer X is erroring message is unhelpful

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1731]
Description:
---

What URL was sent to the tile server?
What error came back?

Device info:
---
<table>
<tr><td>App version</td><td>17.1.6.0</td></tr>
<tr><td>App version code</td><td>2107</td></tr>
<tr><td>Android build version</td><td>00WW_4_15O</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>00WW_4_15O</td></tr>
<tr><td>Device brand</td><td>Nokia</td></tr>
<tr><td>Device manufacturer</td><td>HMD Global</td></tr>
<tr><td>Device name</td><td>PL2_sprout</td></tr>
<tr><td>Device model</td><td>Nokia 6.1</td></tr>
<tr><td>Device product name</td><td>Plate2_00WW</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/SomeoneElse"/>SomeoneElse</A></td></tr>
</table>

**Comment by simonpoole** [comment]
This message is not intended to be more than a hint. The problem with providing details is that there is typically a deluge (aka 100s at the drop of a hat) of errors if something is going wrong fetching a tile (JS frameworks etc typically simply ignore them completely for this reason). Currently the toast is shown once after the count has reached 50 errors and is then muted till the next restart or similar (the layer info modal shows the actual error count).  

In version 16 I moved the tile processing to the main process http://vespucci.io/help/en/16.0.0%20Release%20notes/#tile-download-moved-to-main-process which in principle could make it easier to report a bit more detail, but it needs some thinking about what actually useful info could be.

**Comment by zyphlar** [comment]
I basically never need this notification (or 99% of other notifications) -- there's nothing for me to do about it, if it's truly egregious then maybe it could display a default "No Imagery" tile but generally I get this when I'm super zoomed in and there's no zoom=20 imagery etc. So in that case it belongs in a debug log and not much else.

The vast majority of notifications do nothing for me besides hide the one menu item I'm trying to click on. The one notification I do benefit from is seeing if a place has an address without editing it, but even that could be rendered on the map itself instead of as a pop-up. Generally, popups are a bad UI design unless they truly do need to interrupt the user.
