### ISSUE TITLE
The imagery source 'None' is erroring

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1826]
> The imagery source 'None' is erroring

How to reproduce:
1. Set imagery to None.
2. Go into Airplane Mode.
3. Reboot phone.
4. Launch app.

**Comment by simonpoole** [comment]
This is simply caused by the tile downloading thread checking for network connectivity, which it does (sensibly) before trying to download any tiles. The "None" configuration doesn't have a valid url so it wouldn't be able to download anything but it can't know that at that point. If you simply don't want a background, remove the layer (the None entry dates back to the time before that was possible).
