### ISSUE TITLE
Bing does not work since Android 12

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1910]
Description:
---

Sometimes it works, but most of the time not. Found no way to fix it. Other background imagery like Esri: no problem.

Device info:
---
<table>
<tr><td>App version</td><td>18.0.3.0</td></tr>
<tr><td>App version code</td><td>2204</td></tr>
<tr><td>Android build version</td><td>A336BXXU4AVI4</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.A336BXXU4AVI4</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a33x</td></tr>
<tr><td>Device model</td><td>SM-A336B</td></tr>
<tr><td>Device product name</td><td>a33xnseea</td></tr>
<tr><td>Device hardware name</td><td>s5e8825</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/goodidea"/>goodidea</A></td></tr>
</table>

**Comment by simonpoole** [comment]
There is nothing in the Bing specific code that is Android version dependent so it is more likely to be a coincidence that the upgrade and the issues seemed to be related. Does flushing the tile cache (layer dialog, overflow menu) make a difference? Where are you roughly located?

**Comment by jajajaneeneenee** [comment]
No, this does not help. Tried it several times.

Sometimea rebooting the phone did help, but the last few days, it did not help.

The layer info shows 0 errors (on another phone with Android 9 and Vespucci 18.0.3, where Bing is working fine, it shows 292 errors...), but after some time (when choosing "Info" again) there is a completely empty info popup (only with "DONE" as a button).

![20221028_134531](https://user-images.githubusercontent.com/48966999/198579933-1abe2167-3df6-4625-89bd-b0bcdafb59e6.jpg)

**Comment by simonpoole** [comment]
> The layer info shows 0 errors (on another phone with Android 9 and Vespucci 18.0.3, where Bing is working fine, it shows 292 errors...), but after some time (when choosing "Info" again) there is a completely empty info popup (only with "DONE" as a button).

This is indicative of the app not being able to retrieve the necessary metadata from Bing (this is where Bing differs from other imagery sources), it wont try to retrieve tiles before the metadata is available. As we only try to retrieve the metadata once on app startup if you don't have any network connectivity or something else creates and issue then it will fail. In any case there is no differences in that code wrt Android versions, so I would suspect either you are using the device differently or an ad clocker or similar is getting in the way.

**Comment by simonpoole** [comment]
Testing on an Android 12 emulator there seems to be some issues retrieving the meta data that I'm investigating.

**Comment by simonpoole** [comment]
Doesn't seem to be Android version dependent, it is simply a question of if the Bing layer is already configured on startup.

**Comment by Discostu36** [comment]
I now have the problem described on Android 11. Can I fix this locally somehow or do I need to wait for the update?

**Comment by simonpoole** [comment]
It could be marginally better if you switch to a different layer before exiting the app (and therefore not starting with Bing enabled).

**Comment by jajajaneeneenee** [comment]
Today, I could make Bing work with Vespucci v18.0.3 if first switching off the visibility of the Bing layer, exiting the app and restarting, then switching on the Bing layer. But in the past, this did not work, even removing the layer completely (and exiting the app/restart it/adding the layer again) did not work. 

But I just could install v18.0.5 from the Google PlayStore – and Bing seems to work also without the “workaround“ – great!!! It's really important for mapping ...

One question: is it Google dependant when a new Vespucci version is available in the PlayStore? 18.0.5  is available today since some hours I think (after 4 days), I remember that after the release of 18.0.3 it took only 1 day. And it would be nice if the version number would be shown in the Google PlayStore.

**Comment by simonpoole** [comment]
> One question: is it Google dependant when a new Vespucci version is available in the PlayStore? 18.0.5 is available today since some hours I think (after 4 days), I remember that after the release of 18.0.3 it took only 1 day. And it would be nice if the version number would be shown in the Google PlayStore.

There is no automatism in a release turning up on google at all. In general I need to build a release APK, then make it available to Marcus who will, time permitting, sign it and upload it to his google play store account. At every step there might be delays that could amount to weeks (for example we just spent 3 days because AGP 4.2 has a bug that doesn't allow the generated APK to be uploaded to the play store).

**Comment by rrodrigueznt** [comment]
@jajajaneeneenee I think you can read version number in Google PlayStore by clicking on **What's new** and going down until you reach the **App Info** section.
