### ISSUE TITLE
Missing Bing

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#1916]
Description:
In version 18.0.4, there is no Bing among the background image sources

Device info:
---
<table>
<tr><td>App version</td><td>18.0.4.0</td></tr>
<tr><td>App version code</td><td>2205</td></tr>
<tr><td>Android build version</td><td>V13.0.12.0.SKFMIXM</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SKQ1.210908.001 test-keys</td></tr>
<tr><td>Device brand</td><td>Redmi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>sweet</td></tr>
<tr><td>Device model</td><td>M2101K6G</td></tr>
<tr><td>Device product name</td><td>sweet_global</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
From where did you get the app?

**Comment by mic140** [comment]
> 

F-droid

**Comment by simonpoole** [comment]
The Bing layer hasn't been available in builds from F-Droid since 17.1.

See http://vespucci.io/help/en/17.1.0%20Release%20notes/#bing-imagery-no-longer-available-for-3rd-party-builds you would need to take the issue up with F-Droid (they would need to add an mechanism to provide non-public keys, there's not really a chance of that happening) or get your own Bing key and install it as described. This is no different than any other layer or service that requires an API key.

**Comment by mic140** [comment]
I would like to see this version in the Playmarket, because only in it it is possible to open files like Mbtiles

**Comment by simonpoole** [comment]
The next maintenance release will have all the Android 12 problem workarounds and will be released on the play store, as things look right now, this may be available in early November.
