### ISSUE TITLE
Perhaps the two GPS buttons could be combined

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1954]
Perhaps the GPS button on the left, could be removed, and its functionality simply replaced by a **long press** on the GPS button on the bottom.
![Screenshot_20221126-163401.jpg](https://user-images.githubusercontent.com/1230959/204111462-5536f42a-21f2-4f58-82ef-5e811dd64624.jpg)

**Comment by simonpoole** [comment]
Given that the button can be removed in the preferences and you can use the menu entry in any case I'm not sure what the utility of doing this is supposed to be, particularly since overloading buttons with long press leads to functionality that is not discoverable (and therefore should be avoided when possible).
