### ISSUE TITLE
The volume keys zoom the map

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1992]
And [there is no preference](https://vespucci.io/help/en/Advanced%20preferences/) to stop such behavior, if it makes the user uncomfortable. There are still the plus and minus keys perfectly usable.

**Comment by simonpoole** [comment]
The use of the volume keys for zooming has been a documented feature of the app since 2009, you are literally the 1st and only person to even mention it.

**Comment by jidanni** [comment]
All I know is I needed to turn down the volume on my phone, and lo and behold somebody had hijacked my volume key.

Google Maps doesn't even give the user a way to **opt in** to such behavior.

**Comment by yaomtc** [comment]
I've never seen any app hijack the volume rocker like this. Its default function in any and all apps should be volume controls. This should be an optional feature, but either way it definitely shouldn't be impossible to disable it. I've never seen a smartphone without a multi-touch display; I know they existed but a feature seemingly intended for those ancient devices should not be set in stone for all, when everyone has used pinch to zoom for years. 

I'll take a look at the code later and see if I can help.

**Comment by HolgerJeromin** [comment]
> I've never seen any app hijack the volume rocker like this

Please try the buttons in your camera app :)

**Comment by yaomtc** [comment]
Fair point. However, here's both of my camera apps, Google Camera: https://cubeupload.com/im/yaomtc/shLeDR.png

and Open Camera: https://cubeupload.com/im/yaomtc/2MZCbN.png

**Comment by simonpoole** [comment]
I"m not quite sure what the discussion is really about,  I haven't refused to add a preference or anything similar. 

I simply noted that the issue creators outrage over the way things are hasn't been shared by anybody else over the last 15 years (essentially as long as Android exists). So now there are two.

**Comment by yaomtc** [comment]
What the discussion is really about: I posted because I wanted to share my opinion on the issue, and because after about a year I wanted to mention it's still present/relevant, and I wanted to show that it's not just one person who thinks this should be a preference. 

Vespucci being 15 years old explains why it usually doesn't look or work like most other Android apps... because it came from the early days of Android before modern app design conventions were set, so in many ways it's unconventional. Given the niche use-case it fills (advanced editing of OpenStreetMap for power users) and that nobody is paying you, I understand making changes to long-standing design decisions is low priority.

So in the MapKeyListener section of Main.java, there would need to be a conditional to check `prefs` for something like `volumeIsZoom`, right?

**Comment by simonpoole** [comment]
> Vespucci being 15 years old explains why it usually doesn't look or work like most other Android apps...

It doesn't look or work like most other Android apps.. because it doesn't do what the nth iteration of a social meda/fake newspaper/media player app does. There is literally one other app out of millions that is similar.

**Comment by yaomtc** [comment]
alright nevermind
