### ISSUE TITLE
current location should be last known GPX point if currently tracking

### ISSUE THREAD

**Issue by johndh** [MarcusWolschon/osmeditor4android#2015]
The main way I use this app is for adding new ways and addresses that have just finished construction and don't appear on any satellite imagery, and I often find that my location will bounce around even when my GPX track stays accurate, so I have to scroll around to find the end of the track to find exactly where I am on the map.

**Comment by simonpoole** [comment]
This sounds like if you have "fallback to network location" enabled (see http://vespucci.io/help/en/Advanced%20preferences/#fallback-to-network-location and http://vespucci.io/help/en/10.2.0%20Release%20notes/#support-for-network-location-providers) and your device is not set to just use GPS (what corresponding Android setting is differs from Android version to version).

Location data derived from network sources wont be used for GPX tracks but will be used for centering the map and similar. Naturally even if you are only using GPS derived locations your position will move around a bit when you are stationary, but it will be a lot less than with the "network locations".

**Comment by johndh** [comment]
I guess this might be a misguided question, but if my GPX tracing is running, then the app knows precisely where I am, but it's using less precise data to position my point on the map? Shouldn't it use the more precise data that it's simultaneously already using?

**Comment by simonpoole** [comment]
The question isn't misguided, we check the age of the last fix derived from GPS and if that is stale fallback to the network position. In theory this works OK, except that when and how location updates are delivered to the app by Android is a bit hit and miss. 

You can try tuning http://vespucci.io/help/en/Advanced%20preferences/#minimum-gpsgnss-interval and the distance value to see if it helps, but as said Android doesn't necessarily honor the values (because of the power impact using GPS has). You might even try to switch to internal NMEA input.

**Comment by simonpoole** [comment]
@johndh Has this been resolved?

**Comment by johndh** [comment]
That seems to have fixed it. I guess the "fallback to network location" is counterintuitive, as it sounds to me like it would only come into effect if GPS were unavailable; or is it that the GPS is going stale and that's why? If the latter, should GPS be going stale while the tracking is happening?
