### ISSUE TITLE
Will need additional choice to prop up menu

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2050]
Here we only see choices yes and no, to the left of the lengthy menu item.

![Screenshot_20230123-054754_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/213942355-093fce35-ef80-4cba-8bcc-15978aded288.jpg)

Alas, the only way to make the box taller to see the full sentence, would be to add an additional third choice on the right.

Seen in portrait mode, with standard font sizes, and standard screen zoom.

Full sentence requires user  to turn on landscape mode to see.

We also notice lowercase no and uppercase yes, twice.

**Comment by simonpoole** [comment]
The key label is currently (hard) limited to 3 lines (so adding choices wouldn't make a difference). The argument is that (even with font size set to the max) more lines is excessive and that the text should be modified to be shortened, with other words it is a preset issue. 

The same goes for the lower case "no" this is displayed lower case because it isn't one of the standard values for the tag and you previously manually added it.
