### ISSUE TITLE
ESRI satellite images are not useful on high zoom levels

### ISSUE THREAD

**Issue by brbar** [MarcusWolschon/osmeditor4android#2126]
Unable to use ESRI imagery on high zoom. It shows error "map data not yet available".

However josm is able to show esri imagery on such zoom levels.

**Comment by simonpoole** [comment]
This is an upstream error in the ELI configuration the entry is missing data for no tile and/or error tiles, you should open an issue there: https://github.com/osmlab/editor-layer-index

If the ESRI layer is important to you, you can simply load the JOSM imagery configuration (it has it own issues, but different ones): https://vespucci.io/help/en/Main%20map%20display/#tools

**Comment by brbar** [comment]
I tried to add JOSM ESRI imagery by taping "Add custom imagery..." and inserting this URL:
tms[22]:https://{switch:services,server}.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/{zoom}/{y}/{x}
But it does not work.
What I'm doing wrong?

**Comment by simonpoole** [comment]
> What I'm doing wrong?

The _tms[22]:_ is a JOSM artifact and not part of the actual URL, However adding the layer it via the UI will not work better than the already existing configuration as there is no way to add the information that is missing in ELI via the UI. You can however simply add an entry by putting it in a file (ELI format) in the Vespucci directory named _imagery.geojson_ and in this case you can add the missing fields.

Naturally doing that instead of fixing it in ELI only fixes the issue for you instead of everybody.
