### ISSUE TITLE
Vespucci for use in rural areas with no mobile internet coverage

### ISSUE THREAD

**Issue by duiveldoder** [MarcusWolschon/osmeditor4android#2183]
I'm mapping quite a lot in rural areas where the mobile network is covered very poorly or not at all.

I'm switching between Vespucci, GPS Logger and OSMAnd while mapping, back and forth between them.

The problem is - if the coverage drops and I switch back to Vespucci - the satellite imagery is gone!

Although I downloaded/cached it before, it's simply gone and all I see is a yellow background.

Can you please allow mappers in rural areas to be able to use Vespucci also without live data connection?

i.e. don't flush the cache instantly but let us set a timer like 30 days, 90 days, 180 days.

or allow us something like on OSMAnd where we can use Mobile Atlas Creator to create our own offline tiles for background images so we can map also in rural areas using Vespucci.

Thank you

**Comment by simonpoole** [comment]
Hi, sorry, but literally everything you are asking for is already the case :-).

The only question is why the on device imagery cache isn't working for you. The only "normal" explanation is that you have a very small cache limit set, see http://vespucci.io/help/en/Advanced%20preferences/#tile-cache-size Otherwise either the app can't write to the preferred location or the SQLite cache file is corrupted, things to look at http://vespucci.io/tutorials/faq/#on-startup-vespucci-complains-that-it-cant-write-to-a-directory-or-reports-an-error  

For more information see 
- http://vespucci.io/tutorials/custom_imagery_mbtiles/
- http://vespucci.io/tutorials/offline/

**Comment by duiveldoder** [comment]
Thank you SImonpoole, I'll go for the custom mbtiles .. that way I'm in control of the background and don't mind the caching anymore.

Thank you for pointing out this solution.

**Comment by afgb1977** [comment]
Hello.
I want to confirm the error. My case is definitely the same as the one described in the initial entry of this ticket.
I use Vespucci on a Nokia G50 running Android 13.
I usually map with internet connection and see that the image cache has been created successfully.
When I turned off the data or Wi-Fi connection or activated the airplane mode of my Smartphone I can still see the images that are cached, the problem is that if I close Vespucci and open it again there are no images, I only see a light yellow or cream colored background.
If the cache has been created correctly, this problem should not exist unless Vespucci is conditioning to show the images as soon as it detects that the Smartphone is connected to the Internet or maybe it's a data access restriction issue in Android-Data-... imposed by Android 13.
You could do the test yourself and activate "Airplane Mode", close Vespucci and open it again and check if the images are actually displayed or not.
Annex screenshot, from left to right=
1. Vespucci with internet connection.
2. Vespucci with "Airplane Mode" on.
3. Vespucci with "Airplane Mode" on after closing and reopening the App.
![Screenshot_20230326-144013~2](https://user-images.githubusercontent.com/128996366/227800653-8dbcfc4c-d705-4574-902c-0afc6323a27d.png)

**Comment by simonpoole** [comment]
> You could do the test yourself and activate "Airplane Mode", close Vespucci and open it again and check if the images are actually displayed or not.

You are using Bing which is a special case and will not work without network connectivity.

**Comment by afgb1977** [comment]
> > You could do the test yourself and activate "Airplane Mode", close Vespucci and open it again and check if the images are actually displayed or not.
> 
> You are using Bing which is a special case and will not work without network connectivity.

You are absolutely right, I just checked and Maxar works perfectly offline. Most of my edits are done with Bing Aerial as they have quite a bit of satellite imagery clear and sharp.
I am very sorry for the misunderstanding, I had been frustrated for several weeks and simply believed that it was an error in the app without checking with other sources.
Is there a particular reason for this behavior? I did the test with OruxMaps and the cache is preserved and seen correctly without any kind of connection.
Checking Vespucci a bit I find that there is no url for Bing Aerial of the kind = 
"http://ecn.{s}.tiles.virtualearth.net/tiles/a{q}.png?g=13448" but if I find a direct request to the Bing Aerial metadata in "imagery_vespucci.geojson".
Does it have something to do with "quadkey"?

**Comment by simonpoole** [comment]
@afgb1977 the meta information (key, zoom levels, attribution etc) for bing is/has to be retrieved from an API. We do cache the actual imagery just as any other source, but we would need to cache the meta data too for things to actually work.

**Comment by duiveldoder** [comment]
True - this behavior is limited to Bing! My mistake.

**Comment by vespucci-reporter** [comment]
I've added this as an FAQ https://vespucci.io/tutorials/faq/#background-imagery-cache
