### ISSUE TITLE
Adding a multipolygon to a relation

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#2201]
If you select a building made by a multipolygon, then there is no "Add to relation" item in the menu. 
![Screenshot_2023-03-31-14-46-29-467_com miui global packageinstaller](https://user-images.githubusercontent.com/69987154/229115328-f7fc6c3f-596a-4b2a-b37c-94255aee4b16.jpg)

## Vespucci Version
18.1.4.0.

## Download source
 google play store

## Device (Manufacturer and Model)
Redmi Note 10 Pro

## Android Version 
12

## How to recreate
Select multipolygon and try to add it to relation

**Comment by simonpoole** [comment]
The "Add / remove member" function adds or removes members to the selected relation (this is slightly different than it works for nodes and ways, but they are not relations)*. If you want to add the current, selected, relation to a different relation, you can either select that relation and then use the "Add / remove member", or use the "Relations" tab in the property editor to add the relation to a different one. 

* the reason is that it is just a problem that there is no short way to express the difference in functionality. 

> And if such a building is included in the associatedStreet relation, then when this relation is selected, the building is not highlighted in green.

Could you open a separate issue for this, seems as if the member expression in the preset for associated street relations is not matching.

**Comment by mic140** [comment]
It is not at all clear how one can add a highlighted relation to another relation using the "Add/remove member" function.  I am aware of the "Relations" tab in the property editor.

**Comment by mic140** [comment]
When trying to add a building-multipolygon to an AssociatedStreet relationship, it doesn't even highlight as a possible selection.  And when you click on it, the following message appears:
![IMG_20230331_222442](https://user-images.githubusercontent.com/69987154/229211279-e391f027-8171-40eb-a0bb-1066a87bbb6a.jpg)
I am aware of the "Relations" tab in the property editor.

**Comment by simonpoole** [comment]
Relations have not been supported at the same level as regular objects in the action modes as they do not have geometry of their own (which for example impacts selection). There is no quick fix to this so the workaround via the property editor is the current way to do this.
