### ISSUE TITLE
Follow system theme

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#2218]
Ideally, Vespucci should follow the system light/dark theme by default, rather than requiring users to configure it.

**Comment by simonpoole** [comment]
Vespuccis dark theme predates Android dark mode by years. It would still need to be a preference as older Android version, as said, don't support this at a system level.

**Comment by simonpoole** [comment]
The problem is not determining if the user is using the systems dark theme, it is doing something reasonable for users that don't actually want to follow the system theme. So the current choice needs to be maintained and a third "Follow system" or similar needs to be added, this needs a bit of work and, since not backwards compatible, has to happen at least in a minor release.

PS: it is a setting that people will rarely want to change, so hyperbole notwithstanding, it is going to remain in the advanced prefs.
