### ISSUE TITLE
Unwanted layers turning on whenever app focus lost

### ISSUE THREAD

**Issue by JoeyJoJoJr** [MarcusWolschon/osmeditor4android#2230]
I have a nice setup with multiple layers for my local area - most default, a couple are custom 

![Screenshot_20230409_182123_Vespucci](https://user-images.githubusercontent.com/1538108/230787061-14cf610c-03df-4fc4-9f88-a4e1689aa169.png)
In the most recent maintenance release 18.1.4 I've noticed layers activating themselves whenever app focus is lost. For example, opening any other app, or locking and unlocking the screen.

![Screenshot_20230409_182137_Vespucci](https://user-images.githubusercontent.com/1538108/230787171-9c53e7f9-162a-4aad-bec3-a7e06aeb7dbe.png)

Debug info here

![Screenshot_20230409_182308_Vespucci](https://user-images.githubusercontent.com/1538108/230787179-e64bc1a3-7625-4480-b4d9-d9569e8bf88d.png)

**Comment by JoeyJoJoJr** [comment]
While the app was in the background as I wrote up this bug, another two layers turned themselves on 
![Screenshot_20230409_182624_Vespucci](https://user-images.githubusercontent.com/1538108/230787293-46b77272-0036-4291-add0-b2afea13acee.png)

**Comment by simonpoole** [comment]
There were no relevant changes in 18.1.4 and actually not for quite a while. The visible status is stored immediately on change in a database and that is re-read when the app is being restored. What isn't quite clear from your report is if you left the layer modal/dialog open while the app lost focus, because the issue could be that the modal is being restored while the in memeory layer config is inconsistent.

**Comment by JoeyJoJoJr** [comment]
I didn't leave the dialog open, this has been consistently happening with it closed. Is there a way to send a config file in for reproduction?


-------- Original message --------
From: Simon Poole ***@***.***>
Date: 09/04/2023 18:46 (GMT+00:00)
To: MarcusWolschon/osmeditor4android ***@***.***>
Cc: JoeyJoJoJr ***@***.***>, State change ***@***.***>
Subject: Re: [MarcusWolschon/osmeditor4android] Unwanted layers turning on whenever app focus lost (Issue #2230)


There were no relevant changes in 18.1.4 and actually not for quite a while. The visible status is stored immediately on change in a database and that is re-read when the app is being restored. What isn't quite clear from your report is if you left the layer modal/dialog open while the app lost focus, because the issue could be that the modal is being restored while the in memeory layer config is inconsistent.

**Comment by simonpoole** [comment]
From the screen shot it seems that you sent in a debug dump, did you add anything identifying to it?

**Comment by simonpoole** [comment]
Comparing the debug information with what is displayed it seems as if there is some corruption of the layer database and that is causing the issue (this may have already been caused by a previous version). There isn't a direct way to reset things, but you can try discarding all layers except the data layer, restarting the app and potentially repeating that.

**Comment by simonpoole** [comment]
Ping @JoeyJoJoJr
