### ISSUE TITLE
Apply language change on the fly instead of requiring an app restart

### ISSUE THREAD

**Issue by riQQ** [MarcusWolschon/osmeditor4android#2306]
After changing the language in the Android system, apply the language change in Vespucci on the fly instead of requiring an app restart.

Other apps, e.g. Firefox or StreetComplete, support this.

**Comment by simonpoole** [comment]
Android started supporting per app language settings from API 33 (Android 13) on, we will building against that version (and the associated libraries) this fall and will then likely be able to support changing without restart. 

Currently we are using a third party library that requires a restart (because there is no way to support per app languages without it).

**Comment by riQQ** [comment]
I don't know if it's relevant here but I changed the system language and not the per-app language. Just wanted to clarify my initial post.

**Comment by simonpoole** [comment]
> I don't know if it makes a difference here but I'm talking about changing the system language and not the per-app language. Just wanted to clarify my initial post.

The problem is related, IIRC before we supported per app language selection, the app would change directly with the system, I'm assuming that will return in the fall.  There are certain areas which will require a restart or longer reinitialisation in any case for a language change to take affect, for example the presets as we have to re-read the complete configuration to rebuild differently translated presets.
