### ISSUE TITLE
add a generic descriptive changeset comment if mapper did not add any changeset comment.

### ISSUE THREAD

**Issue by Colonel-Dixie** [MarcusWolschon/osmeditor4android#2392]
Hello,       
If the user did not add a changeset comment, **let the app generate a generic descriptive changeset comment for the changeset**, like the one used with other  phone apps, for example: 
> Created 3 pharmacies, a clothes shop, and 8 other objects; Updated 3 hotels and a hospital      

This will improve and save us a lot of time wasted investigating and trying to understand what the user did and edit especially with the uncommunicative users.         
       
This proposal came to my mind as there is a user who refuses to add changeset comments after many blocks by DWG and comments, and Andy from DWG told me 
> As you've no doubt seen, nothing I've tried within the last couple of years as worked.   
       
So if the DWG can't help, this feature will fix this issue.       
     
Thank you and Best Regards.

**Comment by simonpoole** [comment]
I understand the sentiment, but Vespucci already moans as much as reasonably possible if comments and source tags are missing and automatically adding text will just make it -easier- for users that don't want to add something meaningful. 

There are number of 2nd order issues that would need to be thought about too, for example that even a moderately large changeset would run out of space in the tags.

@SomeoneElseOSM any comments?

**Comment by Colonel-Dixie** [comment]
> if comments and source tags are missing and automatically adding text will just make it -easier- for users that don't want to add something meaningful.     
  
 I agree with this statement. Maybe give them a warning before uploading and asking for a changeset comment, and if they ignore it will be that generic descriptive one. Or maybe prevent users from uploading without changeset comment like Browser and PC Java editors?   Even though it might not guarantee the changeset comment to be accurate and descriptive, users might add just "edit" or a gibberish text, but it will still make them write something hopefully useful.

**Comment by contrapunctus-1** [comment]
I support this, with the change that a changeset comment should be generated and inserted by default, which users can edit or replace if desired.

Most of my changeset comments can be automated - they take the form `<area or route surveyed> - <additions>; <changes>; <deletions>` (similar to OsmAnd's generated changeset comments). Automating it would save me time. (I may have to correct the location, but it would be a significant reduction in time and effort spent.)

Additionally, applications like OsmAnd, EveryDoor, and StreetComplete do away with user-created changeset comments entirely, reducing friction in contributing. This makes them more accessible to casual mappers. While some complexity will remain in a general-purpose editor like Vespucci, it can certainly close this one gap.

**Comment by simonpoole** [comment]
> Additionally, applications like OsmAnd, EveryDoor, and StreetComplete do away with user-created changeset comments entirely, 

This is further one of the most criticized features of these apps, and is of no use at all. It amounts to automatically showing the finger to all other mappers.

**Comment by SomeoneElseOSM** [comment]
In my experience as a Vespucci user (and I've re-checked the latest version just now) Vespucci gets the "amount of badgering" about right.  Most people add good changeset comments, and people who just don't want to, won't. Having Vespucci make up something based on content adds relatively little. If it persuades some people to "go with the generic comment instead", that wouldn't be  a good thing.

**Comment by woodpeck** [comment]
https://www.openstreetmap.org/changeset/143570791 as a prime example of auto-generated changeset comments ;)

@projjalm, I find your comment about changeset comments being the stuff of yesterday somewhat disrespectful. If you want to contribute to OSM in a meaningful way, spending ten seconds on writing a good changeset comment is not too much to ask. See https://wiki.openstreetmap.org/wiki/Good_changeset_comments for why that makes sense. Auto-generated comments are useless. If someone cannot be bothered to write a changeset comment, I'd rather that person did not contribute to OSM at all. Someone who finds it "too 90s" to tell their fellow mappers in a human-readable way what they did can set up their own project in which the data is fully generated by AI. No need for human editors at all. Too 90s.

**Comment by mnalis** [comment]
> Auto-generated comments are useless. If someone cannot be bothered to write a changeset comment, I'd rather that person did not contribute to OSM at all

That might be your opinion, and I understand emotions are running high, but I find such over-encompassing generalizations is bad reasoning, and not very welcoming OSM behaviour either (to say the least).

So, you would **really be OK  with rejecting all [StreetComplete](https://wiki.openstreetmap.org/wiki/StreetComplete) and [EveryDoor](https://wiki.openstreetmap.org/wiki/Every_Door) contributions** as work of their users is _"useless because auto-generated changeset comments could (sometimes) be better written manually"_? I hold your opinions in high regards usually, but here I hope you can see how such wording can be seen as quite disrespectful too (even if you won't consider challenging that claim) 

I'd much prefer if the discussion can be taken in constructive way. I'd too like the option to update changeset comments in some cases too (e.g. see my comment https://github.com/Zverik/every_door/issues/68#issuecomment-1201096104) but in reality, auto-generated comments of on-the-ground-mappers are in 95% of the cases more than good enough, and I don't think I could write much better manual comments myself.

If _you_ @woodpeck can write better comments then me, please see example at https://community.openstreetmap.org/t/rfc-deprecate-hashtag-only-changeset-comments/105770/44 and instruct me how I could write better comment for that example changeset, which would greatly improve the experience of my fellow mappers.

**Comment by Colonel-Dixie** [comment]
Dear @woodpeck , Thank you for your comment, although I always greatly appreciated and respected your opinions and have never disagreed with them, I disagree with you here on the "Auto-generated comments are useless.", I will explain why, and I will give you an example of how it might help in OSM,          
   
For example, see: https://www.openstreetmap.org/user/iran%20map%2028/history        
All of his changesets are "(no comment)" according to https://hdyc.neis-one.org/?iran%20map%2028 he has 18,614 changesets and (6.5%) with comments and only 1.5% are unique comments, which means over 17,405 changesets are "(no comment)". 
   
You mentioned a changeset as an example of how auto-generated comment is not useful, but "Created an unknown object" at least will let me know that the user "Created" an object, not like the user I mentioned as an example above who is editing existing objects in OSM, and you have to waste time and investigate the edit to understand what the edits are.     

I did not want to name an app name, or a user to put them under a spotlight, as this is not my the point of this issue. Before creating and posting this issue here, I spoke with Andy about the user above and he told me "As you've no doubt seen, nothing I've tried within the last couple of years as worked." Andy blocked him many many times before for that, see: https://www.openstreetmap.org/user/iran%20map%2028/blocks 
  
That is why we need at least an auto-generated changeset comment feature or at least prevent the user from uploading a changeset without comment like the iD editor, and then maybe we will have another issue when people add nonhelpful words like this case: https://www.openstreetmap.org/user/majidred/history when the user only say "fix" "add" "delete" and do not say what he fixed, delete or add, but that would be in issue for another day if we did it.    
     
The rest of your comment here I agree with 100%. The time I wasted on investigating changesets without comments would've been spent on improving and mapping OSM, and that's why changeset comment is an important and must-have feature.     
    
Thank you.

**Comment by contrapunctus-1** [comment]
I'll reiterate that generated changeset comments aren't just for "lazy"/uncooperative editors, but also for assisting "serious" mappers by cutting down on time, effort, and inaccuracies.

I've been thinking about what aspects of changeset comments can be generated. Some that come to mind -

1. Determining the smallest area the changeset was made in.

2. Adding a feature - `add [<count>] <preset>` e.g. "add 5 bus stops"

3. Adding details to existing features - `add [<count>] <key>` e.g. "add 5 names"

4. When nodes of a way have been added or moved - `change [<count>] <feature> geometry` e.g. "change primary road geometry" (I would probably change this manually to something more specific, but it's good to have it generated so I don't forget about it in my frequently-large changesets).

5. Similarly, when the nodes of a way have only been removed - `simplify [<count>] <feature> geometry`.

6. When all nodes of a way have been moved the same amount - `move <count> <feature>`.

7. `delete <feature>`

8. When a new feature has the same keys as a deleted feature - `convert <feature> to {node|way|relation}`

**Comment by mnalis** [comment]
> I'll reiterate that generated changeset comments aren't just for "lazy"/uncooperative editors, but also for assisting "serious" mappers by cutting down on time, effort, and inaccuracies.

Agreed!

> I've been thinking about what aspects of changeset comments can be generated. Some that come to mind

One should take into consideration that there is a limit at maximum changeset length (both [technical](https://wiki.openstreetmap.org/wiki/API_v0.6#Changesets_2) and practical), so there should be some prioritizing among those if not all of them would fit.


What I would suggest is **auto-generate that comment and prefill the `comment` field**, and **allow user to edit it** as they wish (or instead access previous comment via already existing dropdown list -- although _unedited_ `comment`s shouldn't be inserted into that history dropdown, for hopefully obvious reasons).

I would also suggest that when uploading edits, the **`Properties` pane is made the default** (instead of `Changes` pane), or that they get merged together (with `comment` and `source` editable fields at the top like e.g. in [JOSM](https://wiki.openstreetmap.org/wiki/JOSM)), as it often happens to me that I forget to change the pane and enter new (currently manually typed) comment, and thus unintentionally upload changeset with wrong/old comment as it was _"hidden"_ from me in UI.

**Comment by HolgerJeromin** [comment]
> So, you would really be OK with rejecting all [StreetComplete](https://wiki.openstreetmap.org/wiki/StreetComplete) and [EveryDoor](https://wiki.openstreetmap.org/wiki/Every_Door) contributions as work of their users is "useless because auto-generated changeset comments could (sometimes) be better written manually"?

Streetcomplete changeset comments are not created by maschine learning (called AI) but handcrafted with love. But not from the osm user but from the quest author.
