### ISSUE TITLE
Allow deselection upon closing app

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2445]
Perhaps add an option to deselect all selections, when closing the app.

Otherwise, we might close the app only to find the next time we open it 3 years later, that's something is still selected.

Just like when we close the Gmail app. Next time we open it if there's a draft we were writing, we can find it in the drafts folder.

Otherwise if we don't look closely we start typing into something that we didn't expect we were typing into.

And maybe even send it to the wrong people.

Of course some users might like going back to the exact operation they were halfway into. So that way it should be a preference.

**Comment by simonpoole** [comment]
If you manually exit the app you've already deselected everything, if the app has been suspended or destroyed by the system you definitely want the current state to be maintained because that can literally happen at any time and 99.9999% of the time you don't want to loose what you were just working on.
