### ISSUE TITLE
"Presets"'s search bar has a weird behavior

### ISSUE THREAD

**Issue by AntoninDelFabbro** [MarcusWolschon/osmeditor4android#2459]
## Vespucci Version
19.3.1 and previous

## Download source
F-Droid

## Device (Manufacturer and Model)
Samsung Galaxy S9+
Google Nexus 6P

## Android Version 
/e/OS, Android 10
/e/OS, Android 9

## Behaviour/Symptoms
When opening "Presets", the "erase text" ("X" icon) from search bar is expanding it.

## Expected Behaviour

Search bar keeps the same height.

## How to recreate
1. Add a object
2. Add attributes
3. Go to Presets, where you noticed the search bar getting smaller and moving the whole page.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information

Video: https://mstdn.social/@OSM_Pontarlier/111291276286336969

**Comment by simonpoole** [comment]
This is not an animation added by us and might be /e/OS specific (I haven't been able to replicate it on any of the devices I've tested it on up to now).

**Comment by simonpoole** [comment]
Ah the swiping bit was the missing piece. Interesting seems as if it is caused by the layout and swiping interacting.

**Comment by simonpoole** [comment]
The effect is caused by the fact there is a ActionMenuView adjacent to the TextView, in landscape/pane mode (aka on tablets) this is visible and in normal (phone) mode it is hidden as the menu items are in the top menu. Due to the decision which menu to show happening in onCreateOptionsMenu there is a slight delay before this is done, which seems to be enough to cause the effect.

Solution: make the ActionMenuView hidden by default (phone mode) and make it visible in landscape mode.
