### ISSUE TITLE
Improved F-Droid support

### ISSUE THREAD

**Issue by RustoMCSpit** [MarcusWolschon/osmeditor4android#2511]
Comparing these two apps: Quillpad has a banner, images, and a high definition logo while this app does not. Please improve the F-Droid page!
edit: F-Droid can't be screenshotted so I used NeoStore which doesn't show the banner, please see it on F-Droid.

![Screenshot_20240229-152420](https://github.com/MarcusWolschon/osmeditor4android/assets/134429563/2ccaf915-d11b-4e3e-ac74-9576b7b5fe37)
![Screenshot_20240229-152431](https://github.com/MarcusWolschon/osmeditor4android/assets/134429563/4ae15f93-ab78-491d-a9f6-f484e11b739e)

**Comment by simonpoole** [comment]
F-Droid is an, opinionated,  independent build service and we don't have any control over what they do or not do. If they or you want better logos etc, there is nothing stopping them or you from putting the work in and doing exactly that, using material from this repository, for example https://github.com/MarcusWolschon/osmeditor4android/blob/master/svg/vespucci-logo.svg

Outside of that note that we do not recommend getting our app from F-Droid due to the many deficiencies in the service, if you don't want to install via google, you can simply use the APK from the releases section.

**Comment by RustoMCSpit** [comment]
> Outside of that note that we do not recommend getting our app from F-Droid due to the many deficiencies in the service, if you don't want to install via google, you can simply use the APK from the releases section

i use obtainium

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/releases/latest might work in obtanium, note that we currently have two flavors of the APK there.

**Comment by RustoMCSpit** [comment]
> F-Droid is an, opinionated, independent build service and we don't have any control over what they do or not do. 

huh, so if you update your logo you have to wait fpr them? is there no control whatsoever?

**Comment by simonpoole** [comment]
> > F-Droid is an, opinionated, independent build service and we don't have any control over what they do or not do. 
> 
> huh, so if you update your logo you have to wait fpr them? is there no control whatsoever?

It is complicated. How things are currently set up I suspect that I would have to make a pull request somewhere in the F-Droid repo and wait till it gets merged.

There is the possibility of setting up media and text in a separate directory in the apps repository but that is a lot of work for something that, not really testable and leads to the question... why?
