### ISSUE TITLE
Ability to stash changes

### ISSUE THREAD

**Issue by dmlls** [MarcusWolschon/osmeditor4android#2560]
Hi and thank you for this great app!

I haven't been able to determine whether there is currently any possible way of "stashing" changes (in the same sense as in [Git](https://git-scm.com/docs/git-stash)). 

I frequently find myself in the situation of having edited something on-site, but there are details that I want to double check later on when I get back home before uploading the changes. Then, I might find another feature that I'd like to edit. In order to keep changelogs granular, it would be very useful to be able to temporally save my changes (i.e., stash them), work on something else, and then unstash them.

**Comment by simonpoole** [comment]
As a single operation this currently doesn't exists, but you can simply write your current changes to an OCS file, and then overwrite your changes by removing the changes from the current data. Then reapply the changes if you want to continue working on them.

I suspect that this will only work reasonably in low activity areas mainly because merging in the presence of conflicts is substantially more involved in OSM.

See https://vespucci.io/help/en/Main%20map%20display/#transfer

**Comment by dmlls** [comment]
Thanks for your answer @simonpoole. Actually, that already helps! I guess implementing a fully fledged stash system would be quite some work, not to mention how to deal with potential conflicts, as you mention.

Anyways, maybe one day :)

**Comment by simonpoole** [comment]
There is already a conflict resolution system for conflicts reported on uploads, that probably could be reused to a point when applying diffs, but in needs investigation.
