### ISSUE TITLE
OAuth constantly requesting authorisation

### ISSUE THREAD

**Issue by davidpnewton** [MarcusWolschon/osmeditor4android#2611]
## Vespucci Version
20.0.5

## Download source
Google Play

## Device (Manufacturer and Model)
Samsung Galaxy A55

## Android Version 
14

## Behaviour/Symptoms
Since upgrading to 20.0.5 the app is asking for OAuth authorisation far too often. Seemingly every time changes are uploaded after the app reloads from the background it re-asks for OAuth authorisation.

## Expected Behaviour
Ask for OAuth authorisation much less frequently.

## How to recreate
Load the app from suspended background state or after rebooting phone. Make edits. Save edits.

## Crash dump submitted (no or yes + date)
No. N/A as app does not crash.

## Any other potentially relevant information
Best guess is that something is going wrong with the caching of the OAuth credentials that was introduced between 20.0.4 and 20.0.5.

**Comment by simonpoole** [comment]
This was fixed in https://github.com/MarcusWolschon/osmeditor4android/pull/2610 as soon as Marcus has time we'll be distributing the (already built) fixed builds.

This is unluckily one of the few things we can't test automatically, and while it looked OK manually, I missed the fact that it was re-authorizing the whole time (for Notes this caused a loop in the end because of a further latent issue).

**Comment by simonpoole** [comment]
New builds have been available since -18:00.
