### ISSUE TITLE
Visual Style for OverPass Data

### ISSUE THREAD

**Issue by afgb1977** [MarcusWolschon/osmeditor4android#2660]
Hello.
At Vespucci we have 2 ways to filter OverPass data=
- inview
- area

OverPass in Vespucci has become a fundamental element in mapping workflows, but we have a problem finding data at low zoom levels when the filtering area is large.
Basically they are not seen unless you have an idea of where they may be within the downloaded area and depending on the size of the polygon we start to see the data in zoom 15.
.
I wanted to propose that the possibility of viewing data brought from OverPass at low zoom levels (12, 13, 14, 15) be added. A marker which indicates where in the bbox the data is. Something similar to what OverPass Turbo does.
Or am I wrong and there is already a function in Vespucci that allows viewing data at low zoom levels? Or is there a possible setting in the visual style?

![OverPass Turbo](https://github.com/user-attachments/assets/ec8b02a8-fdc3-4b90-b8d4-29214672e232)
![Vespucci](https://github.com/user-attachments/assets/a2c3a200-5c9b-4090-9fa8-afbdddedae31)

**Comment by afgb1977** [comment]
![Screenshot_20240814-152234~2](https://github.com/user-attachments/assets/1dfd22b6-28d5-410c-81e2-4a6fbffffaa5)

I think I found a solution. Anyway, a visual style for viewing data at low zoom levels might be a good idea.

**Comment by simonpoole** [comment]
There are two issues here:

- zoom level at which elements are visible: there is no need for me to do anything here, you can simply create your own variant of data styling and set _minVisibleZoom_ to something other than the default. See https://vespucci.io/tutorials/data_styling/

- handling of Overpass results: currently it isn't possible to use special styling or similar because there is just one OSM data layer and all data gets styled the same, there is however an issue open to allow more than one layer see https://github.com/MarcusWolschon/osmeditor4android/issues/2150 . What will likely be available short term is https://github.com/MarcusWolschon/osmeditor4android/issues/2662
