### ISSUE TITLE
Overpass code file

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#2687]
The Overpass request code file is saved with a size of zero.

## Vespucci Version
20.1.2.0

## Download source
github

## Device (Manufacturer and Model)
Redmi Note 10 Pro

## Android Version 
13

**Comment by simonpoole** [comment]
This is caused by a URI conversion for old Android versions that causes problems on recent versions (aka post Android 10), as we don't actually need the conversion any more (aka the URI directly from the system file selector seems to work fine for the post Android 5 versions we support), this is easy to fix.
