### ISSUE TITLE
Handle devices without GPS better

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#273]
```
Currently vespucci has no special handling of devices without GPS (for example 
the smaller Amazon tablets). I'm actually surprised that it seems to work at 
all.

Points to think about:

- using WLAN as ersatz (perhaps via MLS)
- removing the GPS menu 
```

Original issue reported on code.google.com by `sp8...@gmail.com` on 17 Feb 2015 at 9:26

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/11f6eadeb958032f239d35247cf20f7eed20a0a0

**Comment by simonpoole** [comment]
For approximate positioning it would seem as if supporting UnifiedNlp ( https://github.com/microg/android_packages_apps_UnifiedNlp ) would the thing to do, we need to check if we can reliably detect that this is in use (since we do not want to support coarse positioning with google, amazon etc).

**Comment by simonpoole** [comment]
I've done some prototyping on this and the best thing to do is to interface directly with the UnifiedNlp plugins. This is not all too difficut and code from UnifiedNlp can be reused. The apple plugin would have to be explicitly excluded.

Reasoning:
*  the UnifiedNlp plugins already cover a number of cell/wifi based location services including such with the data on device.
* the UnifiedNlp app/services masquerades as teh google service so there is no reasonable way to tell with what we are communicating.
* on a lot of devices the app will not work anyway so we would need to use the plugins directly in any case.

**Comment by MarcusWolschon** [comment]
Very careful here!
We can't copy information of a commercial  cell/wifi database.
Did anyone check that we are legally okay to draw over use user-locations
derived from such a database?
(No guessing please. There have been such problems in the past.)

**Comment by simonpoole** [comment]
There's a misunderstanding somewhere, the main point of using the UnifiedNlp plugins and not the location service is that we can control which data source is used (naturally this only covers the inadvertently using a tainted source problem, not the deliberate misuse). 

For example OpenBmap  (database itself ODbL) or MLS (PD). The only really problematic plugin that exists right now and would have to be excluded is the apple plugin, but likely it would be better to have a positive list anyway and just allow known "good" services to start with.

**Comment by MarcusWolschon** [comment]
Thanks for the clarification.

**Comment by Kilkenni** [comment]
I have a device with GPS module but it (GPS, not the device) is always manually disabled. Every time I open Vespucci it brings up the Android menu for handling GPS settings. Am I the only one experiencing this? Can this "prompt" be disabled somehow? Long story short, my GPS is not working correctly, so I don't use it.
Note: I use the latest 0.9.7.1.1071 f-droid build.

**Comment by simonpoole** [comment]
@Kilkenni Advanced Preferences -> Leave GPS disabled

**Comment by Kilkenni** [comment]
Kudos to you, kind sir!

**Comment by gdt** [comment]
While I'm very sympathetic to the privacy notions expressed above, I wonder if Vespucci should be going to contortions about this if the user has configured network location.   In my case, I have a gapps-free device, uG, and several providers that use on-phone databases.  So using network location is perfectly fine.   If it weren't, I'd be in trouble with osmand using it, rather than just vespucci.

I also do not follow "tainted", either what it means or what the concern is.   These providers give an approximation of location, and that can be shown with an error circle.  That's more or less a single perhaps-wrong fact and far from copyright.  A person editing has to assess the accuracy of the position, think about existing map features, perhaps imagery, and other things, so the fact that there's an iffy position is not really that big a deal.

I like having network location in osmand, because when I start it I get a location close enough to look at the map right away.  (I use LocalWifiBackend as one of my providers, so usually after arriving  someplace while navigating I have some of the local wifis in my database.  If I want in-building nav to work, I drive all the way around before parking or even walk around.)

Certainly "enable GPS" and "enable network location" could both be in advanced preferences.

**Comment by simonpoole** [comment]
Wrt "tainted": when you are using the fused location provider on android you don't have any control over what is being used as a source (it could for example be dead reckoning with input from google map data for a moving device) and  I believe the historic concern was generating tracks based on such data.

Given that we could easily simply not generate tracks when we don't have a GNSS source available that particular aspect is probably not really a current concern. However direct support of unlp would still be a good thing considering that there are many devices on which it isn't possible to use it as an alternative via the OS (and it could potentially be used as a framework for supporting indoor beacons etc).

**Comment by gdt** [comment]
Thanks.  FWIW, "tainted" is probably a bad word, since it implies in en_US that there is something damaged and harmful in an at least somewhat sinister way, vs "probably inaccurate".   I wasn't thinking about tracks, just orienting the user to roughly where they are and showing a dot.   I agree that just not recording tracks fixes this.

It would be nice if uG's NLP fuser had a non-OS interface (probably does) and a library for apps to use; that would let lots of programs be set up to use it.  Particularly with Android 7, even on CM, being difficult about non-system providers, that might be generally useful.

**Comment by gdt** [comment]
Sorry, now I really get it...    The concern is that the track data could really be a copy of a proprietary map via snap-to-road and moving along it.

**Comment by daveo30** [comment]
Which of the plugins included in the UnifiedNlp plugins would be 'good' to implement in Vespucci.
The Apple Plugin is one that would be excluded as discussed above. OpenBMap ( now Radiocells) and MLS seem fine. What about the others?

**Comment by simonpoole** [comment]
Support added in https://github.com/MarcusWolschon/osmeditor4android/commit/25929c845517912e8cc280d5f960ed3c3f1f99d1 (tracks are not possible with this).
