### ISSUE TITLE
Impossible to change OSM user account in Vespucci

### ISSUE THREAD

**Issue by fdroiduser** [MarcusWolschon/osmeditor4android#2731]
## Vespucci Version
20.1.4

## Download source
f-droid

## Device (Manufacturer and Model)
Samsung S23

## Android Version 
14

## Behaviour/Symptoms
Since the last release (?) on f-droid, it is impossible to change user, unless by uninstalling and reinstalling the app.
When clicking "reset OAuth", and then "authorize OAuth", the window displays a text with two buttons "Authorize" (in French: Autoriser) and "Deny" (in French: Refuser), with absolutely no option/menu/etc. to log out and log in using a different account. Put it differently, the same account is logged in forever.
This did not happen before.

## Expected Behaviour
Allowing users to log out, and log in with a different account without uninstalling the app.

## How to recreate
?

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
The behaviour change, aka "logout" button is no longer accessible on the OSM website is due to https://github.com/MarcusWolschon/osmeditor4android/pull/2673 and Android Webviews not expiring the session cookie.

Note that you could have simply changed the password on your OSM account and then changed it back again, that should be enough to invalidate all session cookies (opening an issue before doing something as drastic as an reinstall is in general a good idea).

There are a couple of potential ways to work around the issue, likely we will simply remove the session cookie programmatically.
