### ISSUE TITLE
Refactor Dialogs to use DialogFragment (SherlockDialogFragment)

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#311]
Currently we use AlertDialogs in a lot of places, these have been deprecated and replaced by Fragments resp. DialogFragments (SherlockDialogFragment). A futher issue is that a lot (not all) Dialogs are created in DialogFactory (I assume to reduce code duplication) which makes sense when the only difference is text and buttons, but is very artificial for forms that have a lot of additional logic. For example the upload dialog which btw is likely to get more complex over time. Using DialogFragments provides further potential for reuse of the dialogs as proper part of the UI (it is however unlikely that there are any such uses just right now).

Rough work list

- identify which Dialogs should remain in DialogFactory and which not, move those that shoudn't to seperate classes
- convert dialogs to SherlockDialogFragment 

Things not to forget

- themeing

**Comment by johnjohndoe** [comment]
@simonpoole I am trying to understand the issue ... can you please comment on this and correct me if I am wrong:

Methods such as [`showDialog()`](http://developer.android.com/reference/android/app/Activity.html#showDialog(int)), [`dismissDialog()`](http://developer.android.com/reference/android/app/Activity.html#dismissDialog(int)), [`removeDialog()`](http://developer.android.com/reference/android/app/Activity.html#removeDialog(int)) and [`onCreateDialog()`](http://developer.android.com/reference/android/app/Activity.html#onCreateDialog(int,%20android.os.Bundle)) have been deprecated in API level 13. You suggest using [`SherlockDialogFragment`](https://github.com/JakeWharton/ActionBarSherlock/blob/4.4.0/actionbarsherlock/src/com/actionbarsherlock/app/SherlockDialogFragment.java).

Why do you want to use `SherlockDialogFragment` since [*ActionBarSherlock*](https://github.com/JakeWharton/ActionBarSherlock) has been [deprecated on December 20, 2014 in favor of the AppCompat support library](https://github.com/JakeWharton/ActionBarSherlock/commit/2c71339e756bcc0b1424c4525680549ba3a2dc97)? Did you consider using [`android.support.v4.app.DialogFragment`](http://developer.android.com/reference/android/support/v4/app/DialogFragment.html) instead which is designed to work for Android 3.0 and above?

**Comment by simonpoole** [comment]
@johnjohndoe well if you volunteer to check that  android.support.v4.app.DialogFragment is always compatible with ABS (where we currently use it) and it supports the functionality back to 2.2, then we could obviously simply use that. 

It is BTW not really correct to say that ABS is deprecated because google never had anything to do with it in the first place, the author simply is not developling it any further. However it is not going to potentially vanish in a puff of smoke like stuff that google wants to get rid of.  

In any case AFAIK the API (for once) is essentally the same so from a pure coding pov there is no real difference and we are not tying ourselves more to ABS than before (which would be a legit concern).

**Comment by simonpoole** [comment]
Note: in the process of refactoring the Notes code the openStreetBugEdit dialog has been converted (not commited yet).

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/4d5c8a18515b88955e032188be4fe7d9c1ce44bc refactored all of the simple dialogs.

**Comment by simonpoole** [comment]
Finished in https://github.com/MarcusWolschon/osmeditor4android/commit/c1675118faf48ea1be66204faf3a3082a19808e1
