### ISSUE TITLE
popup name for multi polygon natural water missing 

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#326]
If you have a multi polygon with natural=water the popup on select has only the entry 
Multipolygon #xy

BTW a landuse=forest has the popup 
landuse forest multipolgon #xy
without a seperator : or =
This is inconsistent to ways

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/c7ae2963f463ae926d2598f4a71fb882037dcdc2

**Comment by HolgerJeromin** [comment]
Did you cleaned the inconsistent to ways, too? 
Reference to #287

**Comment by simonpoole** [comment]
Nope as said in 3387 the generation of descriptions for objects needs some looking at in any case, because in many cases a tag combination defines a real world object and not just a single tag. so I expect that we might change the current system to one which uses the best match with a preset function to generate a human readable string in the future, but that needs some more thinking.
