### ISSUE TITLE
proposal of a simple opening_hours editor

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#331]
I have a proposal for a layout for a simple opening_hours editor. This would partial solve #232
`(x)` and `( )` should be a Android Checkbox, `[10:00]` a Android time picker. `[del this entry]` a normal button.

```
-------------------------
 (x) Mo | (x) Tu | (x) We
 (x) Th | (x) Fr | ( ) Sa
 ( ) Su | ( ) PH | ( ) SH

  Start  -   End       or
 [10:00] - [18:00] | ( ) off

 [del this entry]  [add entry after]
-------------------------
 ( ) Mo | ( ) Tu | ( ) We
 ( ) Th | ( ) Fr | (x) Sa
 ( ) Su | ( ) PH | ( ) SH

  Start  -   End   |   or
 [10:00] - [16:00] | ( ) off
 [del this entry]  [add entry after]
-------------------------
 ( ) Mo | ( ) Tu | ( ) We
 ( ) Th | ( ) Fr | ( ) Sa
 (x) Su | (x) PH | ( ) SH

  Start  -   End   |   or
 [--:--] - [--:--] | (x) off
 [del this entry]  [add entry after]
-------------------------
```
This will be converted to
`Mo-Fr 10:00-18:00;Sa 10:00-16:00;Su,PH off`

I think this editor would be able to edit 90% of the values in the DB and 99% of the values i want to add new into OSM on the road.
Too complex opening_hours (with date ranges and so on) should be rejected to edit.
The presented value could be the default, but perhaps the default could be changeable in the prefs.

**Comment by johnjohndoe** [comment]
Could you please explain what `PH` and `SH` means?

**Comment by simonpoole** [comment]
There is already an issue on this topic see https://github.com/MarcusWolschon/osmeditor4android/issues/232

@HolgerJeromin I'll consider the layout in https://github.com/simonpoole/OpeningHoursFragment and https://github.com/simonpoole/OpeningHoursParser likely complicated stuff will simply be collapsed by default in the UI, simply ignoring the complicated cases doesn't really work since "editing" implies dealing with the values that are already present (a write only OH composer would be simple).

@johnjohndoe PH are public holidays and SH school holidays

Closing and referencing in https://github.com/simonpoole/OpeningHoursFragment/issues/1

**Comment by johnjohndoe** [comment]
Simply for reference: You might want to compare what the [opening_hours.js](https://github.com/ypid/opening_hours.js) library does.

**Comment by simonpoole** [comment]
@johnjohndoe actually no

**Comment by HolgerJeromin** [comment]
I want an simple editor for most usecases via menu item. The complex or buggy cases can be left for the plain text input.

**Comment by simonpoole** [comment]
@HolgerJeromin have you actually tested the OH editor yet?

**Comment by HolgerJeromin** [comment]
I am not in the play store beta program. I read somewhere that there is one for vespucci, but i could not find a way to get into it (but i am for osmand, mapillary). 
So i had not the possibility to test it till now.
I dont want to install an apk myself because i want automatic updates...
