### ISSUE TITLE
faster feedback if called from a geo: intent

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#339]
Right now if called from osmand or osm.org website via geo: intent vespussi is loading the old data first. 
This is ok, but on my old device it takes sometimes > 10-20 seconds to jump to the new position and starting download data there.
In the mean time there is no hint, that something is working in the background and i have to wait.
So i desire a user feedback, that loading of the new area is waiting, or the whole process (switching view) has to be ready in < 500 ms.

**Comment by simonpoole** [comment]
Which version of Android is your "old" device running? 

In any case the problem (IMHO unsolvable as long as receiving the intent restarts the app) is that vespucci (simplified a bit)
* has to save the current state and terminate (currently without user feedback because in general you wouldn't want it when terminating)
* restart and receive the intent (this is probably the annoying bit)
* re-read the saved state from above (user feedback present)
* download the new area  (user feedback present)

**Comment by HolgerJeromin** [comment]
I have a Desire HD with a 4.0.4 Custom Rom (Viper DHD).

**Comment by simonpoole** [comment]
Note: the completely restarting problem may be solvable now with the changes made for 0.9.7, This would likely address the whole issue.

**Comment by HolgerJeromin** [comment]
I just tested further. 
I killed vespucci via the task manager.
Then i started the intent and vespucci is started with the old data. I was able to use the app! Panning around, bing image was updated, clicking a way, starting editing the tags of it!
After leaving the editing, vespucci jumped to the next coordinate and loaded the data.

**Comment by simonpoole** [comment]
You can exit vespucci completely by pressing the back button with the exception of when you are recording a track.

That the geographical intent works/has to work when the app is not running is intentional and part of the problem.

**Comment by simonpoole** [comment]
Id this still an issue?

**Comment by HolgerJeromin** [comment]
Using now an Fairphone 2. This Phone or the current app works good enough.
