### ISSUE TITLE
Vespucci forces me to enable GPS over and over again

### ISSUE THREAD

**Issue by M-Reimer** [MarcusWolschon/osmeditor4android#341]
Since the last update shortly after starting Vespucci, the dialog to enable the GPS pops up. If I just want to close this, it keeps opening over and over again. If I enable the GPS to get rid of this dialog and disable it shortly after that, it reappears within a few seconds, again.

I don't want to use the smartphone builtin GPS at all and I want to have it disabled all the time. If I go out for mapping, I connect a better GPS using bluetooth.

Please fix this so I can keep the GPS disabled or tell me which feature I have to disable to prevent Vespucci from asking for the GPS.

**Comment by HolgerJeromin** [comment]
same here. my gps antenna is broken, so letting internal gps on is wasted battery for me.
could be an advanced setting

**Comment by simonpoole** [comment]
The issue was adressed partly in 0.9.7 with https://github.com/MarcusWolschon/osmeditor4android/commit/11f6eadeb958032f239d35247cf20f7eed20a0a0 it needs an addtional preference to mimic not having a GPS provider at all (as in "leave GPS off if disabled"). @M-Reimer you don't indicate which version you are using, but there were no GPS related changes in 0.9.6  so the bahaviour should not have changed.

**Comment by M-Reimer** [comment]
I'm using 0.9.7.0.1036
The problem appeared directly after updating to this version this morning.
Yesterday, I was using whatever version was before that and the GPS request only popped up if disconnect my Bluetooth receiver while the GPS logging is still active. But even then it only popped up once and could be closed.

**Comment by simonpoole** [comment]
@M-Reimer yes the changed behaviour is due to the better support of devices that don't have GPS at all (or put differently: not re-checking was a bug). In any case https://github.com/MarcusWolschon/osmeditor4android/commit/4b50a4cfeb11e5cec9858b054059685a3c04a9fb addresses the issue.

A build with the fix is here (however not signed with the same key as the version on the play store)
https://drive.google.com/folderview?id=0B9pKLmh8s1h8bFI5bGd4VnhYWkk&usp=sharing

**Comment by HolgerJeromin** [comment]
thank you for your quick fix

**Comment by simonpoole** [comment]
@M-Reimer any feedback?

**Comment by simonpoole** [comment]
beta version on the play store has the fix
