### ISSUE TITLE
Vespucci creates changeset without created_by=*

### ISSUE THREAD

**Issue by Nakaner** [MarcusWolschon/osmeditor4android#342]
A few days ago I uploaded a changeset. I do not know what really went wrong but OSM API shows [this changeset without `created_by=*`](https://www.openstreetmap.org/changeset/33801839). I found this just because I scrolled through my editing history. As far as I can remember, I was asked if I want to discard my changes when I downloaded OSM data from the API the next time, i.e. the upload has not been finished. 

As far as I can remember, something went wrong when I tried to upload its [preceding changeset](https://www.openstreetmap.org/changeset/33801733). I noticed that because I was asked if I want to discard my changes when I downloaded data after the data upload.

I do not know how Vespucci uploads its changes but it looks as the `created_by=*` tag is being uploaded at the time of the closure of the changset (i.e. if an upload breaks, the changeset is left without a `created_by=*` and closed by the API after an idle time).

**Comment by simonpoole** [comment]
This sounds weird, the tags are set when the changeset is opened and the only case in which they could be  modified if you select the option to not close the changeset after upload. Even if the upload failed and you are reusing the original changeset because it is still open the created-by tag should remain unchanged. 

Will need further investigation.

Note: you are using a rather old version of vespucci.

**Comment by simonpoole** [comment]
Seems to have been a one off event.

**Comment by simonpoole** [comment]
The error was likely the same as here https://github.com/MarcusWolschon/osmeditor4android/issues/463 (option to not close the changeset after upload likely set) https://github.com/MarcusWolschon/osmeditor4android/issues/463, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/d6699fa57db2203619cdd1371e18ef66da718a81
