### ISSUE TITLE
Logic / writeOsmFile / Target directory is not being used

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#363]
I stumbled over the following lines in the `writeOsmFile()` method of the `Logic` class:

``` java
File sdcard = Environment.getExternalStorageDirectory();
File outdir = new File(sdcard, Paths.DIRECTORY_PATH_VESPUCCI);
outdir.mkdir(); // ensure directory exists;
File outfile = new File(fileName);
```

Source: [Logic.java#L2555](https://github.com/MarcusWolschon/osmeditor4android/blob/0.9.7/src/de/blau/android/Logic.java#L2555)

Please correct me if I am wrong but it appears to me as if the directory being created in the first three lines is not being used here. I supposed this never failed because the "Vespucci" directory had been created by other parts of the application before.

**Comment by simonpoole** [comment]
The code is a bit silly and brittle as is. It should naturally parse the file path and create the necessary directories to be clean, but it does work and the directory is used because filename is constructed to actually contain the directory when writeOsmFile is called. Given that there is currently no way to actually select a different directory (see https://github.com/MarcusWolschon/osmeditor4android/issues/313)  there is no real danger of it going wrong inadvertently. 

Proper way to do it is roughly

File outfile = new File(fileName);
File parent = outfile.getParent();
if (parent != null) {
    if (parent.mkdirs()) {
....

**Comment by johnjohndoe** [comment]
Oh, this might indeed need some refactoring. I created #364 as a short term clean up.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/39e9b3592bcdf793c06b4f2c3280cee6a44addde
