### ISSUE TITLE
Crashes when backing out from editing multiselection

### ISSUE THREAD

**Issue by tweejee** [MarcusWolschon/osmeditor4android#422]
Because I was requested in the app to submit an issue when a crash happened repeatedly: here it is. I'll try to document it, but if more info is needed please contact me.

Actions that caused the crash:
Open Vespucci from OsmAnd. Select a way. Choose menu > Extend selection. Select another way. Choose Edit tags. Hide keyboard. Tap "back" softkey.

Result:
Vespucci restarts. In message centre a message "Vespucci has crashes or..." appears.

Device:
Sony Experia Z2 (D6503). Android Lollipop. System and app up to date.

**Comment by simonpoole** [comment]
Most important information would be which Vespucci version you are using (visible at the top of the advanced preferences).

**Comment by tweejee** [comment]
Version is 0.9.7r1093. And yes, I did send in three crash dumps.

Please let me know if there's anything else I can help with.

**Comment by simonpoole** [comment]
Yes found the crash dumps now. The issue may have already been fixed (can't recreate it right now), where the ways in question members of a relation?

**Comment by tweejee** [comment]
Yes, the ways in question are members of different relations. And selecting the relations themselves causes the same issue.

**Comment by simonpoole** [comment]
Can't recreate the issue with the current maintainance branch, so likely it was fixed as mentioned. A new build of that is waiting to be pushed to the google playstore in any case and will be available as soon as Marcus gets to it.I'll leave the ticket open till the fix is confirmed.

Note on the side: double tapping an element will start the "Extend selection"/Multi-Select mode too, a bit faster and easier to use likely.

**Comment by tweejee** [comment]
Thank you.

And let me take the opportunity to say how much I appreciate Vespucci.
