### ISSUE TITLE
Uploaded changes don't disappear from upload list

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#425]
When I create a node and upload it, I get a confirmation message about a successful upload. (The upload is also visible on openstreetmap.org.) So far, so good.

However, if I again click "Upload data to OSM server", Vespucci has the uploaded node still in the list of changes. I also noticed that selecting the node on the map after the upload prompts me to choose from a list of two entries (saying `Parking` in my case for `amenity=bicycle_parking` and `capacity=24`). I'm assuming that there are now two instances of the node, one uploaded and the other not.

I'm using 0.9.8b1098 on Fairphone 2 (Android 5.1).

**Comment by simonpoole** [comment]
The regression (was specific to a recent 0.9.8 build) was fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/3b51eb90ac4d3f8e1df02158c3b56cc3fec3040b 

@MarcusWolschon I don't believe the beta version available from google has been updated yet? 

If you are not using the google play version, you can install https://drive.google.com/drive/folders/0B9pKLmh8s1h8bFI5bGd4VnhYWkk
