### ISSUE TITLE
UI improvement : prevent unwanted lines splitting while dragging 

### ISSUE THREAD

**Issue by brunetton** [MarcusWolschon/osmeditor4android#442]
I just understood the main UI problem that prevents me to be efficient when using Vespucci: very often, while dragging the view, I split a line. 
I thought that when dragging screen  without any object selected, I was "secure" from moving anything. For moving a node, it must be selected first. It's a very good point. For editing a way, this way must be selected first. But I realize that it's false for adding a point to any line: it can be done without selecting the line first. 

As adding a node to a way is not a really common task when editing, I suggest that the way must be selected first to be able to split it then. 

Thanks

**Comment by simonpoole** [comment]
While not completely happy with the way it works now, it is a result of testing many variants, including what you are suggesting. 

The problem with your variant is that the node should be selected after dragging the way improvement handle (in case you need to adjust the position a bit more) so the work flow when adding multiple nodes is:

select way - drag - select way - drag - select way - drag ...

instead of the current

drag - drag - drag - drag - drag ....

There are some ideas floating around how to make it less easy to accidently add a node, including simply moving it to a separate mode. Currently the best way to work around it is to lock the screen (one click on the lock icon), or use the "tag only" editing mode (long click on the lock icon).

Simon

**Comment by simonpoole** [comment]
I've got a working prototype that would change the behaviour (for 0.9.9) to work as iD currently does (right now Vespucci is more similar to JOSM). 

That means:

- select way
- drag handle (way remains selected and new node is not)
- drag another handle 
.. and so on.

this does have the disadvantage that if you stop dragging the handle but then realize that you need to improve the position you need to select the node, move it and then re-select the way.

Comments?

**Comment by simonpoole** [comment]
Changed to behaviour similar to iD in https://github.com/MarcusWolschon/osmeditor4android/pull/498
