### ISSUE TITLE
Vespucci Connector

### ISSUE THREAD

**Issue by BoFFire** [MarcusWolschon/osmeditor4android#473]
Hi, could you please add this feature to Vespucci : a Vespucci Connector like JOSM so that we can be able to open OverPass requests directly on Vespucci or have the possibilty to edit relations directly by clicking on an URL thar brings relation, node or way on Vespucci for futher edits such adding ref=\* or any missing tag.

Thank you ;)

**Comment by simonpoole** [comment]
While I'm not quite sure that I understand what you want, but Vepucci has supported JOSM style remote control for a long time and this is used for example when selecting a notification. The problem is that Android browsers don't seem to take intent filters in to account and don't pass such URls through to apps.

**Comment by BoFFire** [comment]
Hi again @simonpoole,
Can you tell me how to pass this relation on vespucci ? Since no idea how to do it.
http://localhost:8111/load_object?objects=r1234567890
Thank you :)

**Comment by simonpoole** [comment]
The load_object command is czrrently not supported only land_and_zoom and zoom with the select parameter. Note that the current implementation is not very robust wrt missing parameters etc.

That will be improved and maybe the whole thing documented.

**Comment by simonpoole** [comment]
See http://vespucci.io/tutorials/vespucci_intents/ and https://github.com/openstreetmap/openstreetmap-website/pull/1478
