### ISSUE TITLE
Incomprehensible error msg when trying to upload a change to OSM without login credentials

### ISSUE THREAD

**Issue by leuty** [MarcusWolschon/osmeditor4android#490]
I downloaded Vespucci from the Play Store and forgot about it. When I then tried to upload my first changeset I got an error msg containing something about "consumer keys". After setting the OAuth Login credentials the msg is gone.

Problem: I was confused when I saw the message. It was not clear to me what is wrong.

**Comment by simonpoole** [comment]
I assume the message was "OAuth handshake failed, check that you have proper consumer keys"? 

You normally shouldn't get the message on initial upload, instead you will just be asked to login and authorize the app (a one time exercise). It is an indication that something went wrong with the initial handshake between vespucci and the API, which might be due to a number of reasons (flaky connection or whatever). 

So while I would like to improve the message it is a bit difficult, because fundamentally something unknown is going wrong unseen by the user. I'll have a look at improving the debugging, but have my doubts if we can do more.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/21d25690bfd504957353cbef380c44ff553f22f0 addresses this to a certain point.
