### ISSUE TITLE
grey out undo when there are no items to undo

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#505]
Current version from f-droid on CM14.1.  It seems like the undo item doesn't grey out when the stack is empty, although I do get a "no items to undo" kind of toast.

**Comment by simonpoole** [comment]
Actually it never has "greyed out" in that sense, it will go away on upload (once there are no changed elements in memory). It will remain even when you have used up the complete undo stack, because a long press will call up the redo menu. I'm not claiming it is particularly intuitive but it's been that way long before I ever used the app :-).

**Comment by simonpoole** [comment]
See also https://github.com/MarcusWolschon/osmeditor4android/issues/253

**Comment by simonpoole** [comment]
This is actually expected behaviour as there are redo elements present if the undo stack has been used, the indication simply needs to be better that there are elements on the redo stack.
