### ISSUE TITLE
created_by is not removed on update of a way

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#527]
I just added lit to a way 
https://www.openstreetmap.org/way/24605572/history
but vespucci did not removed the created_by tag from it. 

Vespucci 0.9.8.1.1228 on fairphone 2 with Android 5.1

**Comment by simonpoole** [comment]
The corresponding code wasn't added to the diff upload mechanism that we switched to for 0.9.8 (which just goes to show that tests are important :-/).

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/8253ab29d00c06c182fc44dadba36484d0c92997 and https://github.com/MarcusWolschon/osmeditor4android/commit/824445e53f2e2e9538ca788cb29b276cb3a0148d
