### ISSUE TITLE
(Multi)polygon fixing effort

### ISSUE THREAD

**Issue by joto** [MarcusWolschon/osmeditor4android#535]
There is a major effort going on to fix broken (multi)polygons in OSM and also to finally get rid of *old-style* multipolygon relations. This will hopefully lead to simpler and more efficient software. There is no immediate need for you to change anything in Vespucci, but I would expect there to be opportunities to simplify your code and generally make life easier for you once this effort is successful.

I wanted to make you aware of the effort and get you involved in the discussions. We'd also appreciate it if you can support this effort in any way. Find all the details at http://area.jochentopf.com/. We are coordinating with other software project through our issue osmlab/fixing-polygons-in-osm#23.

**Comment by simonpoole** [comment]
Hi @joto 

We currently don't so anything special on the rendering side wrt MPs as we, with the exception of some indoor areas, currently only render outlines which makes life very simple. This is mainly due to not wanting to obscure whatever is being used as a background with more than a minimal wireframe like data rendering, because of the typical low contrast situation Vespucci is used in, however see https://github.com/MarcusWolschon/osmeditor4android/issues/312

As to creating MPs this needs to be investigated, as a tendency we probably already tend to motivate to do this right.

**Comment by simonpoole** [comment]
Update we now render MPs https://github.com/MarcusWolschon/osmeditor4android/commit/6357d753ffc24d815018d03fe49372392316163e currently rings that have no role set are "highlighted" but there isn't much validation otherwise.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/pull/1266 will automatically move tags on outer elements to the MP relation.
