### ISSUE TITLE
area=yes interpreted as dog park

### ISSUE THREAD

**Issue by scaidermern** [MarcusWolschon/osmeditor4android#543]
Vespucci 0.9.8.1.1242 (from g**gle play store) shows the preset "dog park" for areas tagged with `area=yes` despite the tag `leisure=dog_park` being _not_ present:

![photo_2017-03-29_13-45-32](https://cloud.githubusercontent.com/assets/1040784/24452934/117ea1b4-1486-11e7-80f3-1be1d11e3f1d.jpg)

![photo_2017-03-29_13-45-28](https://cloud.githubusercontent.com/assets/1040784/24452943/1877306c-1486-11e7-9578-242968bc591e.jpg)

Not sure if this is a bug in the preset or Vespucci. The preset seems to require a `leisure=dog_park` tag if I understand correctly.

**Comment by simonpoole** [comment]
This is a a preset / data error IMHO.

When matching against presets Vespucci calculates a score that is heavly biased towards matching the fixed tags, if there are no fixed tags present that can be matched, it will try against other tags (and typically use a nearly random preset if the scores are the same).

The fix is on the one hand that the dog park preset needs a match="none" attribute for the area tag, or it needs to be in an optional section, on the other hand an otherwise untagged object with area="yes" is naturally not useful.

**Comment by scaidermern** [comment]
Yes, the tagging in the screenshot isn't very useful. It was just an example.

If version 0.9.9 doesn't have this issue any more then this is fine.
