### ISSUE TITLE
Steal UI for entering opening_hours from StreeStreetComplete

### ISSUE THREAD

**Issue by steelman** [MarcusWolschon/osmeditor4android#544]
[StreetComplete](https://github.com/westnordost/StreetComplete) has a great UI for entering values of opening_hours. Please implement it in Vespucci (on the more general Properties tab).

**Comment by simonpoole** [comment]
It might be great but i is hopeless for dealing with already existing OH. Unluckily it is -far- complexer than simply adding new values. See https://github.com/MarcusWolschon/osmeditor4android/issues/232 for more info.

**Comment by DFyson** [comment]
How about just sticking to the easy stuff for now? So if the content of OH is either non-existent or simple to parse, then use the editor. I feel this would cover the vast majority of cases. I rarely come across complex opening hours, although occasionally come across incorrectly formatted ones because someone guessed at the formatting.

If it doesn't already exist, someone should make a generic library for parsing opening hours that apps like this one can use without having to make it from scratch. There seems to be at least one for php looking at [the wiki](https://wiki.openstreetmap.org/wiki/Key:opening_hours#Code) but it still seems pretty simple.

What would be really slick is being able take a picture of the OH on a store front and have it auto complete a form for user verification and submission. I find I tend to avoid adding opening hours because of just how tedious it is, even with a nice interface.

**Comment by simonpoole** [comment]
Sigh @DFyson please have a look at the already referenced https://github.com/MarcusWolschon/osmeditor4android/issues/232 and then https://github.com/simonpoole/OpeningHoursFragment , https://github.com/simonpoole/OpeningHoursParser and https://github.com/simonpoole/OpeningHoursFragment/issues/5

And yes lots of these seemingly obscure uses of OH are in use, and an editor (instead of an overwrite what is there program) needs to be able to handle these in one way of the other (as you at least need to know for which elements you don't have an UI you need to have to have an UI to handle those).

**Comment by simonpoole** [comment]
@DFyson the main problem with using machine learning (forget character recognition on its own) is the amount of time building the model and training it will take with no guarantee for success. If you can find somebody willing to sponsor a couple of man-months (at least)  then things would be different.

**Comment by DFyson** [comment]
oops missed that when I read over #232. I added it to [the wiki](https://wiki.openstreetmap.org/wiki/Key:opening_hours#Code).
Maybe machine learning could be avoided since OH tend to have a simple layout of one day per line.

**Comment by steelman** [comment]
Or range of days per line.
