### ISSUE TITLE
Display time stamp of last edit for a place

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#554]
I would like to see the time stamp of the last edit of a place.
Can you retrieve the information from OpenStreetMap and display it in the "Element information" dialog shown in the screenshot?

![Vespucci, "Element information" dialog](https://cloud.githubusercontent.com/assets/144518/25752980/40c2884a-31ba-11e7-903c-9ebae4baf00f.png)

**Comment by simonpoole** [comment]
This is trivial to implement (we currently simply don't parse and store the timestamp) and I've been thinking of doing it since it opens up a number of QA avenues which you were likely thinking of too, 

The trade off is that it adds a long to every element in storage, which for way nodes with no tags (the most common object) is an increase by 20% in required memory.  Historically we've been fairly conservative wrt memory consumption because of the very limited heap available on old devices, obviously we could just do it for objects with tags but that adds extra complexity that is likely not worth it.

**Comment by johnjohndoe** [comment]
If I understand correctly, you want to store the value as a `long` because you want to display the date/time depending on the user's locale setting?

**Comment by simonpoole** [comment]
ms since the epoch is simply the most convenient representation (timezone independent), seconds since the epoch currently fit in an int and would be an alternative and potentially, depending on alignment, padding etc could currently come at near zero cost (well to the next time we add a field that is).

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/b02be8ec4a76b28df7fb65376064c516ffa3387b
