### ISSUE TITLE
tag input not possible with android keyboard MessagEase 

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#571]
i have installed the fantastic keyboard MessagEase. 
But entering tag namens is not possible. Every char is cleared after a few hundred milli seconds.

Entering values works

## Vespucci Version
0.9.8r1242

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
6.0

**Comment by simonpoole** [comment]
The "Details" view uses a completely standard AutoCompleteTextView for input (see https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/res/layout/tag_edit_row.xml ) nor does the associated code do anything particularly exotic. It seems to be a bit unlikely that this is an issue with vespucci, I would suggest asking the company producing MessagEase first before we embark on debugging this. 

BTW you may want to disable the the microphone privilege the keyboard asks for.

**Comment by HolgerJeromin** [comment]
Microphone is needed for speech to text.

**Comment by HolgerJeromin** [comment]
I wrote a mail to support and got a few hours later:

> Thank you very much for your interest in MessagEase and you feedback. 
> I'm sorry about the problem you encountered, and I'•e asked one of our devs to look at this issue. 
> Hopefully we'll be able to find a fix for it and include it in our next update.

**Comment by simonpoole** [comment]
Since we didn't get any feedback from MessageEase, I did a quick test myself: the issue only exists when word prediction in MessageEase is turned on, turning it off fixes the problem. 

Note: as can seen in the layout referenced above the AutoCompleteTextViews have android:inputType="textNoSuggestions" set so likely MessageEase shouldn't be trying to suggest words regardless of its settings.
