### ISSUE TITLE
GPS location button and 'Show location'

### ISSUE THREAD

**Issue by silvermapper** [MarcusWolschon/osmeditor4android#581]
'Show location' box is checked in Vespucci on my 'phone.  I am surprised the blue arrow does not appear in the centre of the screen when I touch that button and is not within the screen at all sometimes.  I use Locus Map very much and my location centres in the selfsame situation.  Should it occur likewise in Vespucci?  Have I not set it up correctly?

**Comment by simonpoole** [comment]
When you touch the "GPS Button" on the left hand side it should pan the screen so that the position is in the center of the screen and continue to track the position. The arrow should just be an outline as long as it is in that state, if you manually move the screen it will fall out of that mode (because you don't want the view changing while you are trying to edit) and will show a full blue arrow, which can be off-screen. Re-touching the "GPS-Button" should re-center as described above.

**Comment by silvermapper** [comment]
Simon
It is totally immaterial now, but I am as certain as can be that the GPS button in black in the middle of the left-hand side of the screen to which I understand now you clearly refer, has not been there until this morning - I had been using the GPS 'button' in the bar at the foot of the screen, hence the issue.  I have been conscious of a grey outline circle only.  No matter - all is well now.
There is much to learn, but I am becoming increasingly comfortable with the application and can see myself using it more and more as I learn.
I thank you for your help.
