### ISSUE TITLE
Nodes that cannot be moved

### ISSUE THREAD

**Issue by MikeParfitt** [MarcusWolschon/osmeditor4android#591]
According to the map in my satnav, I was driving across the sea this afternoon and some of the coastline was represented by straight lines that met at 90 degrees.

So I decided to try and improve the modelling of the coastline, but was unable to move some nodes on Way #403957865

Some of the nodes on the way have 1 node number (e.g. #1571491855) and can be moved, these have very small red dots on the way.

The node to the East of it has two node numbers (#21163076 and #4062508183) and cannot be moved, nodes like this have slightly bigger red dots on the way.

There are quite a lot of nodes like this that cannot be moved.

## Vespucci Version
0.9.8r1285

## Device (Manufacturer and Model)
Glaxy Tab S2 SM-T715

## Android Version 
7.0 (not rooted) with security patch dated 1st April 2017

## Behaviour/Symptoms
Tapping on nodes with very small red dots selects them and allows them to be moved.  Tapping on nodes with slightly larger red dots brings up information dialogue

## Expected Behaviour
That all nodes on a way can be selected and moved to correct positioning errors

## How to recreate
Try to move one of the nodes on Way that has a slghtly bigger red dot

## Crash dump submitted (no or yes + date)
No

**Comment by simonpoole** [comment]
I'm fairly sure that this is not directly a bug, but the situation should be handled and documented better.

The "unmovable" nodes were likely outside of the downloaded area. Since such nodes can be members of ways that have not been downloaded and you probably don't want to inadvertently change such ways without downloading them first, we don't allow such way nodes to be selected (they are only downloaded because they are members of a way that extends outside of the area) and moved or changed in any other way.

That they are not selectable is indicated by the missing "touch halo". Maybe we should add a toast with explanatory text pointing out that they can't be moved when the user tries to select them.

See the following screen shot, lower part downloaded, upper part not.

![screenshot_1501192575](https://user-images.githubusercontent.com/1011860/28693909-54983514-7327-11e7-80f2-22828e15bb3a.png)

Note on the side: the nodes of the admin boundary and tos of the other ways do not seem to be shared which at least some would consider a data error, see http://osmose.openstreetmap.fr/en/map/#zoom=14&lat=56.53667&lon=-5.81765&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT&item=xxxx&level=1%2C2%2C3&tags=&fixable=

**Comment by MikeParfitt** [comment]
Hi Simon, the nodes are all in the downloaded area.  Nodes #1571491855 and #1571491864 both lie on Way #403957865, have little red dots and can be selected and moved.  The larger red dot is between these two and has a double-size orange circle.

![nodes a b and c downloaded and unlocked](https://user-images.githubusercontent.com/29509220/28748157-7475d616-74a8-11e7-8bf6-1ff661057da9.png)

![selection of node a](https://user-images.githubusercontent.com/29509220/28748158-7e5923fe-74a8-11e7-8000-6fb159395394.png)

![selection of node c](https://user-images.githubusercontent.com/29509220/28748160-8598165c-74a8-11e7-8907-48a603af960a.png)

**Comment by simonpoole** [comment]
The large halo for the node in the middle is because one of the two nodes there (#21163076) has a tag so that is not a sign of a specific issue.

In any case I wasn't able to recreate the issue with 0.9.9, Will check with 0.9.8 in a minute.

**Comment by MikeParfitt** [comment]
Sorry about the delay in replying.  I didn't realise that I could tap on the entries for each node in the information dialogue to select just that node.  Once I did that, it was possible to move that node by itself, seperating it from the other node at the same location.  Then I could select and move the second node.

![screenshot_20170810-092911](https://user-images.githubusercontent.com/29509220/29161701-1d194802-7daf-11e7-8a3f-2b29b3071f77.png)

So this turns out to be a lack of familiarity with the user interface.

Although it does beg the question, what is the point of having two coincident nodes on two seperate ways, when the nodes either side have both ways united via a single node ?

**Comment by simonpoole** [comment]
I mentioned this earlier on that IMHO there is a bit of a data problem in the area however it is not clear what the best way forward is (merge all the nodes, keep them separate, but clearly not a mix of both). I would suggest taking the issue up on talk-gb.

Closing this now.
