### ISSUE TITLE
cliff rendering should indicate cliff direction

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#596]
Currently in Vespucci http://www.openstreetmap.org/#map=19/50.03944/19.91314 is quite hard to edit as cliffs are shown as green lines. In JOSM it looks like this:

![selection_001](https://user-images.githubusercontent.com/899988/29493215-8a541330-8592-11e7-9c76-5464baf5d15e.png)

![screenshot_2017-08-20-10-27-18-595_de blau android](https://user-images.githubusercontent.com/899988/29493353-59e01134-8594-11e7-97d3-75111340bda7.png)

I needed to fix my edit in JOSM as half of cliffs was mapped in wrong direction.

related to #312

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/8039145e98fac6b15fee5d2110b06e2ad9bb5b60

**Comment by jajajaneeneenee** [comment]
It would be very nice (and important) to have such a styling also for `barrier=retaining_wall `(like in JOSM). At the moment I always have to check it in JOSM afterwards if a new retaining wall way really has the right direction. Should this be a new issue?

**Comment by simonpoole** [comment]
Well it should be a new issue (in general nobody is going to work on a closed issue), but better simply a pull request. While currently there is only a limited number of hardwired asymmetric patterns (the triangle pattern and border pattern) and adding more would need a bit of coding, walls should be easy to distinguish by colour. 

With other words just create a custom data style, add your styling there and if it works create a PR against the default, included styles, see http://vespucci.io/tutorials/data_styling/ for more information.

**Comment by jajajaneeneenee** [comment]
I am not very familiar with GitHub, didn't know if a closed issue would be opened again if necessary ... but I can open a new issue of course. I also have to check what a pull request means (sorry ...).

And thank you for the hint with Vespucci Data Styling and the tutorial page (is it new? I did not saw it before) – I wanted to try that out anyway, I am familiar with CSS styling for example and some coding ... I should be able to do that.

But I am not sure if you understood that the DIRECTION of a line is important with retaining walls (same as with cliffs – which is the side with the lower and the higher level?). I don't think that this can be displayed with line styling by a single color, or can you created a two-colored line (e.g. left side = red, right side=blue)? 

I am also missing a simple thing (perhaps too simle to mention it) in the tutorial: what is is the target path/folder for the xml file? Simply the Vespucci folder in the internal memory? And are there special naming conventions the the xml file? And what happens with more than one xml file?

**Comment by matkoniecz** [comment]
> I also have to check what a pull request means (sorry ...).

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests http://oss-watch.ac.uk/resources/pullrequest

**Comment by simonpoole** [comment]
> Indeed, you could use nearly the same styling as a cliff also on retaining walls (perhaps only another color or smaller triangles) ... in JOSM it looks very similar.
> 
> I am also missing a simple thing (perhaps too simple to mention it) in the tutorial: what is is the target path/folder for the xml file? Simply the Vespucci folder in the internal memory? And are there special naming conventions the the xml file? And what happens with more than one xml file?

Currently it isn't possible to have two different colors outside of using casing, which I suppose probably works for patterns too.

The patterns have a version for the left and right side of the center line, so you can simply use what is appropriate for the semantics of the style.

The files currently should be in the Vespucci folder and named *-profile.xml you can have any number of them (need to have different names in the config itself though).

**Comment by jajajaneeneenee** [comment]
Hello!
Sorry for writing again in this closed ticket ...  

(Although it seems to be the right place, because it is ONE topic – rendering of ways whose direction is very relevant like natural=cliff, natural=coastline, waterway=weir, man_made=embankment AND barrier=retaining_walls – and perhaps others?. Which can be done with the triangle_right/triangle_left pathPattern.)

I finally found some time to try it out with custom data styling (@simonpoole: thank you for the missing information about the XML name *-profile.xml! This could be added to the tutorial page ...).

So I took the Color-round-profile style and added just one new line which did the trick for me, quite simply:

`<feature type="way" tags="barrier=retaining_wall" style="STROKE" cap="BUTT" join="MITER" widthFactor="1.5" color="ff878787" pathPattern="triangle_right" />`
(note sure if the widthFactor="1.5" makes sense, but it looks OK for me – and I am happy with it!)

Perhaps this could be added to the profiles ... I am too unsecure with GitHub to try it out with a pull request ...

I only got one slightly annoying problem by testing with different profile names:
I have now all these test profiles in the data style list in Vespucci and cannot remove them. Deleting the files in the Vespucci folder didn't help. Is there any way (except deleting the app data  in the Android app preferences perhaps)?

![data_style_list_vespucci](https://user-images.githubusercontent.com/48966999/90191588-73d53280-ddc1-11ea-95dd-74122322ee01.jpg)
