### ISSUE TITLE
OSM objects move relative to map background at different zoom levels

### ISSUE THREAD

**Issue by MikeParfitt** [MarcusWolschon/osmeditor4android#609]
## Vespucci Version
0.9.9r1300

## Device (Manufacturer and Model)
Samsung Galaxy Tab S2 ( MT-715 )

## Android Version 
7.0

## Behaviour/Symptoms
When zooming (in/out) OSM objects jump across the map background being displayed.  This allows incorrect positioning to be saved to the OSM database.

## Expected Behaviour
OSM objects should be displayed at a consistent location (relative to the map background) at all zoom levels

## How to recreate
Zoom in/out and pay attention to the exact relationship between the OSM objects and the map background

## Crash dump submitted (no or yes + date)
No, this happens without Vespucci crashing

## Any other potentially relevant information
Images a-c show the node whose name is ^ at one location, but images d-f show it at a different location.  Between these two zoom levels, the OSM objects skitter about relative to the map background.
![a](https://user-images.githubusercontent.com/29509220/30982641-e7dbbd08-a47f-11e7-84d0-362c8e5cc376.png)
![b](https://user-images.githubusercontent.com/29509220/30982646-eca7c2fa-a47f-11e7-8afe-8d74f24fa464.png)
![c](https://user-images.githubusercontent.com/29509220/30982660-f6a8dcc6-a47f-11e7-8a78-096e9731eee6.jpeg)
![d](https://user-images.githubusercontent.com/29509220/30982668-ff65345e-a47f-11e7-9f49-b4923c6386bd.jpeg)
![e](https://user-images.githubusercontent.com/29509220/30982682-09d4d962-a480-11e7-890f-2e5b674fc691.jpeg)
![f](https://user-images.githubusercontent.com/29509220/30982695-165102e2-a480-11e7-9fc3-b416a9bc2fcb.jpeg)

**Comment by simonpoole** [comment]
Are you sure this isn't simply a difference in the imagery between image 3 and 4? In any case we need to know the imagery selected to check.

Note on the side: there is a obvious bug visible in the images though, the scale should be directly under the menu bar, do have the same effect in landscape mode?

**Comment by MikeParfitt** [comment]
The offsets change for the same location between different instances of Vespucci.  If it were simply the differences between the image(s) used at the various levels of zoom, then the offsets would remain consistent between different instances.

I have attached today's equivalents of images 1 and 6, both use Mapbox Satellite as the map background, just as the originals, but this time cropped from landscape screenshots.  All are of the northern harbour wall of Penzance harbour.

The scale bug happens after a small amount of scrolling and zooming.  Initially, the scale is positioned as expected.

![a2](https://user-images.githubusercontent.com/29509220/31044129-63526120-a5c1-11e7-9941-77dc650ecb93.jpeg)
![f2](https://user-images.githubusercontent.com/29509220/31044132-6c662166-a5c1-11e7-9c35-46cd67244342.jpeg)

**Comment by simonpoole** [comment]
What are "different instances of Vespucci" in this context? Note that the imagery cache is persistent and will potentially contain old imagery if not cleared.

The reason I believe this may be the issue (besides the effect is not reproducible here) is because the high zoom images show OSM data that aligns very nicely with the imagery, which would indicate, that that was originally used to add the features, the lower zoom imagery however is consistent with what is currently available from mapbox.

In any case I would suggest clearly cache to test this hypothesis.

**Comment by MikeParfitt** [comment]
I terminate all apps after use, then restart them when next required.  Each restart puts that app back into memory.  This is what I mean by an instance of that app.  I realise that background services with no visible interface may persist for days, possibly weeks, as I no longer power off my tablet on a regular basis.

I launched Vespucci and used the Spanner icon, then selected the options :-
 . . . Flush background tile cache
 . . . Flush overlay tile cache
then terminated Vespucci.

Then I repeated the steps above, after which I relaunched Vespucci and the debug information is as follows :-

Vespucci 0.9.9r1300
Maximum avaliable memory 536870912
Total memory used 35716746
Tile Cache MAPBOX usage Size 4194304 of maximum 67108864 #entries 0
Tile Cache OSM_INSPECTOR-HIGHWAYS usage Size 4194304 of maximum 67108864 #entries 0
State file size 71170 last changed 2017-10-01 14:58:15
Bug state file size 248 last changed 2017-10-01 14:58:15
Relations (current/API): 8/0
Ways (current/API): 217/0
Nodes (current/Waynodes/API): 3065/3295/0
Available location providers
passive enabled true
gps enabled true
network enabled true

Tell me if I need to do anything more.

I then typed Penzance into the search box and accepted one of the Chyandor Cliff offerings near the harbour then scrolled the background (without zooming) so that the tip of the harbour wall was in the centre of the screen.  Then I used the arrows icon and selected the "Download current view" option.  The first image is what appeared.

![1](https://user-images.githubusercontent.com/29509220/31056153-49220ff8-a6c5-11e7-8713-6c1d33f75eed.png)

I then zoomed in really close and added a node at the tip of the harbour wall (image 2) then progressively zoomed back (images 3&4) while the OSM objects (including the node and its' name) all move north-west (today) relative to the Map Background, ending up close to the catamaran tied up against the habour wall.

![2](https://user-images.githubusercontent.com/29509220/31056159-633ca574-a6c5-11e7-8721-a369fd102174.png)
![3](https://user-images.githubusercontent.com/29509220/31056160-672590c4-a6c5-11e7-92f9-c97f32be47ce.png)
![4](https://user-images.githubusercontent.com/29509220/31056164-73101bd4-a6c5-11e7-9b51-9bbf8c77194d.png)

I realise that the amount of relative movement is not easy to see, so I have extracted and expanded the relevant pixels from image 4 so that they show approximately the same area as image 3.

![5](https://user-images.githubusercontent.com/29509220/31056174-8c41d782-a6c5-11e7-982c-be96b8f2a096.png)

Given that these drifts in registration between map background and OSM objects are random in size and direction, my guess would be that accuracy is being lost somewhere during the screen positioning calculation, leading to the same OSM objects being rendered at slightly different locations as you zoom in and out.  Of course, it could be that choosing which part(s) of the Map Background tile(s) to display is going slightly wrong while zooming, or even that both are affected.

Worst case, the problem may be specific to the OS on Samsung devices.

**Comment by simonpoole** [comment]
If you look at the imagery now, it would seem to be consistent between high and low zoom. Compare the new images to the first original three.

**Comment by MikeParfitt** [comment]
If you look at image 5 (of the set uploaded yesterday) the top of the ^ character (node name) has moved north-west across the harbour wall and has started to obscure the tip of the catamaran hull.  If you compare that with images 3 and 2 (of the set uploaded yesterday) they show the node exactly on the south-east tip of the harbour wall, with the tip of the name immediately below.

**Comment by simonpoole** [comment]
The point is that the position of your test node relative to the other OSM data hasn't changed in any of the series of images. 

The only "glitch" that is visible is in the -first- series of images and is that the background imagery of the 1st three images is aligned differently (to both the node you added and the existing OSM data) than in all other images, which supports the hypothesis that the background imagery in the first three images was aligned differently and now isn't (because it has been removed from the on device cache and fresh imagery seems to be consistent over all the relevant zoom levels). 

Now how that happened is a different question, but likely to do with imagery being realigned and you by coincidence  having some old tiles from a previous editing session or a similar process (the tiles may have themselves been cached at the original source at the time).

The other point that supports this, is that the outline there was added 4 years ago from OS data and not from imagery and the position of the node nearest to your test node http://www.openstreetmap.org/node/2445969153 has not been changed in those four years. Yes this does actually indicate that the imagery alignment is now worse than that at the time when the original tiles.

Note: the movement of the label at lower zoom levels is to be expected and has no bearing on the issue discussed.

**Comment by simonpoole** [comment]
No more input received
