### ISSUE TITLE
Java 1.7/7 souce code compatibility

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#630]
@MarcusWolschon @johnjohndoe 

Just a general heads up, I've (hopefully) kept the code Java 1.6/6 compatible up to now, however given that we are no longer supporting very old Android versions any more (pre 8), and that it is unlikely that somebody is stuck only with a 1.6/6 now, I think we can safely start using the supported features from 1.7/7 notably:

- [x] Empty angle brackets to avoid declaring type parameters twice
- [x] Multi-catch of exceptions
- [ ] try with resources

**Comment by simonpoole** [comment]
WIth the change here https://github.com/MarcusWolschon/osmeditor4android/commit/0c05e0071fccf0526aad03f02ef4e85708bdab73 I believe try with resources should be supported.

**Comment by johnjohndoe** [comment]
@simonpoole I recommend passing a higher order function instead of _try-with-resources_ to provide an "API" which does not leave the responsibility to the user of the class or method. Here is an [example](https://github.com/android/android-ktx/blob/master/src/main/java/androidx/core/content/Context.kt#L58) from the [Kotlin KTX library](https://github.com/android/android-ktx). Similar patterns are possible with Java, too.

**Comment by simonpoole** [comment]
Stale, closing.
