### ISSUE TITLE
template for filling station

### ISSUE THREAD

**Issue by olafhering** [MarcusWolschon/osmeditor4android#632]
The app from fdroid lacks a template to easily add a missing filling station (Tankstelle).

**Comment by simonpoole** [comment]
As the issue template say:

> When reporting issues, please use this template, if you are asking for an enhancement you can delete the text.
> 
> Please note that some components are maintained in upstream repositories and relevant issues should be reported there, these are specifically:
> 
>     background and overlay layers: https://github.com/osmlab/editor-layer-index
>     presets: https://github.com/simonpoole/beautified-JOSM-preset
>     opening hours user interface: https://github.com/simonpoole/OpeningHoursFragment
> 

You should be opening preset related issue in the corresponding repo., however there isn't actually an issue, as there is a corresponding preset which simply is not quite obviously named, due to the provenance from JOSM that now and then tends to use non-obvious terms which in turn get reflected in the translations, see http://simonpoole.github.io/beautified-JOSM-preset/#Car "Fuel" or in German "Treibstoff"

There is an open issue to address the root cause of this: that there is currently no support for synonyms https://github.com/simonpoole/beautified-JOSM-preset/issues/34
