### ISSUE TITLE
Extremely slow on Galaxy S5

### ISSUE THREAD

**Issue by M-Reimer** [MarcusWolschon/osmeditor4android#644]
## Vespucci Version
0.9.9r1321

## Device (Manufacturer and Model)
Samsung Galaxy S5

## Android Version 
Stock ROM (6.0.1)

## Behaviour/Symptoms
For me, Vespucci is **extremely** slow. Panning the map takes forever and opening a menu takes over a second. This way, editing is just impossible. Seems like I have to go back to my old way of mapping with GPS logger and JOSM on my laptop.

## Expected Behaviour
Vespucci should be at least as fast as required to do mapping without waiting for the app to react.

**Comment by simonpoole** [comment]
A stock S5 is regularly used for testing here with no problems (it is in fact likely one of the most used devices for Vespucci), 

You should check

- http://vespucci.io/tutorials/faq/#vespucci-is-getting-slower-and-slower
- size of the tile cache (I would recommend at least 100 MB)
- number of download threads (4 seems to work well on modern devices)

The soon to be released next version contains a improvement for tile downloading when you are rapidly zooming in and out by flushing pending requests, but it doesn't seem as if that is your issue.

**Comment by simonpoole** [comment]
PS: are you using a build from F-Droid?

**Comment by simonpoole** [comment]
As a general sanity test I quickly retested the upcoming release on a S5 and no problems at all (Vespucci does run on an original HTC Desire HD, running 2.3.5 now that is slow at times, but still usable). 

If there is no clear reason outside of what I've already listed (very slow SD card would perhaps be a further one as we try to stall tiles on removable media if possible)., I would suggest switching to the upcoming version as you may simply have a corrupted install (shouldn't happen but has).

**Comment by simonpoole** [comment]
ping @M-Reimer

**Comment by M-Reimer** [comment]
I did a few more tries and the issue is still only partially resolved.
It in fact has something to do with the amount of data loaded.
But the downloaded area has to be pretty small for Vespucci to run smooth.
I remember that Vespucci once had better performance on my phone, even with bigger areas.

**Comment by M-Reimer** [comment]
No I'm not using a build from F-Droid. Play-Store only.

**Comment by simonpoole** [comment]
Actually it should be at least a bit faster now since 0.9.8, than older versions,  but the way data is stored etc., hasn't really changed so there should be no fundamental difference. 

Could you check the debug page how many elements you have in storage? 10'000 nodes, multiple 100s of ways should work without issues (very long ways will impact performance).

It should be noted that drawing the touch areas has a substantial impact on panning/zooming performance (and there is not much that can be done about it because areas tend to vary a lot in object density). To use the example from above: if you zoom out so that 10'000 nodes are visible things are going to be slow when the screen is unlocked. 

Workarounds: 
- lock the screen
- zoom in more
- turn off the halos

**Comment by simonpoole** [comment]
I've been doing some work on this that has already shown some positive results.  That doesn't mean that it is lightning fast, but it is definitely better.

Among other things we now avoid drawing the node halos if they are too close together (it definitely looks better :-)).

**Comment by simonpoole** [comment]
No further input from op, given that there are no issues specific to S5s otherwise known, closing.
