### ISSUE TITLE
use lower zoom aerial images if high zoom is not available

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#652]
![gif-180101_184728](https://user-images.githubusercontent.com/899988/34469956-d1ba30c8-ef1f-11e7-9b5d-66aa0079d361.gif)

It is especially useful for offline editing without mobile data connection.

**Comment by simonpoole** [comment]
We do this in principle (use lower zoom tiles for higher zoom ones) however the logic currently doesn't take offline/inline into account nor does it do it over more than a limited number of zoom levels.

**Comment by matkoniecz** [comment]
> limited number of zoom levels

Is it possible to increase this number or remove limit?

In the worst case it will display low-quality aerial images rather than background and it can be improvement like in case like this where image was good enough to use (in this case - to trace waterway).

**Comment by simonpoole** [comment]
I've had a look at the code, the overzoom limit isn't the issue (it is currently limited to three, which means that a 256x256 tile maimum gets replaced by a 32x32 pixel image, doing more doesn't really make any sense).

The actual problem is that it only does this for tiles that are in the in-memory cache, not for those that are on "disk", except in the case of real over zoom (zooming more than the maximum zoom supported by the tile layer). This makes sense normally (with network connectivity) as using lower zoom tiles is just a stop gap visual effect, without network connectivity the situation is different.

This can clearly be fine tuned a bit more, however is a tiny bit complex as the whole tile on disk cache and downloading is provided by a service.

**Comment by matkoniecz** [comment]
> This makes sense normally (with network connectivity) as using lower zoom tiles is just a stop gap visual effect, without network connectivity the situation is different.

I think that even with network it is always (except heavy overzoom) better to show low-quality image rather than background.

**Comment by simonpoole** [comment]
There was actually a regression in 0.9.8 that impacted this, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/48b63584e8d5f05fcbef28aa22ee8727ce5e3222
