### ISSUE TITLE
Multi select and empty value

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#657]
Selecting three shop nodes and a building should show this entries

butcher (1)
bakery (2)
""(1) or 
(1) 

Right now i have
butcher (1)
bakery (2)

It is not obvious that there is one element with no such tag

Latest play beta

**Comment by simonpoole** [comment]
This is more a philosophical question than a technical one (changing the behaviour takes about a second). The problem is an element without a shop key, doesn't actually have a shop key, so why would we indicate the it has one with an empty value? The only reason we tend to think this is equivalent is because most editors (including vespucci) will delete keys with empty values.

**Comment by HolgerJeromin** [comment]
I edited the issue to the correct menu entry (no shop= is shown)

"" (1) looks ugly
<no shop value> (1)
Would probably not be the optimum either

Thanks for linking my other item

**Comment by simonpoole** [comment]
There is a more general argument to be made that an empty value should always be present in any case (I can argue both ways :-)).

**Comment by simonpoole** [comment]
I don't think this is still an issue since https://github.com/MarcusWolschon/osmeditor4android/issues/519 was fixed. The total number of elements is displayed so it is always obvious how many elements of the selection have the same value.
