### ISSUE TITLE
Feature request: Make it easier to change building=yes to building=residential

### ISSUE THREAD

**Issue by versat** [MarcusWolschon/osmeditor4android#669]
When i am outside i often want to quickly change building=yes to a specific value.
Often this is residential or a more specific residential value like apartments, house, ...
But all these values do not appear when deleting the value yes and a list of possible values is shown.
So i have to type the complete value every time, this is a bit annoying.
I guess the reason are the presets that differentiate between residential and other buildings or something like that and it is not a bug. But it would be really nice if all possible building values would be shown if the type of building is not known at all.
What do you think?

**Comment by simonpoole** [comment]
The underlying issue is that the building presets in the default preset don't have fixed building values, but a selection. This works well for new objects but not so for existing ones (applying a preset will only overwrite "fixed values" that is why you can't get rid of the building=yes). 

The alternative would be to create individual entries for at least the major in use building types (so for example one with the fixed value building=house), that is entirely possible, at the price of having quite a few more preset items to hunt through.

**Comment by versat** [comment]
I do not fully understand what you wrote, i am not familiar with the preset files (and the syntax).
Would it be possible to simply add "residential" to the list of default building types? When residential is chosen then it can be easily changed to more specific types i guess.
Sorry if this sounds "dumb" :) I really do not know what effects this could have.

**Comment by simonpoole** [comment]
Addressed in https://github.com/simonpoole/beautified-JOSM-preset/commit/8c26df85f0b39f016438e30734ac83926bcc80cf

This should fix most of the issues, I've merged the two general presets in to one and created fixed value ones for house, apartments, garage and industrial which are very often used. What still won't work (via preset) is changing one of house, apartments, garage and industrial to one of the values in the general preset.

**Comment by simonpoole** [comment]
@versat to explain a bit more: essentially there are two logically different kind of presets, such that have fixed values for the "major" (object defining) tags and those that offer a selection.

In principle the former is preferable (for example the highway presets are such), but when you have a large number of seldom used values, as you do with building=* it really makes more sense to offer a selection, however in the case of the building preset the list has become very long, so that is why I split it up. However as mentioned above this doesn't work well when modifying existing objects (well only the value you want to change to is in the same list as the current value).

**Comment by versat** [comment]
" house, apartments, garage and industrial which are very often used"
For me it is often not absolutely clear if it is a "house" (one household) or maybe "apartments" (two or even more households) and to not commit wrong types but be more specific than "building=yes" i choose "residential". Since you did not list it explicitly it is not available in this list then i guess?
Would it make sense to add "residential"?

**Comment by simonpoole** [comment]
It should be easier to set residential too now, however residential is a very unspecific tag and lots of people think it should be avoided.

**Comment by versat** [comment]
Ok. Thanks for all the great work!
