### ISSUE TITLE
"Report sucessfully submitted!" vague

### ISSUE THREAD

**Issue by goldfndr** [MarcusWolschon/osmeditor4android#679]
## Vespucci Version
10.1.0

## Download source
Google Play Store

## Device (Manufacturer and Model)
Motorola Moto G (2013, 1st generation, XT2018 Verizon)

## Android Version 
4.4.4, stock ROM with some Xposed modules

## Behaviour/Symptoms
Just by panning around the app a bit, I'm seeing "Report successfully submitted!" toasts. I have no idea what's being submitted or where it's going. I'm just hoping that I'm not unwittingly vandalizing any imagery offsets.

## Expected Behaviour
No toasts just from zooming/panning

## How to recreate
* enable location (GPS)
* set Map background to Digital Globe Premium Imagery (won't be visible) and Map overlay to None
* menu / Tools / Zoom to background layer extent
* pan/zoom around the map a bit
* observe "Report successfully submitted!" toasts (or, occasionally, "Report submission failed")

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
Earlier today I was using version 10.0.5 and editing, but my phone's battery died before I saved anything. I upgraded to 10.1.0 after charging the battery a bit, without running 10.0.5 again. The note in the help about "The saved editing state file format has changed, please complete any edits before upgrading." should probably go in the Play Store's "What's New" section; if Vespucci keeps a draft state file then maybe the edits I performed didn't need to be lost.

**Comment by simonpoole** [comment]
What is happening is that the background process that download tiles can't open the sqlite database that it uses for storage, likely because the file is corrupted in one way or the other (and it is submitting error reports for that).

The only way to fix that is to clear the data for the app, or if you have root access on your device you can simply remove the database file,. The location is typically (on removable storage or on hte internal "sdcard") in Android/data/de.blau.android/files/databases/osmaptilefscache_db.db and the accompanying journal file.

As to the saved edits: we will add a warning. We do keep a backup copy of the edits, the problem in this case is really that the format of that has changed.

**Comment by HolgerJeromin** [comment]
> As to the saved edits: we will add a warning. We do keep a backup copy of the edits, the problem in this case is really that the format of that has changed.

Many (I hope) phones are updating on wifi automatically. Most people will never see a warning or have no possibility to upload before an upgrade is installed.

**Comment by simonpoole** [comment]
@HolgerJeromin so we never change the format?

**Comment by HolgerJeromin** [comment]
I understand the problem. 
Programming a migration for a database which is in most cases empty is not fun either.

**Comment by goldfndr** [comment]
Could you change the string from "Report" to "Bug report" or "Error report"? That would make it somewhat clearer.

**Comment by simonpoole** [comment]
@goldfndr the message likely could be changed somewhere in the ACRA configuration, but https://github.com/MarcusWolschon/osmeditor4android/commit/14a43ca3d3a14b61b478e7ee5a674ddecb2d68bf should improve the messaging without that (and stop the submitting of reports for such cases as they are local device issues and not actual code problems).
