### ISSUE TITLE
add Geoportal 2: ISOK hillshade imagery

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#692]
It is extremely useful layer for editing in Poland (extreme detail - not only objects like streams and peaks are visible, it is possible to map paths in forests based on a terrain shape)

It is in JOSM - https://josm.openstreetmap.de/wiki/Maps

may require equivalent of https://josm.openstreetmap.de/ticket/7427

**Comment by simonpoole** [comment]
Is the layer in https://github.com/osmlab/editor-layer-index? That is where the issue should be opened-

If it supports EPSG:4326 or EPSG:3857 it technically should work without issues in Vespucci, it is however very unlikely that we will add generic re-projection support. If there is a real need for the layers and they don't support either of the supported projections, simply run a mapproxy instance somewhere or get somebody to run one for you (and then add that to the editor-layer-index). It makes far more sense to reproject once for all users instead of burning cycles on mobile devices doing the same thing again and again.

**Comment by matkoniecz** [comment]
Sorry for misfiling, I opened https://github.com/osmlab/editor-layer-index/issues/476
