### ISSUE TITLE
It seems that Vespucci caches also failed responses

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#726]
## Vespucci Version
Vespucci 11.0.0-5

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
After period of poor connection and starting to receive good mobile internet tiles are not downloading.

After deleting cache tiles are downloading normally.

## Expected Behaviour
Tile are downloading after restoring connection

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information

It may be misinterpretation as flushing cache takes a long time

**Comment by simonpoole** [comment]
Yes we do cache actual errors, but not network errors as far as possible. Not sure if this is easily fixable.

**Comment by simonpoole** [comment]
Do you see this particularly often with a specific layer? 

FYI the (read) timeout is currently 5 seconds which assuming a tile size of 15-20kB should still be doable with a GPRS or GSM connection, you may need to lower the number of download threads from the standard of 4 down to 1 or 2 though. It is naturally clear that a tile per couple of seconds is very very slow (particularly because on current hi-res phones you may need a -lot- of tiles for the whole screen).

The -other- workaround for bad connectivity is to use a mbtiles container holding the tiles.

**Comment by matkoniecz** [comment]
> Do you see this particularly often with a specific layer?

Geoportal (though I use just this layer for 90%+ of time)

**Comment by simonpoole** [comment]
Closing, don't think there is anything currently actionable here.
