### ISSUE TITLE
Apply default value only once in tag editor

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#748]
Perhaps related like #571 but valid with all my keyboards (google, swiftkey, MessagEase)
Vespucci 11.0.0-10 on Fairphone 2 with Android 6.

- create new node/way
- select `building=appartment` from preset
- place cursor behind `appartment`
- delete all chars with backspace till we have only `building=a` => every thing normal
- delete `a` with backspace
=>
cursor is still on the front position of the text input, but now we have `building=yes`
typing `a` leads to `building=ayes`

**Comment by simonpoole** [comment]
When empty, the field simply gets filled with "yes". That is because once you've deleted the apartments value (assuming you meant "apartments") and the field is empty it matches with the generic "building" preset which has a default value of "yes". Double clicking the value field should get you the dropdown and allows selection of a different value. 

The current behaviour is in any case problematic since one would expect the default value not to get in the way of adding an arbitrary value, which it does now.

**Comment by simonpoole** [comment]
Addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/fb1d214f2578e6f1b93f346712389b2d3a698594 and https://github.com/MarcusWolschon/osmeditor4android/commit/21d51e77d881ebfbc4d670d336a2502c087a84f6
