### ISSUE TITLE
Unable edit value of tag with "maxspeed" key

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#754]
## Vespucci Version
11.0.0

## Download source
Google Play

## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)

## Android Version 
6.0.1

## How to recreate
1. Select way and go to properties
2. Go to Details tab
3. Type "maxspeed" or "maxspeed:backward" or something containing speed value
4. Try to set value, the "Vespucci crashed" dialog appears (the app actually doesn't crash)

I'm not able edit existing values as well.

## Crash dump submitted (no or yes + date)
9.7.2018 23:00 GMT+02:00 (CET)

![gif](https://user-images.githubusercontent.com/11516259/42476003-c4bfe920-83cc-11e8-98d5-947c830f7aa8.gif)

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/96f65004a4181cd6389bc9d3887fd96a011dfa3b Note: you should still be able to add a maxspeed value through the form interface (note the underlying issue was that there are no suggested maxspeed values for your location, see http://vespucci.io/help/en/11.0.0%20Release%20notes/#improved-country-specific-tagging

**Comment by simonpoole** [comment]
11.0.1 that is rolling out now has the fix.
