### ISSUE TITLE
"operator" not appearing as available tag for amenity=bicycle_parking, despite that it is the preset

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#779]
"operator" is one of fields in bicycle parking preset so I expect it to appear od adding key in Details mode.

## Vespucci Version
11.0.4

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms

- Create node.
- Add "amenity=bicycle_parking" tag
- start creating new key, type `op`
- `operator:type` and `opening_hours` keys are offered.

## Expected Behaviour
`operator` key is offered among other.

## How to recreate
Enable Thunderforest OpenCycleMap tiles.

## Crash dump submitted (no or yes + date)
No

**Comment by simonpoole** [comment]
It is not quite so simple in the details form the empty lines don't have a preset associated with them and the mechanism that returns possible keys from the "best" preset wont work. 

What is a problem, but IMHO was never different is that it doesn't simply have an autocomplete adapter that contains all "known" keys, that is because text fields currently don't get added to the internal data structure (because they don't have values). This is fixable but wont be backported to 11.0.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/e308adb277fc4e9d2a4ddd1e9191945bab60d16a
