### ISSUE TITLE
Same versionCode for latest release

### ISSUE THREAD

**Issue by roptat** [MarcusWolschon/osmeditor4android#791]
Hi,

I'm trying to take care of Vespucci on the fdroid side, and while trying to update to the latest release (11.1.3.0), I found that the versionCode was still 704, as with the previous release, which prevents me from packaging the newer version.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/releases/tag/11.1.4.0 

Note you shouldn't be distributing 11.1.2 as there is a serious regression for older deives which is the reason it was removed essentially immediately.

**Comment by roptat** [comment]
Thank you, it should be updated in fdroid shortly :)

**Comment by simonpoole** [comment]
I was just going to point out that because of the play store access changes on November 1st the build process will be changing and we will be producing 2 APKs see https://github.com/MarcusWolschon/osmeditor4android/issues/773 for more information. The directory the "normal" APK lands in will change to  `/osmeditor4android/build/outputs/apk/current/release` and at least this will have to be changed in the f-droid build process. Any further input on https://github.com/MarcusWolschon/osmeditor4android/issues/773 is welcome.
