### ISSUE TITLE
Make new "add something" button more noticeable as user tries to add things in the old way

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#812]
Long-press that would start creation of new object with old style editing may cause new "add something" button to change colour/pulse/become bigger/arrow poiting to a new button to make it more discoverable.

That would be useful in making new interface easier to get for users - both current ones and new in the future.

**Comment by matkoniecz** [comment]
BTW, I would expect that this new interface will be better for newbies as it is self-explonatory.

It may require more clicking but it is not a significant problem as smartphones ate anyway unsuitable for edits where this would be a big issue

**Comment by matkoniecz** [comment]
I actually forgot about tablets (but at least I was careful enough to restrict my comment to smartphones).

**Comment by HolgerJeromin** [comment]
How do i add a node in a way with the new interface? 
Like an entrance in a building.

**Comment by simonpoole** [comment]
@HolgerJeromin there is actually documentation :-): https://github.com/MarcusWolschon/osmeditor4android/blob/master/documentation/docs/help/en/Simple%20actions.md

Since the node is selected after adding the tags, you simply need to tap the "merge" button (which will only be visible if there is something the node can be merged with).  Note there's a small issue in the current beta that the property editor will be started on the node after merging, that is already fixed as can be seen below.

Or you can turn the simple mode off.

![add_entrance](https://user-images.githubusercontent.com/1011860/49788179-efe3c100-fd28-11e8-9309-da9e72aa4e99.gif)

**Comment by simonpoole** [comment]
While not quite as luxurious as suggested https://github.com/MarcusWolschon/osmeditor4android/commit/7130e5c3be1b1e1af4066c7c226c7f63b0926677 shows a toast if you long press in simple mode.
