### ISSUE TITLE
Undo is not properly undoing edits in partially downloaded area

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#827]
Description:
---

To reproduce: download way that has one node outside downloaded area, delete all nodes in downloaded area, undo. Way is not recreated or at least it is not reappearing.

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>12.0.0.4</td></tr>
<tr><td>App version code</td><td>902</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
The downloaded area shouldn't affect the undo process (outside of you not being able to delete the node outside of the area). In any case I can't recreate this locally, how did you try to undo?

**Comment by simonpoole** [comment]
Yes this wasn't actually the undo not working, the problem was that the cached bounding box for the way was not invalidated on restore and so remaining at what it was immediately before the deletion, with the result that if the piece that was initially restored was moved out of the view box it "disappeared".

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/c7056502595e532cc1181197a01aa590090837ff 

Thanks for the report.
