### ISSUE TITLE
Way action - align nodes in circle

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#828]
Like the equivalent command in JOSM - a Way Selected action to arrange the nodes of the way in the closest possible circle segment. Indispensable for circles and curves.

**Comment by simonpoole** [comment]
This currently exists for closed ways only.

**Comment by Discostu36** [comment]
> This currently exists for closed ways only.

Even for closed ways its not as good as JOSM's feature because no additional nodes are added to make the shape rounder.

**Comment by simonpoole** [comment]
Last time I checked the function was named "Arrange in circle" not "Arrange in circle and arbitrarily add some more nodes".

**Comment by Discostu36** [comment]
Well, it's always arbitrarily to make a circle in OSM because real circles don't consist of nodes. If I want to create a circle with Vespucci it takes quite a long time and in the end still doesn't look like a circle (see [this example that I created today](https://www.openstreetmap.org/way/756455443)). It would be really helpful if there was a feature that converts a closed way of 3 to 4 nodes into a nice circle (20 nodes or whatever).

**Comment by HolgerJeromin** [comment]
It looks odd, because the nodes have different distance on the circle. Perhaps we need an option to "arrange node evenly". So we can call this new function and after that call "arrange in circle" (perhaps with a few iterations) and have a nice circle.

**Comment by jajajaneeneenee** [comment]
I was also already fighting several times with the function "Arrange in circle" ... it's good to have it (better than nothing), but it really could be smarter, more like in JOSM. It really takes a long time (and patience) to create a nice circle in Vespucci ...

**Comment by contrapunctus-1** [comment]
@simonpoole IIRC, JOSM's version doesn't add nodes new nodes (there is probably a different action for that), but does evenly distribute the existing ones (but not moving nodes shared with other ways). That would be handy to include in Vespucci's "align nodes in circle" action.

However, this request is for making the "align nodes in circle" operation work on open ways too...

**Comment by jajajaneeneenee** [comment]
OK ... I just compared it with the action in JOSM to create a clean circle or circle segment. @simonpoole: perhaps you could also try it out ...

What JOSM is doing is to create a **regular geometry** (e.g. a regular pentagon with 5 nodes, if it is a closed way, see [https://en.wikipedia.org/wiki/Pentagon#Regular_pentagons](https://en.wikipedia.org/wiki/Pentagon#Regular_pentagons) or something like a "regular half circle" if it is not a closed way of 5 nodes or if you select 5 nodes of a closed or open way with more than 5 nodes). And JOSM also gives an error if you select the 3 nodes of a closed way with 3 nodes  ... (but it could also create a regular triangle ...).

Vespucci perhaps arranges the nodes on a circle, which might be correct, but usually not very useful ... What you often get is a strange polygon. I would say, the method of JOSM is the better choice ... and the result is what a user would expect more than the other one.

I would appreciate if Vespucci would do it like JOSM, it's also easier for the brain when basic things like that work in the same way ...

**Comment by jajajaneeneenee** [comment]
I forgot:
JOSM has another command for circles (additionally to "Align Nodes in Circle" – shortcut = O): 

"Create Circle" (shortcut Shift-O). I guess this is what @Discostu36 means in https://github.com/MarcusWolschon/osmeditor4android/issues/828#issuecomment-567226459:

> Well, it's always arbitrarily to make a circle in OSM because real circles don't consist of nodes. If I want to create a circle with Vespucci it takes quite a long time and in the end still doesn't look like a circle (see [this example that I created today](https://www.openstreetmap.org/way/756455443)). It would be really helpful if there was a feature that converts a closed way of 3 to 4 nodes into a nice circle (20 nodes or whatever).

With this command JOSM converts a way with 2 oder 3 nodes (closed or not closed) to a nice circle with an amount of nodes depending on the size of the circle (I think at least 6 nodes for a very small one, or 20, 50, 100 or much more for larger ones ... I'm not sure about the rule behind the amount of nodes, perhaps a certain target value for the angle between 2 segments of the "circle polygon"?).

Of course, this is also a very useful (and simple!) tool ....

**Comment by jidanni** [comment]
(Indeed, currently it seems to make various "flat tire" shapes.)

**Comment by jidanni** [comment]
I was just thinking, just like when we want a tire for a car, we don't just start making it out of scratch and then trying to make it round. We instead just go to the store and buy one. 

Therefore instead of even making a single node, the user could just select from some pre-made circles.

Just like when we go into the the tire store and select the size that's right for us.

Well anyway the idea is for the user not to make any nodes on the map, but instead invoke some professional circle placer, that has size sliders... or maybe just fits to where his fingers stretch it to.

(And continuing our tire example, if there's some kind of thickness required for some double ring, then he would just turn on the "air switch" slider, and the thing would inflate. Just some fun new approaches here.)

**Comment by dmlls** [comment]
Sorry for commenting in a closed issue, but I don't think this is solved as of v22.0.4.0?

Here goes an example before and after arranging in circle:

| Before | After |
|---|---|
| ![Before](https://github.com/user-attachments/assets/51161d22-c1dd-4d36-89eb-6c9e4b8f3670) | ![After](https://github.com/user-attachments/assets/c7170867-bbd1-471b-b3dc-d08054f12d75) |

**Comment by simonpoole** [comment]
@dmlls you are not indicating a size of the object so it is not possible to tell if this is what should be expected (probably yes, see below) or something else.

Most likely it is a small object and you are simply seeing the results of the current settings https://vespucci.io/help/en/Advanced%20preferences/#minimum-number-of-nodes-in-circle you can naturally tweak those.

**Comment by dmlls** [comment]
@simonpoole another try, this time with a generous size (≈10 m radius) and number of nodes (15).

| Before | After |
|---|---|
| ![Before](https://github.com/user-attachments/assets/e06b7e23-5f39-494f-90c7-144f7dd39dbd) | ![After](https://github.com/user-attachments/assets/f23926f0-869f-42a7-ae37-41ca710ad636) |

The circle is still made of irregular segments. Is there any technical limitation to having a true circle in which all the segments have equal length (as in other popular editors)? Or is the current behavior by design? I cannot think of any situation where I'd want to end up with a botched circle but maybe there are?

I get that Vespucci was always kind of a power-user app, but having to go to a submenu in advanced settings to get anywhere close to a basic shape such a circle seems a bit much?

I don't mean any offense, just trying to provide constructive feedback from a user's perspective.

**Comment by simonpoole** [comment]
In all cases the vertices are on a circle, we simply try to retain the original vertex locations as far as possible. If you want circles with equal spaced nodes (not part of the definition of a circle) then I would suggest opening a feature request.

**Comment by dmlls** [comment]
@simonpoole thanks for the reply. I don't think is a matter of more features, but rather a current feature with unexpected behavior to users (as evidenced in this issue and #1860).

Nevertheless, I'm totally fine with using other editors for this, it's already amazing how far I can get with Vespucci and I'm very grateful for that!
