### ISSUE TITLE
Squaring multiple buildings that share nodes doesn't work

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#847]
## Vespucci Version

12.0.0

## Download source

Not sure, F-Droid maybe...

## Device (Manufacturer and Model)

Fairphone 2

## Android Version 

7.1.2

## Behaviour/Symptoms

Draw an approximate square, tag it as building, reuse two nodes to draw another square and tag it as building too. That gives us two separate buildings sharing a wall. Now use the squaring tool. Not both buildings will be squared (and have the same directions compared to each other).

## Expected Behaviour

The two buildings should both be squared and have the same directions, similar to JOSM.

## How to recreate

See above.

## Crash dump submitted (no or yes + date)

No.

**Comment by simonpoole** [comment]
I think this may depend on the definition of "doesn't work". 

There are two issues which you may be seeing:
* currently we don't consider angles that differ from 90° or 180° more than +-10°, so the objects should typically be nearly square or straight.
* you can construct situations with connected buildings that will not converge (or only badly) within the maximum number of iterations we currently allow.

Note we use the original P1 algorithm for squaring, not what JOSM does, as the later tends to show degenerate behaviour in some cases instead of simply not doing anything.

In any case there is already an open issue on refactoring the relevant code, I'll close here and track this specific problem there https://github.com/MarcusWolschon/osmeditor4android/issues/832
