### ISSUE TITLE
Improvements for opening files

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#898]
I'd like to suggest the following improvements in this aspect -
1. Vespucci should be suggested for opening GPX files, when one tries to do so from a file manager
2. When trying to select a GPX file to import, Vespucci seems unable to access the external storage.

**Comment by simonpoole** [comment]
This looks like a bug in/with the (3rd-party) file selector , might be Android version dependent.

**Comment by simonpoole** [comment]
Seems as if there is no way around this outside of using the system file picker and the SAF on >= 4.4 devices (which I didn't originally do so that we could have a consistent UI over all supported versions).

Note on the side, seems as if google is working on completely disabling access via file URIs for Android 10.

**Comment by simonpoole** [comment]
SAF for opening files https://github.com/MarcusWolschon/osmeditor4android/commit/aed39ad91603829d1025b36f8ce6f8c7bd593d52

Support intents for GPX and geojson https://github.com/MarcusWolschon/osmeditor4android/commit/241fddff5894052b723e2d8d78e7fa465166e405
