### ISSUE TITLE
make initial view more local

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#899]
Description:
---

After starting the app, as inital view we currently see the whole globe. But in the vast majority of cases, I start vespucci to edit OSM data which nearly only makes sense on high zoom levels when you see the details - hence I've to tap many times the zoom buttons until I see a much more local map region. Please start with maybe 100-500m around my position or remember last used zoom level or offer a setting for this.

Extra info:
---
<table>
<tr><td>OSM display name</td><td>schoschi</td></tr>
</table>

**Comment by simonpoole** [comment]
You should only get the "world view" on:

- initial startup after the first install
- when starting after updates that changed the stored data format, or the save file is corrupted (which shouldn't happen).

in all other cases the screen should be set to the last area viewed/edited. With other words: we are already doing what you are suggesting. If you are getting the fully zoomed out view in other cases, could you pls detail what events led to that happening.

Outside of the above: if you have a GPS fix of any kind you can simply select "Go to current location" from the GPS/GNSS menu, which will zoom in to the current position.

**Comment by georg-d** [comment]
Hi Simon, the behavior as you describe it is mostly what I would like to experience - only addendum is, I'd prefer not to start in world view at all but instead with a zoom level that is reasonable for OSM editing on a smartphone. That would completely avoid this kind of issue. Another way to ease this: Long press of + / - zoom icons pops up a slider - Locus behaves like this and it proved to be well usable.

My experience: I use the app, I press back button to exit the app and confirm, and finally I mostly remove it from most recently used apps list by swiping it left out of the screen. Starting it again (seconds or days later) usually shows the world map. It's no issue with general data loss as notes, OSM data, background imagery etc are still present. Switching on GPS and checking "show GPS position" (literally translated from German) in Vespucci shows the arrowhead reliably, but pressing "go to current location" does only sometimes zoom in. Samsung Galaxy S7 running stock Android 8.0

Best regards, Georg

**Comment by simonpoole** [comment]
Weird. As I can do all of above on a S7 with stock 8.0 and it simply works. While I don't see how it could have an influence some a/b testing with not removing the app from the mru list would be good.

The next time you restart, and you are not shown the last edited position, could you go to the debug information screen and send the debug info, before you do anything else? It is likely not going to give any magic insight but it is probably still worth the trouble.

A further note: an alternative method to get to the last edited region is to zoom to the extent of the downloaded data in the layer dialog. But as said, normally you should simply get zoomed to the last edited location.

**Comment by georg-d** [comment]
Hi Simon, I just sent the debug info with note referencing this issue.
As zooming in automatically does not work for me and manually is not possible in a quick way: Is there any use case for an OSM editor to start in zoom showing the whole world? I don't see any and if also not, why not _always_ start in zoom level around 20, so that neither automatic not manual zooming is required? 
Best regards, Georg

**Comment by simonpoole** [comment]
As I've already pointed out, you are not seeing the normal behaviour, so we need to get to the bottom of the issue on your device to find out what is causing that. Arguing that it should behave as it already does in normal circumstances is not going to help with that.

**Comment by simonpoole** [comment]
> Hi Simon, I just sent the debug info with note referencing this issue.

Could you do that one more time, we had some issues with the system receiving the information which makes it difficult to analyse it, what I did notice that there was a number of reports from a S7 showing a stack overflow when saving state, die you experience any other issues during use?

**Comment by georg-d** [comment]
Hi Simon, at the moment, I cannot reproduce what happened hundreds of times - now, Vespucci starts zoomed into the last or pre-last area I was. Weird. I'll keep you updated in case the issue re-occours.

**Comment by georg-d** [comment]
It happened again; I uploaded debug info with reference to this issue 899.

**Comment by simonpoole** [comment]
Is the time on your device off? I found the dump but it was dated to the 17th.  

Anyway it doesn't show anything abnormal, that is the good news, the bad news is that we still don't know what is causing the issue. 

Does your typical work flow contain any deviation from:

- manually or automatically download data
- edit data
.....
- upload 

and repeat.

**Comment by matkoniecz** [comment]
> initial startup after the first install

Is there some reason why in such case local area cannot be shown?

Especially initial startup after the first install has very confusing screen with space for manual coordinate input, ability to search for location by name (with dropdown for Photon/Nominatim).

I think it would benefit from being simplified.

**Comment by georg-d** [comment]
To all who are also still experiencing this: You can zoom in _very quickly_ from world to a reasonable zoom level for editing by tap, tap & hold & swipe down.

@simonpoole The device time is usually correct, but maybe I did not upload quickly – every now & then, I'm offline for some days, for example because I hike in the mountains and there is no mobile internet, or because it is costly due to romaing fees in Switzerland. And my usual workflow differs from what you listed, especially, I switch between layers, I undo (mostly due to lower accurracy of interaction with the device while it shakes during walking), and I switch between apps, i.e. I load OSM data into Vespucci, do some editing, then bring other apps like navigation to foreground, later bring Vespucci to foreground to edit again,... and finally I upload. While I disabled the aggressive background app cleanup features, the time between first edit and upload can be days, thus, Vespucci might be "too much" in the background and loose all resources.
