### ISSUE TITLE
Crash when trying to access "Presets" list in settings

### ISSUE THREAD

**Issue by nw520** [MarcusWolschon/osmeditor4android#912]
## Vespucci Version
13.0.2

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei P20 lite

## Android Version 
8.0.0 running EMUI

## Behaviour/Symptoms
App crashes and automatically restarts into map view once pressing on "Presets" menu item in Settings

## Expected Behaviour
Display "Presets" list

## How to recreate
_see Behaviour_

## Crash dump submitted (no or yes + date)
No. Don't know where to find one since app automatically restarts

## Any other potentially relevant information
I've added custom presets

**Comment by simonpoole** [comment]
> ## Crash dump submitted (no or yes + date)
> 
> No. Don't know where to find one since app automatically restarts

After a crash you should automatically be asked if you want to submit one, can you check if in ~~~Advanced preferences / Miscellaneous / Report app crashes~~~ is turned on?

Without the dump it is going to be a bit difficult to do this, I assume, since you added a custom Preset, if was previously working?

**Comment by simonpoole** [comment]
Ah do you have the light theme turned off? Because there's a theme issue that potentially causes a crash that was fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/8b72c64de4a1a79830b5aa5b4cfd724c773065b3 the corresponding build is available on F-Droid, but hasn't turned up on googles play store.

Workaround till the new build is installed: enable the light theme (in principle you just need to do this when you are accessing the presets).

**Comment by nw520** [comment]
> Without the dump it is going to be a bit difficult to do this

You're right. I had the option to report app crashes disabled. Sorry for that, I assumed that Vespucci might _automatically_ submit a bug report without asking me beforehand. Obviously wrong so I just enabled the option and sent a report.

> Ah do you have the light theme turned off

Ah, yes, that was the problem. Enabling the light theme fixed this problem. Sorry for reporting an already fixed bug. Welp, this might be a good nudge to switch to the F-Droid version though. :wink:

**Comment by simonpoole** [comment]
@nw520 13.04 should be available from the play store now. While currently the F-Droid version tends to be available faster, it has in the past most of the time been the other way around, the real downside is that beta releases are only available (at least properly signed) from googles play store.
