### ISSUE TITLE
go back to last edit

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#936]
Description:
---

I frequently edit very far away from my current location. Unfortunately, sometimes I accidentally hit the "current location" button,  and move away from where I'm editing. It then always a pain to find my way back to where I was. Would it be possible to add a "back to last edit" or "back to download area" button? I would find this hugely useful.  Let me take this opportunity to thank you for this great app, I find it of outstanding quality. Best wishes, Gerald

Device info:
---
<table>
<tr><td>App version</td><td>13.0.6.0</td></tr>
<tr><td>App version code</td><td>1109</td></tr>
<tr><td>Android build version</td><td>e472b</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPY29.105-57</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>channel</td></tr>
<tr><td>Device model</td><td>moto g(7) play</td></tr>
<tr><td>Device product name</td><td>channel</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Gerald Weber</td></tr>
</table>

**Comment by simonpoole** [comment]
We currently don't really have the necessary information available (while we keep a list of bounding boxes, they are merged when possible), and would need to add a "last bounding box in which was actually edited" to the save edit state. But obviously doable.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/cd55946028315f861404a065fe4b97d7957da1ad

This creates a bounding box of the last undo checkpoint, which implies
- if an object has been moved the previous position will be zoomed to (this could be fixed by creating an union with the bounding boxes of the moved objects, but that could be impractically large), 
- if an edit has been undone it will not be considered (this could be addressed by providing a per checkpoint go to function in the undo dialog).
