### ISSUE TITLE
Special keyboards not showing if tag is not part of preset

### ISSUE THREAD

**Issue by TimMagee** [MarcusWolschon/osmeditor4android#953]
## Vespucci Version
13.1.0

## Download source
F-Droid

## Device (Manufacturer and Model)
Samsung Galaxy S5

## Android Version 
LineageOS for MicroG 16.0 (Android Pie)

## Behaviour/Symptoms
When adding a phone number, the "phone keyboard" does not show up if the field is not part of the currently used preset.

## Expected Behaviour
The "phone keyboard" always shows for tags of type "phone" even if the tag is not part of the currently used preset.

## How to recreate
1. Add a  node.
2. Directly edit the tags.
3. Choose the `contact:` preset. 
4. Note that the fields show up under "Additional Properties".
5. Click to add phone number under contact:phone
6. At this point, the regular text-entry keyboard will appear rather than the phone number-entry keyboard.

## Crash dump submitted (no or yes + date)
None needed.

**Comment by simonpoole** [comment]
The reason why you are running in to this issue is because in the default preset only the "conventional"  contact auxiliary preset is linked to the relevant presets and not the one for the namespaced "contact:" scheme. 

Tags that can't be assigned to a specific preset item don't have properties (because those are defined in the preset) and so we can't know that contact:phone is a phone number. The twist is that we will match tags from auxiliary presets (aka presets that don't actually define "objects" in their own right), if they are a linked preset for the matching preset. Sounds complicated but irl works as expected (as you can test by applying the non-namespaced contact preset).

This is obviously fixable, but from the above you can see that it is a preset issue and not directly a Vespucci problem.

**Comment by simonpoole** [comment]
Fixed in preset repo
