### ISSUE TITLE
The text written in the search bar disappears in PropertyEditor activity after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [MarcusWolschon/osmeditor4android#962]
When I change the orientation of the device screen, the text written in the search bar disappears
![2019-07-20 21-46-28_before](https://user-images.githubusercontent.com/53469180/62285282-97973600-b455-11e9-8b96-1dc43dcfd878.png)
![2019-07-20 21-46-28_after](https://user-images.githubusercontent.com/53469180/62285283-97973600-b455-11e9-884d-a84b00ee6137.png)

**Comment by simonpoole** [comment]
This is an actual defect (not that allowing automatic screen rotation in the app is a good idea).

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/2b55fae4db719412afc19acc1841c12c93ed6827#diff-aec4f1717fd4e60bfeb7cbf20b4f8563 (for some reason the was an issue with WS in the commit). 

Note that the search result fragment dialog contents currently deliberately get zapped on configuration changes, as saving the search results would typically increase that saved state over the 1MB Android transaction size limit (resulting in a crash of the whole activity). It is intended to address the issue in the context of implementing incremental search (see https://github.com/MarcusWolschon/osmeditor4android/issues/697).
