### ISSUE TITLE
Fully zoomed out issues

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#965]
- [x] after rotating the screen back and forward a number of times the map fitting is off and there is empty space at the top of the map.
- [ ] the zoom out buttons margins are off when disabled and then the screen is rotated.

**Comment by simonpoole** [comment]
The map fitting issue doesn't seem to be reproducible.

**Comment by aarewhyan** [comment]
This issue also persists for zoom in button when it gets disabled (at max zoom in)
The core of the problem is when setEnable(boolean) gets true for one button and false for the other it creates the neceassry context and attributes for one and ignores such things for the other, as given in the constructor FloatingActionButton()-

```
  TypedArray a = ThemeEnforcement.obtainStyledAttributes(context, attrs, R.styleable.FloatingActionButton, defStyleAttr, DEF_STYLE_RES);

  setEnabled(a.getBoolean(R.styleable.FloatingActionButton_android_enabled, true));
```
The normal course of action would be to create one setDisable() interface or let setEnable(false) to only remove the clickability aspect while retaining every other aspect of FAB intact.

A workaround here would be to keep setEnable(true) always. As the map is limited, the zooming functionality will stop working at its max level
