### ISSUE TITLE
Rotate Tool Buggy

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#982]
Description:
---

(Pixel 3A XL) I was using the Rotate Tool and while I was adjusting the Way to turn it 180 degrees the Way would disappear. So, I kept undoing back to before I chose the tool and eventually I got the result I was looking for, but now the Way didn't have any Nodes anymore. I ended up giving up using the Rotate Tool and drew the shape I wanted to create. Later when I tried to upload the changes I was getting an API error over and over again that kept me from uploading. I went through the log (before you upload) and found that there was some hidden shapes that disappeared when I was trying to rotate. So I removed the hidden shape and now I was able to upload the changes, but now the map has disappeared and I'm getting a black screen (I can still interact with the selections at the bottom of the screen). I'm probably going to uninstall and reinstall the app to fix this problem, but wanted you to know.

Device info:
---
<table>
<tr><td>App version</td><td>13.1.6.0</td></tr>
<tr><td>App version code</td><td>1209</td></tr>
<tr><td>Android build version</td><td>5674421</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PQ3B.190801.002</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>bonito</td></tr>
<tr><td>Device model</td><td>Pixel 3a XL</td></tr>
<tr><td>Device product name</td><td>bonito</td></tr>
<tr><td>Device hardware name</td><td>bonito</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>MapRogers</td></tr>
</table>

**Comment by simonpoole** [comment]
Could you point to the specific way? There are currently no known issues with rotating so there must be something special with the situation that triggers a bug.

**Comment by simonpoole** [comment]
If there is a data issue (as in the saved data seems to be corrupt) the best action is to save the contents as an OSC file and then re-download the area. We can then have a look at the edits in the file to determine at least partly what went wrong, and apply them after fixing anything necessary so that you don't loose you work.

**Comment by rrogerss** [comment]
It was this Way that I was having issues with. https://www.openstreetmap.org/way/721045538/history#map=19/32.93885/-97.07967

If you look North of it you'll see another Way about the same shape as this one with the same features. So I tried to copy, paste, and rotate the shape the previous shape to avoid drawing the whole thing out again. The mystery shapes would appear about 3-4 parking spaces above where I was trying to place it.

**Comment by rrogerss** [comment]
I've already uninstalled the app then reinstalled it again which cleaned up the problem, but I could try to recreate it again if you want to look into the problem.

**Comment by simonpoole** [comment]
> If you look North of it you'll see another Way about the same shape as this one with the same features. So I tried to copy, paste, and rotate the shape the previous shape to avoid drawing the whole thing out again. The mystery shapes would appear about 3-4 parking spaces above where I was trying to place it.

Did you by any chance try to undo a paste? 

Because if you did, you likely ran in to an issue that I fixed yesterday: https://github.com/MarcusWolschon/osmeditor4android/commit/5087c5c4f77633223c043a045291b599dfe23856 which had the potential to create a weird object (actually undoing pastes was previously never really supported, but somehow that was never documented anywhere obvious). I backported the fix to 13.1 so at least that will be available with this months update.

I didn't ask before but there wasn't actually a crash at any time during your issue and you were nevery asked to submit a crash dump?

**Comment by rrogerss** [comment]
Yep. Everytime the shape would disappear I would undo back before the paste. 

As far as the Rotate Tool, I would rotate the shape but never got it quite right on the first move (going too far over or not far enough) so I would adjust angle of the shape a couple of more times to get it just right. As I'm moving the shape around the shape would disappear (probably 30-60 seconds after the first rotation). That's when I would just undo everything before I pasted it.

I should also tell you that I wasn't familiar with this tool when I was using it and didn't realize for a little while that you don't require two fingers to twist the shape around so maybe that could have been causing the problem?

**Comment by simonpoole** [comment]
Hmmmm two fingers...... lets check. Yes that is interesting, zoom in/out isn't disabled during rotation, so being able to zoom is expected (just as being able to pan). I managed to get an object to vanish too after some twisting and zooming at the same time, I suspect that it is a case of the input values going wild in one way or the other.

**Comment by rrogerss** [comment]
Since you're able to make the shape disappear too, maybe this additional information could also be useful. If you try to upload changes with that invisible shape you should see some "API error" message. Then, if you find the shape in the update log and remove it before uploading again you might see a blank/black display (that I couldn't seem to get rid of even if I closed the app out all the way).

**Comment by rrogerss** [comment]
Other than the issues I ran into, I just want to say that I enjoy this app very much. There is a bit of a learning curve, but when I discovered what that Preset search bar can do I was off to the races. Anyhow, if you're involved in the development of the app or know who is please thank them for a great tool.

**Comment by simonpoole** [comment]
Fixed (hopefully) in https://github.com/MarcusWolschon/osmeditor4android/commit/256bc229c535639238fa7d4c9d964036e9bd31f2 The problem really only happened when zoomed very far in, but that is naturally easy to do by accident with "pinch to zoom". The upside is that I took the opportunity and improved the code a bit so that rotating should be slightly less jerky now.

**Comment by simonpoole** [comment]
> 
> 
> Other than the issues I ran into, I just want to say that I enjoy this app very much. There is a bit of a learning curve, but when I discovered what that Preset search bar can do I was off to the races. Anyhow, if you're involved in the development of the app or know who is please thank them for a great tool.

Thanks for the praise

I'm currently the main developer (the app has been around for more than a decade now, and the torch has been transferred a couple of times).  Anyway if you like the current preset search, you'll love  the next version (beta hopefully starting soon), see https://twitter.com/sp8962/status/1162459329112547330

**Comment by rrogerss** [comment]
That's great! Now I don't have to wait to see what results appear. 😁

Like I said earlier, the app is fantastic as it is, but if you don't mind,
can I make a suggestion for a feature I'd love to have.

I have been messing around with parking lots a little bit on the map and I
think I like them better with the spaces showing (instead of with a large
parking area with just parking aisles going through them).

There is this great looking plug-in that I'd love to use, but I'm not sure
if I can use it thru this app (but I haven't tinkered with the JOSM parts
of the app yet).

Here is the link.
https://github.com/JOSM/josm-gridify

If I can't plug this into the app, can I request this as a future feature?
No rush, but I think it would be nice to have.

Anyhow, thanks again for all you do.

Russell Rogers

**Comment by simonpoole** [comment]
@rrogerss we can't use JOSM plugins both for techincal and legal reasons, so this would need to be a reimplementation (as with everything). Could you however open a new issue for the request so that we can keep track of the request?

**Comment by rrogerss** [comment]
Sure, thank you.
