### ISSUE TITLE
Hard Crash When Trying to View Relation Tags

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#992]
Description:
---

Select a relation and touch the tags button at the bottom.  Vespucci locks up for about two seconds and then hard crashes.  Reopening appears to return to the last editing state.  I've reproduced this many times.

Device info:
---
<table>
<tr><td>App version</td><td>13.1.6.0</td></tr>
<tr><td>App version code</td><td>1209</td></tr>
<tr><td>Android build version</td><td>P550XXU1CQL1</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NMF26X.P550XXU1CQL1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>gt5note10wifi</td></tr>
<tr><td>Device model</td><td>SM-P550</td></tr>
<tr><td>Device product name</td><td>gt5note10wifixx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Jared Campbell</td></tr>
</table>

**Comment by simonpoole** [comment]
Have you submitted a crash dump and is this limited to a specific relation? 

In any case a concrete example would be good. Naturally both our automated and manual tests cover editing the tags on relations and while things will get slow for largish, that is > 1'000 members, relations, it should work in principle.

**Comment by simonpoole** [comment]
Crash dump found.

The crash is caused by a stack overflow in Relation.getBounds, indicating that the cause might be a loop in the relation, this is tricky to protect against, but in any case it would be important to determine which relation caused this and inspect it.

**Comment by jaredcampbell** [comment]
This was on the relation between the Harrod, OH point and boundary.  https://www.openstreetmap.org/relation/182723  The recursive relation has been resolved and it does appear that Vespucci no longer crashes when looking at the relation's tags.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/baede4fc7af97dc5fe01dbb6f3294d937151c2f5

Thanks for the report!

 A sure way to stop users from creating such a relation is difficult because the loop could be very deeply nested and also possibly the information might not even be available on device (consider a relation member that is a relation that isn't downloaded that contains a reference to the original relation :-)).  And I might note there are plenty of such relations around. 

In any case I'll give at least showing an error if a loop was actually detected a shot asap.
