### ISSUE TITLE
playground / swing != de:Schwingtor, sondern Schaukel

### ISSUE THREAD

**Issue by chatelao** [MarcusWolschon/osmeditor4android#999]
The Value "Swing" on a playground should be "Schaukel" not "Schwingtor"

**Comment by simonpoole** [comment]
Which language do you have set your device too? 

In general issues with presets are handled in the preset repo https://github.com/simonpoole/beautified-JOSM-preset/ but  for both vespucci and the presets you should likely be looking at fixing the translation directly in transifex https://www.transifex.com/openstreetmap/vespucci/dashboard/ for vespucci and https://www.transifex.com/openstreetmap/presets/dashboard/ for the presets.

Most of the time such issues are due to a missing translation context in the preset, or the same translation being used for multiple different translation contexts in the specific language.

**Comment by HolgerJeromin** [comment]
I am pretty sure you are using a third party or old preset. My current vespucci (german translation) translates a playground swing with the correct Schaukel. Which corresponds to this code:

https://github.com/simonpoole/beautified-JOSM-preset/blob/ee3a02dcc592701c2d37edfc5b24a8077354520d/i18n/preset_de.po#L16153-L16159

**Comment by chatelao** [comment]
Danke Holger, ich werde ihn mal neu installieren.

Holger Jeromin <notifications@github.com> schrieb am Mi., 25. Sep. 2019,
23:12:

**Comment by simonpoole** [comment]
Eine Neuinstallation ist sicher nicht nötig, die Presets können unabhängig heruntergeladen und installiert werden. Ader wie schon gesagt, ohne zu Wissen welche Sprache auf dem Gerät eingestellt ist, kann man nichts zu der Ursache des Problems sagen.

**Comment by chatelao** [comment]
Also, das Gerät läuft unter Deutsch.

Das Wort "Schwingtor" kommt, wenn ich einzelne Tags hinzufüge, den key
"playground" erfasse, dann kommt bei "Swing" die Übersetzung "Schwingtor".

Ich weiss nicht, ob in dieser Konstellation der Key als Kontext gebraucht
wird. In Fall "barrier" wäre "Schwingtor" sicher richtig.

Simon Poole <notifications@github.com> schrieb am Do., 26. Sep. 2019, 11:12:

**Comment by simonpoole** [comment]
> 
> Also, das Gerät läuft unter Deutsch. 

Ja aber de_DE, de_CH oder de_AT?

**Comment by chatelao** [comment]
Most probably de-ch

**Comment by simonpoole** [comment]
See https://www.transifex.com/openstreetmap/presets/translate/#de_CH/presetpot/50934395?q=text%3Aswing you simply need to fix the translation.

**Comment by HolgerJeromin** [comment]
I just fixed the preset `Schaukel` (and also the wrong `Drehbrücke`)

**Comment by chatelao** [comment]
Vielen Dank Holger. Mit dem Mobiltelefon (und ohne Laptop) auf Griechenland
geht alles sehr holprig ☺️

Holger Jeromin <notifications@github.com> schrieb am Mo., 30. Sep. 2019,
14:57:

**Comment by simonpoole** [comment]
Note the simple workaround till the presets have been updated is to switch to de_DE.

**Comment by chatelao** [comment]
:-) - we are in for the long run

Simon Poole <notifications@github.com> schrieb am Mo., 30. Sep. 2019, 15:58:
